// packages/shared/utils/src/lib/rules/combat_reactions.ts
//
// Pure, deterministic reaction mechanics — Combat-08.
//
// This release implements exactly ONE reaction: an opportunity attack on a
// hostile actor voluntarily leaving a reactor's melee threat range. The
// mechanics here are pure: they compute windows, ordering, eligibility and
// continuation, and never roll dice or mutate state. The kernel commits.
//
// Invariants (contract §"Bounded reactions"):
//   - The window opens BEFORE committing the movement step that exits the
//     threat range; the exit cell is the trigger cell.
//   - Forced movement, teleport-like authored movement and reaction-generated
//     movement never trigger.
//   - Simultaneous eligible reactors are ordered by initiative DESC, then
//     stable id ASC.
//   - Eligibility is revalidated immediately before resolution.
//   - Nesting is capped at one: a reaction attack opens no further window.
//   - A declined or no-longer-legal reaction spends no reaction resource and
//     no RNG. An accepted legal attack consumes one reaction whether it hits
//     or misses.
//   - Movement is charged only for committed cells.
//
// Contract: C-532 AC-3

import type {
  CombatAbilityDefinition,
  CombatantState,
  GridPoint,
  ParticipationState,
  ReactionRegistry,
  ReactionWindow,
  RegisteredReactionDefinition,
  SerializableCommandContinuation,
} from '@aikami/types';

/** Movement causes a window only when it is voluntary. */
export const MOVEMENT_CAUSES_OPPORTUNITY_ATTACK = {
  /** Ordinary player/AI movement. */
  voluntary: true,
  /** Environmental forced movement (C-531). */
  forced: false,
  /** Teleport-like authored movement. */
  teleport: false,
  /** Movement generated by a reaction itself. */
  reaction: false,
} as const;

export type MovementCause = keyof typeof MOVEMENT_CAUSES_OPPORTUNITY_ATTACK;

const manhattan = (a: GridPoint, b: GridPoint): number => Math.abs(a.x - b.x) + Math.abs(a.y - b.y);

/** Whether `reactorTeam` is hostile toward `moverTeam`. Neutral never reacts. */
export const isHostileToward = (
  reactorTeam: CombatantState['team'],
  moverTeam: CombatantState['team'],
): boolean => {
  if (reactorTeam === 'neutral' || moverTeam === 'neutral') {
    return false;
  }
  const moverIsFriendly = moverTeam === 'player' || moverTeam === 'ally';
  const reactorIsFriendly = reactorTeam === 'player' || reactorTeam === 'ally';
  return moverIsFriendly !== reactorIsFriendly;
};

// ---------------------------------------------------------------------------
// Trigger detection
// ---------------------------------------------------------------------------

export type OpportunityTriggerGroup = {
  /** The cell the mover is attempting to enter (the trigger cell). */
  triggerCell: GridPoint;
  /** Index into the evaluated path of `triggerCell`. */
  pathIndex: number;
  /** Eligible reactors ordered by initiative desc, then stable id asc. */
  reactorIds: string[];
};

/** The registered opportunity-attack reaction, or `null` when unregistered. */
export const opportunityReaction = (
  registry: ReactionRegistry,
): RegisteredReactionDefinition | null =>
  registry.definitions.find((definition) => definition.triggerKind === 'opportunity_attack') ??
  null;

/**
 * Whether a reactor is eligible to react right now.
 *
 * `targetPosition` is the mover's position at the moment the reaction
 * resolves — which, because the window opens BEFORE the exiting step is
 * committed, is the cell the mover is leaving. The registered ability's own
 * targeting rules are checked from the reactor's current position to that
 * point; no reaction-specific attack rules exist.
 *
 * Every clause is a kernel fact: participation, reaction budget, ability
 * ownership, catalog presence and the ability's own targeting rules.
 */
export const reactorIsEligible = (options: {
  reactor: CombatantState;
  mover: CombatantState;
  participation: ParticipationState | undefined;
  reaction: RegisteredReactionDefinition;
  ability: CombatAbilityDefinition | undefined;
  targetPosition: GridPoint;
}): boolean => {
  const { reactor, mover, participation, reaction, ability } = options;
  if (!isHostileToward(reactor.team, mover.team)) {
    return false;
  }
  // A downed or defeated mover cannot be attacked by a reaction — the
  // opportunity was against a voluntary withdrawal that is no longer happening.
  if (mover.defeated || mover.downed) {
    return false;
  }
  if (reactor.defeated || reactor.downed) {
    return false;
  }
  if (participation !== undefined && participation.status !== 'active') {
    return false;
  }
  if (!reactor.budget.reactionAvailable) {
    return false;
  }
  if (!reactor.abilityIds.includes(reaction.abilityId)) {
    return false;
  }
  if (ability === undefined) {
    return false;
  }
  return manhattan(reactor.position, options.targetPosition) <= ability.rangeCells;
};

const orderReactors = (reactors: readonly CombatantState[]): CombatantState[] =>
  [...reactors].sort(
    (a, b) => b.initiative - a.initiative || (a.combatantId < b.combatantId ? -1 : 1),
  );

/**
 * Computes every opportunity-attack trigger group a voluntary move would
 * produce, in path order.
 *
 * The mover's current position counts as the cell *before* `path[0]`: a
 * reactor already in range at the mover's start is exited at the first path
 * cell that leaves that reactor's threat range.
 */
export const computeOpportunityTriggers = (options: {
  mover: CombatantState;
  path: readonly GridPoint[];
  combatants: Record<string, CombatantState>;
  participation: Record<string, ParticipationState>;
  registry: ReactionRegistry;
  abilityCatalog: Record<string, CombatAbilityDefinition>;
  cause: MovementCause;
  /** True while a reaction window is already open — nesting is capped at one. */
  nested: boolean;
  /**
   * Reactors already offered a window for this suspended command. They are
   * never offered the same command's trigger twice.
   */
  alreadyOfferedReactorIds?: readonly string[];
}): OpportunityTriggerGroup[] => {
  if (!MOVEMENT_CAUSES_OPPORTUNITY_ATTACK[options.cause] || options.nested) {
    return [];
  }
  const reaction = opportunityReaction(options.registry);
  if (reaction === null) {
    return [];
  }

  const reactorCandidates = Object.values(options.combatants).filter(
    (combatant) =>
      combatant.combatantId !== options.mover.combatantId &&
      !(options.alreadyOfferedReactorIds ?? []).includes(combatant.combatantId),
  );
  const moverCells: GridPoint[] = [options.mover.position, ...options.path];
  const groups: OpportunityTriggerGroup[] = [];

  for (let index = 0; index < options.path.length; index++) {
    const before = moverCells[index];
    const after = moverCells[index + 1];
    const eligible: CombatantState[] = [];
    for (const reactor of reactorCandidates) {
      const wasInRange = manhattan(before, reactor.position) <= reaction.threatRangeCells;
      const stillInRange = manhattan(after, reactor.position) <= reaction.threatRangeCells;
      if (!wasInRange || stillInRange) {
        continue;
      }
      if (
        reactorIsEligible({
          reactor,
          mover: options.mover,
          participation: options.participation[reactor.combatantId],
          reaction,
          ability: options.abilityCatalog[reaction.abilityId],
          // The mover has not yet committed the exiting step, so it is still
          // in the cell it is leaving.
          targetPosition: before,
        })
      ) {
        eligible.push(reactor);
      }
    }
    if (eligible.length > 0) {
      groups.push({
        triggerCell: { x: after.x, y: after.y },
        pathIndex: index,
        reactorIds: orderReactors(eligible).map((reactor) => reactor.combatantId),
      });
    }
  }

  return groups;
};

// ---------------------------------------------------------------------------
// Window construction and queue advance
// ---------------------------------------------------------------------------

/** Deterministic window id — no ambient randomness. */
export const reactionWindowId = (
  initiatingCommandId: string,
  pathIndex: number,
  version: number,
): string => `rw:${initiatingCommandId}:${pathIndex}:${version}`;

export const buildReactionWindow = (options: {
  initiatingCommandId: string;
  moverId: string;
  reactionId: string;
  trigger: OpportunityTriggerGroup;
  continuation: SerializableCommandContinuation;
  version: number;
}): ReactionWindow => ({
  windowId: reactionWindowId(
    options.initiatingCommandId,
    options.trigger.pathIndex,
    options.version,
  ),
  version: options.version,
  status: 'open',
  initiatingCommandId: options.initiatingCommandId,
  moverId: options.moverId,
  reactionId: options.reactionId,
  reactorQueue: [...options.trigger.reactorIds],
  currentReactorId: options.trigger.reactorIds[0] ?? null,
  triggerCell: { ...options.trigger.triggerCell },
  continuation: options.continuation,
});

/**
 * Advances the queue past the current reactor. Returns the updated window; a
 * drained queue leaves `currentReactorId = null` and the caller resolves the
 * window.
 */
export const advanceReactorQueue = (window: ReactionWindow): ReactionWindow => {
  const current = window.currentReactorId;
  if (current === null) {
    return window;
  }
  const remaining = window.reactorQueue.filter((reactorId) => reactorId !== current);
  return {
    ...window,
    version: window.version + 1,
    reactorQueue: remaining,
    currentReactorId: remaining[0] ?? null,
    // The consumed reactor is recorded so the suspended command never offers
    // it the same trigger twice.
    continuation: {
      ...window.continuation,
      resolvedReactorIds: [...new Set([...window.continuation.resolvedReactorIds, current])],
    },
  };
};

/**
 * Marks a window resolved and records it on the continuation. A resolved
 * window is never re-entered, which is what makes a duplicate choice a no-op.
 */
export const resolveReactionWindow = (window: ReactionWindow): ReactionWindow => ({
  ...window,
  version: window.version + 1,
  status: 'resolved',
  currentReactorId: null,
  continuation: {
    ...window.continuation,
    resolvedWindowIds: [...window.continuation.resolvedWindowIds, window.windowId],
    resolvedReactorIds: [...window.continuation.resolvedReactorIds],
    pendingWindowId: null,
  },
});

/**
 * Whether a reaction selection request still matches the live window.
 * A stale or duplicate request is rejected here — before any resource or RNG
 * is spent.
 */
export const reactionRequestIsCurrent = (options: {
  window: ReactionWindow | undefined;
  windowId: string;
  windowVersion: number;
  reactorId: string;
}): boolean => {
  const { window } = options;
  if (window === undefined || window.status !== 'open') {
    return false;
  }
  if (window.windowId !== options.windowId || window.version !== options.windowVersion) {
    return false;
  }
  return window.currentReactorId === options.reactorId;
};

// ---------------------------------------------------------------------------
// Continuation
// ---------------------------------------------------------------------------

/**
 * Builds the resumable continuation for a move suspended at `pathIndex`.
 *
 * `committedCells` is the already-applied prefix (charged), `remainingPath`
 * excludes the mover's current cell so the resume never replays a committed
 * cell or charges it twice.
 */
export const buildMoveContinuation = (options: {
  continuationId: string;
  initiatingCommandId: string;
  combatantId: string;
  fullPath: readonly GridPoint[];
  committedPathIndex: number;
  spentMovement: number;
}): SerializableCommandContinuation => ({
  continuationId: options.continuationId,
  initiatingCommandId: options.initiatingCommandId,
  commandKind: 'move',
  combatantId: options.combatantId,
  committedCells: options.fullPath
    .slice(0, options.committedPathIndex + 1)
    .map((cell) => ({ x: cell.x, y: cell.y })),
  remainingPath: options.fullPath
    .slice(options.committedPathIndex + 1)
    .map((cell) => ({ x: cell.x, y: cell.y })),
  spentMovement: options.spentMovement,
  resolvedWindowIds: [],
  resolvedReactorIds: [],
  pendingWindowId: null,
});

/**
 * Whether the suspended command may resume after the reaction batch.
 *
 * An active or retreating mover may continue — a fleeing actor still on the
 * battlefield remains a participant. A mover that is downed, defeated,
 * removed or surrendered cannot continue: the remainder of the path is
 * cancelled. Contract: C-532 AC-2, AC-3.
 */
export const continuationCanResume = (options: {
  mover: CombatantState | undefined;
  participation: ParticipationState | undefined;
  phaseEnded: boolean;
}): boolean => {
  const { mover, participation } = options;
  if (options.phaseEnded || mover === undefined) {
    return false;
  }
  if (mover.defeated || mover.downed) {
    return false;
  }
  return (
    participation === undefined ||
    participation.status === 'active' ||
    participation.status === 'retreating'
  );
};

/** Reaction availability resets at the start of the reactor's own turn. */
export const resetReactionForTurn = (
  budget: CombatantState['budget'],
): CombatantState['budget'] => ({
  ...budget,
  reactionAvailable: true,
});
