// packages/backend/audio/tests/tts_worker_pool.test.ts
import { afterEach, describe, expect, test } from 'bun:test';
import type { TtsJob } from '../src/lib/tts_worker_pool.ts';
import { TtsWorkerPool } from '../src/lib/tts_worker_pool.ts';

describe('TtsWorkerPool', () => {
  let pool: TtsWorkerPool | undefined;

  afterEach(async () => {
    if (pool) {
      await pool.terminate();
      pool = undefined;
    }
  });

  test('creates workers and dispatches a single job', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const jobs: TtsJob[] = [{ id: 'job-1', text: 'Hello world.', sequence: 0 }];

    const results = await pool.processBatch({ jobs });

    expect(results).toHaveLength(1);
    expect(results[0].jobId).toBe('job-1');
    expect(results[0].audio).toBeInstanceOf(Float32Array);
    expect(results[0].audio.length).toBe(2400);
  });

  test('processes multiple jobs sequentially with concurrency=1', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const jobs: TtsJob[] = [
      { id: 'a', text: 'First.', sequence: 0 },
      { id: 'b', text: 'Second.', sequence: 1 },
      { id: 'c', text: 'Third.', sequence: 2 },
    ];

    const results = await pool.processBatch({ jobs });

    expect(results).toHaveLength(3);
    expect(results.map((r) => r.jobId)).toEqual(['a', 'b', 'c']);
    // Results should be in sequence order
    const sequences = results.map((r) => r.sequence);
    expect(sequences).toEqual([0, 1, 2]);
  });

  test('respects job sequence ordering (out-of-order completion reordered)', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const jobs: TtsJob[] = [
      { id: 'first', text: 'A.', sequence: 0 },
      { id: 'second', text: 'B.', sequence: 1 },
    ];

    const results = await pool.processBatch({ jobs });

    expect(results[0].sequence).toBe(0);
    expect(results[1].sequence).toBe(1);
  });

  test('concurrency=2 processes jobs in parallel', async () => {
    pool = new TtsWorkerPool({ concurrency: 2 });
    const jobs: TtsJob[] = [
      { id: 'a', text: 'Text.', sequence: 0 },
      { id: 'b', text: 'Text.', sequence: 1 },
    ];

    const start = performance.now();
    const results = await pool.processBatch({ jobs });
    const elapsed = performance.now() - start;

    expect(results).toHaveLength(2);
    // With synthetic mock (instant), should be very fast
    expect(elapsed).toBeLessThan(200);
  });

  test('aborts pending jobs on signal', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const controller = new AbortController();

    // Create many jobs but only allow 1 concurrency
    const jobs: TtsJob[] = Array.from({ length: 5 }, (_, i) => ({
      id: `job-${i}`,
      text: `Sentence ${i}.`,
      sequence: i,
    }));

    // Abort after a short delay
    setTimeout(() => controller.abort(), 5);

    try {
      await pool.processBatch({ jobs, signal: controller.signal });
      // May or may not throw depending on timing
    } catch (error) {
      expect((error as Error).name).toBe('AbortError');
    }

    // Pool should still be usable after abort
    const newResults = await pool.processBatch({
      jobs: [{ id: 'post-abort', text: 'Clean.', sequence: 0 }],
    });
    expect(newResults).toHaveLength(1);
    expect(newResults[0].jobId).toBe('post-abort');
  });

  test('terminate cleans up all workers', async () => {
    pool = new TtsWorkerPool({ concurrency: 2 });
    const results = await pool.processBatch({
      jobs: [{ id: 'before', text: 'Before.', sequence: 0 }],
    });
    expect(results).toHaveLength(1);

    await pool.terminate();

    // After terminate, processBatch should reject
    try {
      await pool.processBatch({
        jobs: [{ id: 'after', text: 'After.', sequence: 0 }],
      });
      // Should not reach here
      expect(false).toBe(true);
    } catch (error) {
      expect((error as Error).message).toContain('terminated');
    }
  });

  test('worker receives correct IPC messages', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const results = await pool.processBatch({
      jobs: [{ id: 'ipc-test', text: 'IPC test.', sequence: 0 }],
    });

    expect(results[0].jobId).toBe('ipc-test');
    // Audio was generated by worker through IPC → validates message passing
    expect(results[0].audio).toBeInstanceOf(Float32Array);
    expect(results[0].audio.length).toBe(2400);
  });

  test('handles empty job list gracefully', async () => {
    pool = new TtsWorkerPool({ concurrency: 1 });
    const results = await pool.processBatch({ jobs: [] });
    expect(results).toEqual([]);
  });

  test('pool info reports correct worker count', () => {
    pool = new TtsWorkerPool({ concurrency: 3 });
    const info = pool.getInfo();
    expect(info.totalWorkers).toBe(3);
    expect(info.activeWorkers).toBe(0);
    expect(info.terminated).toBe(false);
  });
});
