// packages/backend/database/src/lib/d1_schema.ts
//
// C-426 AC-1: the Cloudflare D1 schema (Drizzle `sqlite` dialect).
//
// This is the hub's server data plane on Cloudflare Workers. It carries the
// `packs` / `pack_versions` shapes forward from the Postgres schema
// (schema.ts, C-394) with the FK retargeted from `accounts.id` to Better
// Auth's `user.id`, adds Better Auth's own identity tables (`user`,
// `session`, `account`, `verification`), and adds the new `account_backups`
// table for the Turso save-backup feature (AC-6/AC-7).
//
// Relationship to schema.ts: the Postgres schema stays live until the
// decommission phase (AC-8) — Cloud Run keeps serving production traffic
// through the migration's rollback window. This file is the D1 target; the
// two schemas are intentionally separate files so neither migration path
// disturbs the other.
//
// DDL is generated by `drizzle-kit generate` against this schema and applied
// via `wrangler d1 migrations apply` (see drizzle.d1.config.ts). No
// hand-written DDL.

import { sql } from 'drizzle-orm';
import { check, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

// ── Better Auth identity tables ─────────────────────────────────────────
// Exact column shapes per Better Auth's D1/Drizzle adapter. Timestamps are
// unix-ms integers (SQLite has no native timestamp type). Booleans are
// integer 0/1.

/** A hub member — Better Auth's `user` table replaces the retired `accounts` table. */
export const users = sqliteTable(
  'user',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull(),
    image: text('image'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [uniqueIndex('user_email_unique').on(table.email)],
);

/** A Better Auth session — one row per active sign-in. */
export const sessions = sqliteTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    token: text('token').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
  },
  (table) => [
    uniqueIndex('session_token_unique').on(table.token),
    index('session_user_id_idx').on(table.userId),
  ],
);

/** A Better Auth account — one row per OAuth provider / email-password credential. */
export const accounts = sqliteTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    /** OAuth issuer — Better Auth requires this field on the account table. */
    issuer: text('issuer').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
    refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
    scope: text('scope'),
    password: text('password'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    index('account_user_id_idx').on(table.userId),
    // One identity per (issuer, accountId) — Better Auth's account model.
    uniqueIndex('account_issuer_account_id_unique').on(table.issuer, table.accountId),
  ],
);

/** A Better Auth verification token (email verification, password reset, …). */
export const verifications = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }),
});

// ── Catalog tables (carried forward from schema.ts, FK retargeted) ──────

/** packs.visibility — a SQLite CHECK constraint (no pgEnum in the sqlite dialect). */
export const PACK_VISIBILITY_VALUES = ['draft', 'public', 'unlisted', 'removed'] as const;
export type PackVisibility = (typeof PACK_VISIBILITY_VALUES)[number];

/**
 * Catalog identity and ownership. The pack's *content* lives in the static
 * index; this row exists so a pack can be owned, moderated and versioned.
 * `ownerAccountId` now references Better Auth's `user.id` (was `accounts.id`).
 */
export const packs = sqliteTable(
  'packs',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Url-safe, immutable once published — UNIQUE NOT NULL. */
    slug: text('slug').notNull(),
    /** Owner — RESTRICT FK to user.id (catalog rows are moderated, never cascaded away). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** Visibility state — SQLite CHECK constraint (see below). */
    visibility: text('visibility').notNull().default('draft'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('packs_slug_unique').on(table.slug),
    // Slug pattern: lowercase alphanumerics separated by single hyphens.
    // SQLite has no built-in regexp, so enforce the URL-safe character class
    // with GLOB and reject empty slugs. (The full hyphen-separation rule is
    // enforced at the repository/app layer.)
    check(
      'packs_slug_url_safe',
      sql`${table.slug} NOT GLOB '*[^a-z0-9-]*' AND length(${table.slug}) > 0`,
    ),
    check(
      'packs_visibility_valid',
      sql`${table.visibility} IN ('draft', 'public', 'unlisted', 'removed')`,
    ),
    // Ownership reads (moderation, per-owner listing) filter on this FK.
    index('packs_owner_account_id_idx').on(table.ownerAccountId),
  ],
);

/**
 * An immutable published version. `manifestHash` is the content address that
 * joins this row to its entry in the static index.
 */
export const packVersions = sqliteTable(
  'pack_versions',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Parent pack — RESTRICT FK to packs.id. */
    packId: text('pack_id')
      .notNull()
      .references(() => packs.id, { onDelete: 'restrict' }),
    /** Semver, unique per pack. */
    version: text('version').notNull(),
    /** sha256 of the canonical manifest bytes. */
    manifestHash: text('manifest_hash').notNull(),
    /** When the row was created — unpublished versions keep their creation time. */
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    /** Null while unpublished. */
    publishedAt: integer('published_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    // One pack cannot publish the same semver twice.
    uniqueIndex('pack_versions_pack_id_version_unique').on(table.packId, table.version),
  ],
);

// ── Save-backup metadata (AC-6/AC-7) ────────────────────────────────────
// The R2 object itself holds the Turso DB bytes; this row is the metadata.

/**
 * A player's Turso save backup. `r2Key` points at the object in the
 * `SAVES_BUCKET` R2 bucket (`saves/{accountId}/{timestamp}-{filename}`).
 * The metadata row is written only AFTER the R2 PUT succeeds (AC-6).
 */
export const accountBackups = sqliteTable(
  'account_backups',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Owner — CASCADE FK to user.id (a deleted account's backups go with it). */
    accountId: text('account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** R2 object key: saves/{accountId}/{timestamp}-{filename}. */
    r2Key: text('r2_key').notNull(),
    /** Size of the uploaded object in bytes. */
    sizeBytes: integer('size_bytes').notNull(),
    /** sha256 of the uploaded object bytes. */
    checksumSha256: text('checksum_sha256').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [index('account_backups_account_id_idx').on(table.accountId)],
);

// ── Row types (exported for repositories + the conformance test) ────────

export type D1UserRow = typeof users.$inferSelect;
export type D1SessionRow = typeof sessions.$inferSelect;
export type D1AccountRow = typeof accounts.$inferSelect;
export type D1VerificationRow = typeof verifications.$inferSelect;
export type D1PackRow = typeof packs.$inferSelect;
export type D1PackVersionRow = typeof packVersions.$inferSelect;
export type D1AccountBackupRow = typeof accountBackups.$inferSelect;
