// packages/backend/database/src/lib/schema.ts
//
// C-426 AC-1: the Cloudflare D1 schema (Drizzle `sqlite` dialect).
//
// This is the hub's server data plane on Cloudflare Workers. It carries the
// `packs` / `pack_versions` shapes forward from the Postgres schema
// (schema.ts, C-394) with the FK retargeted from `accounts.id` to Better
// Auth's `user.id`, adds Better Auth's own identity tables (`user`,
// `session`, `account`, `verification`), and adds the new `account_backups`
// table for the Turso save-backup feature (AC-6/AC-7).
//
// Relationship to schema.ts: the Postgres schema stays live until the
// decommission phase (AC-8) — Cloud Run keeps serving production traffic
// through the migration's rollback window. This file is the D1 target; the
// two schemas are intentionally separate files so neither migration path
// disturbs the other.
//
// DDL is generated by `drizzle-kit generate` against this schema and applied
// via `wrangler d1 migrations apply` (see drizzle.d1.config.ts). No
// hand-written DDL.

import { sql } from 'drizzle-orm';
import {
  check,
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from 'drizzle-orm/sqlite-core';

// ── Better Auth identity tables ─────────────────────────────────────────
// Exact column shapes per Better Auth's D1/Drizzle adapter. Timestamps are
// unix-ms integers (SQLite has no native timestamp type). Booleans are
// integer 0/1.

/** A hub member — Better Auth's `user` table replaces the retired `accounts` table. */
export const users = sqliteTable(
  'user',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).notNull(),
    image: text('image'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [uniqueIndex('user_email_unique').on(table.email)],
);

/** A Better Auth session — one row per active sign-in. */
export const sessions = sqliteTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    token: text('token').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
  },
  (table) => [
    uniqueIndex('session_token_unique').on(table.token),
    index('session_user_id_idx').on(table.userId),
  ],
);

/** A Better Auth account — one row per OAuth provider / email-password credential. */
export const accounts = sqliteTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    // 🔴 No `issuer` column. Better Auth 1.7.0–1.7.2 required one (NOT NULL,
    // unique with `account_id`); 1.7.3 removed that requirement and went back
    // to recognising an account by (providerId, accountId), as in 1.6. It
    // therefore never writes `issuer`, and a NOT NULL column here rejects
    // every sign-up and account link — Better Auth's own schema check detects
    // exactly that and refuses to serve (SCHEMA_MISMATCH). See
    // drizzle-d1/0006_drop_account_issuer.sql and
    // https://www.better-auth.com/docs/guides/1-7-upgrade-guide
    userId: text('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
    refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
    scope: text('scope'),
    password: text('password'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  // No unique index on (providerId, accountId): Better Auth 1.7.3 does not
  // declare one, and enforcing it in the database would fail the migration
  // on any 1.7.0–1.7.2 rows that share a provider key across issuers — which
  // the upgrade guide asks you to resolve by hand before upgrading.
  (table) => [index('account_user_id_idx').on(table.userId)],
);

/** A Better Auth verification token (email verification, password reset, …). */
export const verifications = sqliteTable('verification', {
  id: text('id').primaryKey(),
  identifier: text('identifier').notNull(),
  value: text('value').notNull(),
  expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
  createdAt: integer('created_at', { mode: 'timestamp_ms' }),
  updatedAt: integer('updated_at', { mode: 'timestamp_ms' }),
});

/**
 * A Better Auth device-authorization code (C-426 AC-5 device handoff).
 * One row per pending/approved/denied device sign-in request. Column JS
 * property names match the device-authorization plugin's camelCase fields.
 */
export const deviceCodes = sqliteTable(
  'deviceCode',
  {
    id: text('id').primaryKey(),
    deviceCode: text('device_code').notNull(),
    userCode: text('user_code').notNull(),
    userId: text('user_id').references(() => users.id, { onDelete: 'cascade' }),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    status: text('status').notNull(),
    lastPolledAt: integer('last_polled_at', { mode: 'timestamp_ms' }),
    pollingInterval: integer('polling_interval'),
    clientId: text('client_id'),
    scope: text('scope'),
    // The device-authorization plugin does not populate these, so keep them
    // nullable (unlike the core identity tables where Better Auth sets them).
    createdAt: integer('created_at', { mode: 'timestamp_ms' }),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    uniqueIndex('device_code_device_code_unique').on(table.deviceCode),
    uniqueIndex('device_code_user_code_unique').on(table.userCode),
    index('device_code_user_id_idx').on(table.userId),
  ],
);

// ── Catalog tables (carried forward from schema.ts, FK retargeted) ──────

/** packs.visibility — a SQLite CHECK constraint (no pgEnum in the sqlite dialect). */
export const PACK_VISIBILITY_VALUES = ['draft', 'public', 'unlisted', 'removed'] as const;
export type PackVisibility = (typeof PACK_VISIBILITY_VALUES)[number];

/**
 * Catalog identity and ownership. The pack's *content* lives in the static
 * index; this row exists so a pack can be owned, moderated and versioned.
 * `ownerAccountId` now references Better Auth's `user.id` (was `accounts.id`).
 */
export const packs = sqliteTable(
  'packs',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Url-safe, immutable once published — UNIQUE NOT NULL. */
    slug: text('slug').notNull(),
    /** Owner — RESTRICT FK to user.id (catalog rows are moderated, never cascaded away). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** Visibility state — SQLite CHECK constraint (see below). */
    visibility: text('visibility').$type<PackVisibility>().notNull().default('draft'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('packs_slug_unique').on(table.slug),
    // Slug pattern: lowercase alphanumerics separated by single hyphens.
    // SQLite has no built-in regexp, so enforce the URL-safe character class
    // with GLOB and reject empty slugs. (The full hyphen-separation rule is
    // enforced at the repository/app layer.)
    check(
      'packs_slug_url_safe',
      sql`${table.slug} NOT GLOB '*[^a-z0-9-]*' AND length(${table.slug}) > 0`,
    ),
    check(
      'packs_visibility_valid',
      sql`${table.visibility} IN ('draft', 'public', 'unlisted', 'removed')`,
    ),
    // Ownership reads (moderation, per-owner listing) filter on this FK.
    index('packs_owner_account_id_idx').on(table.ownerAccountId),
  ],
);

/**
 * An immutable published version. `manifestHash` is the content address that
 * joins this row to its entry in the static index.
 */
export const packVersions = sqliteTable(
  'pack_versions',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Parent pack — RESTRICT FK to packs.id. */
    packId: text('pack_id')
      .notNull()
      .references(() => packs.id, { onDelete: 'restrict' }),
    /** Semver, unique per pack. */
    version: text('version').notNull(),
    /** sha256 of the canonical manifest bytes. */
    manifestHash: text('manifest_hash').notNull(),
    /** When the row was created — unpublished versions keep their creation time. */
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    /** Null while unpublished. */
    publishedAt: integer('published_at', { mode: 'timestamp_ms' }),
  },
  (table) => [
    // One pack cannot publish the same semver twice.
    uniqueIndex('pack_versions_pack_id_version_unique').on(table.packId, table.version),
  ],
);

// ── Save-backup metadata (AC-6/AC-7) ────────────────────────────────────
// The R2 object itself holds the Turso DB bytes; this row is the metadata.

/**
 * A player's Turso save backup. `r2Key` points at the object in the
 * `SAVES_BUCKET` R2 bucket (`saves/{accountId}/{timestamp}-{filename}`).
 * The metadata row is written only AFTER the R2 PUT succeeds (AC-6).
 */
export const accountBackups = sqliteTable(
  'account_backups',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Owner — CASCADE FK to user.id (a deleted account's backups go with it). */
    accountId: text('account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** R2 object key: saves/{accountId}/{timestamp}-{filename}. */
    r2Key: text('r2_key').notNull(),
    /** Size of the uploaded object in bytes. */
    sizeBytes: integer('size_bytes').notNull(),
    /** sha256 of the uploaded object bytes. */
    checksumSha256: text('checksum_sha256').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [index('account_backups_account_id_idx').on(table.accountId)],
);

// ── Community map studio tables (C-508) ─────────────────────────────────
// Per-user drafts + hub-published community maps. The curated catalog remains
// a CI-owned static R2 index; these rows back the hub-served community
// namespace that the map studio writes to.

/**
 * A creator's private, owner-scoped map draft. The native scene document is
 * stored inline (the API bounds it) so a draft reloads with no catalog access.
 */
export const mapDrafts = sqliteTable(
  'map_drafts',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Owner — CASCADE FK to user.id (a deleted account's drafts go with it). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Human-readable draft name. */
    name: text('name').notNull(),
    /** Native `aikami.scene` JSON. */
    document: text('document').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [index('map_drafts_owner_account_id_idx').on(table.ownerAccountId)],
);

/**
 * A published community map. Immutable per revision: a re-publish appends a
 * new revision. `documentHash` verifies the bytes and `r2Key` points at the
 * durable catalog-bucket copy.
 */
export const communityMaps = sqliteTable(
  'community_maps',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Url-safe public identifier, immutable once created. */
    slug: text('slug').notNull(),
    /** Owner — RESTRICT FK to user.id (published rows are moderated). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** Display title. */
    title: text('title').notNull(),
    /** Monotonic revision, starting at 1. */
    revision: integer('revision').notNull(),
    /** sha256 of the document bytes. */
    documentHash: text('document_hash').notNull(),
    /** R2 object key: community/{slug}/{revision}.json (catalog bucket). */
    r2Key: text('r2_key').notNull(),
    /** Size of the uploaded document in bytes. */
    sizeBytes: integer('size_bytes').notNull(),
    /** This revision's native `aikami.scene` JSON (served without an R2 round-trip). */
    document: text('document').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('community_maps_slug_revision_unique').on(table.slug, table.revision),
    check(
      'community_maps_slug_url_safe',
      sql`${table.slug} NOT GLOB '*[^a-z0-9-]*' AND length(${table.slug}) > 0`,
    ),
    check('community_maps_revision_positive', sql`${table.revision} >= 1`),
    index('community_maps_owner_account_id_idx').on(table.ownerAccountId),
    index('community_maps_updated_at_idx').on(table.updatedAt, table.id),
  ],
);

// ── Community asset publishing tables (C-513) ───────────────────────────
// Reserve → upload to a *private* intake bucket → commit a pending row →
// promote into the shared content-addressed `assets/` namespace at moderation
// time. There is no cross-store transaction between D1 and R2, so the staging
// row is the recovery point that makes the sequence representable.

/** `asset_publish_staging.state` — the attempt state machine. */
export const ASSET_PUBLISH_STAGING_STATES = [
  'reserved',
  'uploaded',
  'committed',
  'rolled_back',
  'orphaned',
] as const;
/** One in-flight publish attempt's state. */
export type AssetPublishStagingState = (typeof ASSET_PUBLISH_STAGING_STATES)[number];

/**
 * One in-flight (or abandoned) community-asset publish attempt.
 *
 * AC-8's recovery point: `reserved` → `uploaded` → `committed`, with
 * `rolled_back` for a failed upload and `orphaned` for a row whose bytes were
 * never confirmed. Ownership is CASCADE — an abandoned attempt is not a
 * published record.
 */
export const assetPublishStaging = sqliteTable(
  'asset_publish_staging',
  {
    /** Stable internal id — uuid, server-generated (== the upload id). */
    id: text('id').primaryKey(),
    /** Owner — CASCADE FK to user.id (an abandoned attempt is not a publication). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** Reserved public identifier. */
    slug: text('slug').notNull(),
    /** Reserved revision, >= 1. */
    revision: integer('revision').notNull(),
    title: text('title').notNull(),
    /** CatalogCategory value. */
    category: text('category').notNull(),
    /** Resolver tag, url-safe. */
    tag: text('tag').notNull(),
    /** Lowercase extension including the dot. */
    ext: text('ext').notNull(),
    /** Declared at reservation; must equal the upload's Content-Length. */
    sizeBytes: integer('size_bytes').notNull(),
    /** Hub-computed sha256 of the uploaded bytes; absent while `reserved`. */
    sha256: text('sha256'),
    /** `staging/<accountId>/<uploadId>` in the private intake bucket. */
    stagingKey: text('staging_key').notNull(),
    /** Attempt state — SQLite CHECK constraint (see below). */
    state: text('state').$type<AssetPublishStagingState>().notNull().default('reserved'),
    /** Redacted provenance projection (never prompts or local paths). */
    provenanceJson: text('provenance_json').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    // One *live* reservation per (owner, slug, revision). Rolled-back attempts
    // are excluded so a retry after a failed upload can re-reserve.
    uniqueIndex('asset_publish_staging_live_unique')
      .on(table.ownerAccountId, table.slug, table.revision)
      .where(sql`${table.state} <> 'rolled_back'`),
    check(
      'asset_publish_staging_slug_url_safe',
      sql`${table.slug} NOT GLOB '*[^a-z0-9-]*' AND length(${table.slug}) > 0`,
    ),
    check('asset_publish_staging_revision_positive', sql`${table.revision} >= 1`),
    check(
      'asset_publish_staging_state_valid',
      sql`${table.state} IN ('reserved', 'uploaded', 'committed', 'rolled_back', 'orphaned')`,
    ),
    index('asset_publish_staging_owner_account_id_idx').on(table.ownerAccountId),
    index('asset_publish_staging_staging_key_idx').on(table.stagingKey),
    index('asset_publish_staging_state_updated_at_idx').on(table.state, table.updatedAt),
  ],
);

/**
 * Atomic per-account publish reservations for one fixed quota window.
 *
 * Unlike an isolate-local counter, the composite primary key lets D1
 * serialize concurrent reservations across every Worker isolate.
 */
export const assetPublishRateLimits = sqliteTable(
  'asset_publish_rate_limits',
  {
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    windowStartedAt: integer('window_started_at', { mode: 'timestamp_ms' }).notNull(),
    hits: integer('hits').notNull(),
  },
  (table) => [primaryKey({ columns: [table.ownerAccountId, table.windowStartedAt] })],
);

/** `community_assets.moderation_state` — the only states that ever exist. */
export const COMMUNITY_ASSET_MODERATION_STATES = ['pending', 'approved', 'rejected'] as const;
/** One committed revision's moderation state. */
export type CommunityAssetModerationState = (typeof COMMUNITY_ASSET_MODERATION_STATES)[number];

/**
 * An immutable committed community-asset revision, content-addressed.
 *
 * `r2Key` and `promotedAt` are written by the approval-time copy into
 * `CATALOG_BUCKET` — absent ⇒ the bytes are still only in the private intake
 * bucket and are not public (AC-1, AC-3, AC-6). Ownership is RESTRICT (C-508
 * precedent): a published row is moderated, never cascaded away.
 */
export const communityAssets = sqliteTable(
  'community_assets',
  {
    /** Stable internal id — uuid, server-generated. */
    id: text('id').primaryKey(),
    /** Owner — RESTRICT FK to user.id (published rows are moderated). */
    ownerAccountId: text('owner_account_id')
      .notNull()
      .references(() => users.id, { onDelete: 'restrict' }),
    /** Url-safe public identifier. */
    slug: text('slug').notNull(),
    /** Monotonic revision, starting at 1. */
    revision: integer('revision').notNull(),
    title: text('title').notNull(),
    /** CatalogCategory value. */
    category: text('category').notNull(),
    /** Resolver tag. */
    tag: text('tag').notNull(),
    /** Content address — hub-computed, never client-claimed. */
    sha256: text('sha256').notNull(),
    /** `assets/<hash[0:2]>/<hash><ext>` — written at promotion, NOT at publish. */
    r2Key: text('r2_key'),
    sizeBytes: integer('size_bytes').notNull(),
    /** Lowercase extension including the dot. */
    ext: text('ext').notNull(),
    /** Redacted projection of AssetProvenance — the single source of truth. */
    provenanceJson: text('provenance_json').notNull(),
    /** Derived from provenanceJson for gate/index queries (SPDX or 'proprietary'). */
    license: text('license'),
    /** Moderation state — SQLite CHECK constraint (see below). */
    moderationState: text('moderation_state')
      .$type<CommunityAssetModerationState>()
      .notNull()
      .default('pending'),
    /** Operator reason for a rejection. */
    moderationNote: text('moderation_note'),
    moderatedByAccountId: text('moderated_by_account_id'),
    moderatedAt: integer('moderated_at', { mode: 'timestamp_ms' }),
    /** Set by the approval-time copy into CATALOG_BUCKET; absent ⇒ not public. */
    promotedAt: integer('promoted_at', { mode: 'timestamp_ms' }),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' }).notNull(),
  },
  (table) => [
    uniqueIndex('community_assets_slug_revision_unique').on(table.slug, table.revision),
    check(
      'community_assets_slug_url_safe',
      sql`${table.slug} NOT GLOB '*[^a-z0-9-]*' AND length(${table.slug}) > 0`,
    ),
    check('community_assets_revision_positive', sql`${table.revision} >= 1`),
    check(
      'community_assets_moderation_state_valid',
      sql`${table.moderationState} IN ('pending', 'approved', 'rejected')`,
    ),
    check(
      'community_assets_ext_lowercase',
      sql`${table.ext} LIKE '.%' AND ${table.ext} = lower(${table.ext})`,
    ),
    index('community_assets_owner_account_id_idx').on(table.ownerAccountId),
    index('community_assets_updated_at_idx').on(table.updatedAt, table.id),
    // Public browse reads only approved + promoted rows.
    index('community_assets_browse_idx').on(
      table.moderationState,
      table.promotedAt,
      table.updatedAt,
    ),
    // Reference-aware cleanup: is this content address still referenced?
    index('community_assets_sha256_idx').on(table.sha256),
  ],
);

// ── Row types (exported for repositories + the conformance test) ────────

export type D1UserRow = typeof users.$inferSelect;
export type D1SessionRow = typeof sessions.$inferSelect;
export type D1AccountRow = typeof accounts.$inferSelect;
export type D1VerificationRow = typeof verifications.$inferSelect;
export type D1DeviceCodeRow = typeof deviceCodes.$inferSelect;
export type D1PackRow = typeof packs.$inferSelect;
export type D1PackVersionRow = typeof packVersions.$inferSelect;
export type D1AccountBackupRow = typeof accountBackups.$inferSelect;
export type D1MapDraftRow = typeof mapDrafts.$inferSelect;
export type D1CommunityMapRow = typeof communityMaps.$inferSelect;
export type D1AssetPublishStagingRow = typeof assetPublishStaging.$inferSelect;
export type D1AssetPublishRateLimitRow = typeof assetPublishRateLimits.$inferSelect;
export type D1CommunityAssetRow = typeof communityAssets.$inferSelect;

// ── Backward-compatible aliases (C-436: pg schema removed, types kept) ──
// These were previously exported from the pg schema (schema.ts, pg-core).
// They are now aliases to the D1 equivalents so existing consumers
// (conformance test, deploy scripts) continue to compile.
export type AccountRow = D1AccountRow;
export type PackRow = D1PackRow;
export type PackVersionRow = D1PackVersionRow;
