# apps/backend/local-stack/compose.intel.yaml
#
# Intel / SYCL backend (Arc GPUs, recent integrated graphics).
#
# .env:
#   COMPOSE_FILE=compose.yaml:compose.intel.yaml
#   COMPOSE_PROFILES=text,image,voice,stt,client

services:
  text:
    image: ghcr.io/ggml-org/llama.cpp:server-intel@sha256:e50c9adcb27750f721a8c22d295df48c1ad6480e57e78f71a89b9c1585fa4153

  image:
    image: ghcr.io/leejet/stable-diffusion.cpp:master-sycl@sha256:1b06c16e6d7e10b667d06159a0c227f507413ca4c01a8c49e9c36e084c087a3b
