# apps/backend/local-stack/compose.intel.yaml
#
# Intel / SYCL backend (Arc GPUs, recent integrated graphics).
#
# .env:
#   COMPOSE_FILE=compose.yaml:compose.intel.yaml
#   COMPOSE_PROFILES=text,image,voice,stt,client

services:
  text:
    image: ghcr.io/ggml-org/llama.cpp:server-intel@sha256:91446be66969b3396813c94c89a34795c473252f71b84f118c83779baa0c755f

  image:
    image: ghcr.io/leejet/stable-diffusion.cpp:master-sycl@sha256:519c95a222ef5d4853bee802e9378a777d697e88164f84475ee4a5a55d6e7d59
