// scripts/src/lib/ops/__tests__/git_hooks.test.ts
//
// 🔴 The one property .moon/hooks/post-checkout and post-merge must never
// lose: they cannot fail.
//
// A non-zero post-checkout makes `git checkout` ITSELF exit non-zero, so every
// `git checkout && …` chain and every execFileSync git call breaks. Because
// `bun run <name>` resolves against whatever tree was just checked out,
// checking out a branch older than the `sync-workspace` script IS that
// failure. These hooks are therefore hand-written rather than generated by
// moon — moon's template opens `set -eo pipefail`, which propagates exactly
// the failure we cannot afford. See the comment block in .moon/workspace.yml.
//
// This test is the guard on that, so a future "tidy-up" that moves them into
// `vcs.hooks` (regenerating them with `set -eo pipefail`) fails here rather
// than in someone's terminal.

import { describe, expect, it } from 'bun:test';
import { spawnSync } from 'node:child_process';
import {
  chmodSync,
  existsSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { delimiter, join, resolve } from 'node:path';

const REPO_ROOT = import.meta.dir ? resolve(import.meta.dir, '../../../../..') : resolve('.');
const HOOKS = ['post-checkout', 'post-merge'];

describe('.moon/hooks fail-safe hooks', () => {
  for (const hook of HOOKS) {
    describe(hook, () => {
      const path = join(REPO_ROOT, '.moon/hooks', hook);

      it('exists and is executable', () => {
        expect(existsSync(path)).toBe(true);
        // Git only runs a hook with the execute bit; git tracks mode 100755,
        // so committing it preserves this across clones.
        expect(statSync(path).mode & 0o111).toBeGreaterThan(0);
      });

      it('has no `set -e` and ends with an unconditional exit 0', () => {
        const source = readFileSync(path, 'utf8');
        const code = source
          .split('\n')
          .map((line) => line.trim())
          .filter((line) => line && !line.startsWith('#'));

        expect(code.some((line) => /^set\s+-\w*e/.test(line))).toBe(false);
        expect(code.at(-1)).toBe('exit 0');
      });

      it('uses the trusted sync entrypoint and not a checked-out package script', () => {
        const source = readFileSync(path, 'utf8');
        expect(source).toContain(
          'bun run "$hook_directory/../../scripts/src/lib/ops/sync_workspace.ts"',
        );
        expect(source).not.toContain('bun run sync-workspace');
      });

      it('stays silent and succeeds when the sync process fails', () => {
        const temporaryDirectory = mkdtempSync(join(tmpdir(), 'aikami-git-hook-'));
        const stubPath = join(temporaryDirectory, 'bun');
        writeFileSync(
          stubPath,
          '#!/usr/bin/env bash\nprintf "sync stdout\\n"\nprintf "sync stderr\\n" >&2\nexit 17\n',
        );
        chmodSync(stubPath, 0o755);

        try {
          const args = hook === 'post-checkout' ? ['old', 'new', '1'] : [];
          const result = spawnSync(path, args, {
            cwd: REPO_ROOT,
            encoding: 'utf8',
            env: {
              ...process.env,
              PATH: `${temporaryDirectory}${delimiter}${process.env.PATH ?? ''}`,
            },
          });

          expect(result.status).toBe(0);
          expect(result.stdout).toBe('');
          expect(result.stderr).toBe('');
        } finally {
          rmSync(temporaryDirectory, { recursive: true, force: true });
        }
      });
    });
  }

  it('is NOT declared in .moon/workspace.yml vcs.hooks', () => {
    // No YAML parser is a dependency here, and none is needed: a declared
    // hook is a `<name>:` key, and every mention of these names in the file
    // today lives in a `#` comment explaining why they are NOT declared.
    const declaredKeys = readFileSync(join(REPO_ROOT, '.moon/workspace.yml'), 'utf8')
      .split('\n')
      .filter((line) => !line.trim().startsWith('#'))
      .map((line) => line.trim().match(/^([\w-]+):/)?.[1])
      .filter(Boolean);

    for (const hook of HOOKS) {
      // Declaring it hands generation back to moon, which wraps the command
      // in `set -eo pipefail` — the broken-checkout bug, reintroduced.
      expect(declaredKeys).not.toContain(hook);
    }
  });
});
