// Auto-generated by scripts/src/lib/ops/collect_lpc_assets.ts — DO NOT EDIT.
import type { LpcSlotDefinition } from '$lib/data/lpc_asset_catalog';

export const GENERATED_LPC_SLOTS: readonly LpcSlotDefinition[] = [
];

export const LPC_ASSET_IDS_BY_SLOT: Record<string, string[]> = {
};

/** All generated asset IDs as a flat string array — verified at generation. */
export const ALL_GENERATED_ASSET_IDS: readonly string[] = [];

export function getLpcCatalogPrompt(): string {
  const parts: string[] = ['Available LPC sprite components (asset IDs by slot):'];
  for (const [slot, ids] of Object.entries(LPC_ASSET_IDS_BY_SLOT)) {
    parts.push(`  ${slot}: ${ids.join(', ')}`);
  }
  parts.push('\\nWhen generating a character appearance, return a JSON object: {"lpcRecipe": {"head": "head/heads/human_male", ...}}');
  return parts.join("\\n");
}