// apps/frontend/client/src/lib/data/lpc_asset_catalog_generated.ts
//
// This file is auto-generated by scripts/src/lib/ops/collect_lpc_assets.ts
// and contains the full LPC spritesheet catalog. The file is not committed
// to the repository — run the collect script to regenerate it.
//
// The stub below exists so the sandbox resolver can be imported without
// a build error. It will be overwritten when the catalog is generated.

import type { LpcSlotDef } from '@aikami/frontend/engine';

export const GENERATED_LPC_SLOTS: LpcSlotDef[] = [];
