// apps/frontend/client/src/lib/services/gm/gm_types.ts
//
// Client-local types for the GM Narrative Director system. These are
// UI-layer constructs specific to the Aikami Client — not cross-boundary
// data — so they live in the app's local types, not shared packages.
//
// GmPromptContext, SceneDirection, ArcMemory, and related types are
// used exclusively within the client's GM services and ViewModels.
//
// For AddressMode and SessionSummary, import from $types directly.

// ---------------------------------------------------------------------------
// Address Mode — controls how the GM prompt addresses the player
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Prompt assembly input types
// ---------------------------------------------------------------------------

/**
 * World/character state snapshot fed into the GM prompt assembler.
 */
export type GmPromptContext = {
  readonly worldName: string;
  readonly regionName: string;
  readonly locationName: string;
  readonly locationDescription: string;
  readonly timeOfDay: string;
  readonly weather: string;
  readonly activeQuests: ReadonlyArray<{
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly status: string;
  }>;
  readonly nearbyNpcs: ReadonlyArray<GmNpcContext>;
  /** Party members with names + personalities for multi-character voice. */
  readonly partyMembers: ReadonlyArray<GmPartyMemberContext>;
  readonly playerCharacter: {
    readonly name: string;
    readonly class: string;
    readonly level: number;
    readonly currentHp: number;
    readonly maxHp: number;
  };
};

/**
 * Minimal NPC context for the GM system prompt.
 */
export type GmNpcContext = {
  readonly id: string;
  readonly name: string;
  readonly persona: string;
  readonly relationship: string;
  readonly currentActivity: string;
};

/**
 * Party member context for multi-character voice distinction.
 * Injected into the Party-mode GM prompt so the LLM can speak
 * as each party member in their distinct voice.
 */
export type GmPartyMemberContext = {
  readonly id: string;
  readonly name: string;
  readonly personality: string;
};

/**
 * Combat state context when in active combat.
 */
export type GmCombatContext = {
  readonly isInCombat: boolean;
  readonly round: number;
  readonly enemies: ReadonlyArray<{
    readonly name: string;
    readonly currentHp: number;
    readonly maxHp: number;
  }>;
  readonly allies: ReadonlyArray<{
    readonly name: string;
    readonly currentHp: number;
    readonly maxHp: number;
  }>;
};

// ---------------------------------------------------------------------------
// Prompt section priority tiers for budget enforcement (C-457)
// ---------------------------------------------------------------------------

/**
 * Priority tier for a prompt section.
 * "required" sections are always included and never dropped.
 * "high", "medium", "low" sections may be dropped in that order
 * when the assembled prompt exceeds the byte budget.
 */
export type PromptSectionPriority = 'required' | 'high' | 'medium' | 'low';

/**
 * A single section of the assembled GM prompt with priority metadata.
 */
export type PromptSection = {
  /** Human-readable section name for logging, e.g. "WORLD INFO" */
  readonly name: string;
  /** Formatted section content (may be multi-line) */
  readonly content: string;
  /** Priority tier for budget enforcement */
  readonly priority: PromptSectionPriority;
  /**
   * Optional partial rendering for a section built from a list of entries.
   *
   * 🔴 Without this, budget enforcement is all-or-nothing: a section that does
   * not fit is dropped whole. C-456 requires finer granularity for
   * `[NEARBY NPCS]` — a location with hundreds of NPC IDs must still
   * contribute the NPCs it can, keeping source order and omitting only the
   * trailing entries that do not fit, rather than vanishing entirely.
   *
   * `render(n)` returns the section rendered with only its first `n` entries.
   */
  readonly partial?: {
    readonly render: (entryCount: number) => string;
    readonly total: number;
  };
};

// ---------------------------------------------------------------------------
// Narrative Director types
// ---------------------------------------------------------------------------

/**
 * A narrative scene direction generated by the background LLM agent.
 *
 * Contains a formatted scene description and optional guidance for what
 * the player might encounter next.
 */
export type SceneDirection = {
  /** Unique identifier for this scene direction. */
  readonly id: string;
  /** The formatted scene description (2–4 sentences). */
  readonly description: string;
  /** Optional hints or guidance for the player. */
  readonly playerGuidance?: string;
  /** Timestamp when this direction was generated. */
  readonly createdAt: number;
  /** Whether the player has acknowledged this direction. */
  readonly acknowledged: boolean;
};

/**
 * Persistent arc memory stored across sessions for a given game.
 *
 * Tracks the narrative arcs that have developed and which scene
 * directions have been delivered. Used by the Narrative Director to
 * maintain continuity across save/load cycles.
 */
export type ArcMemory = {
  /** Unique arc identifier. */
  readonly arcId: string;
  /** Human-readable arc name. */
  readonly arcName: string;
  /** Detailed description of this narrative arc. */
  readonly description: string;
  /** Ordered list of scene directions generated in this arc. */
  readonly sceneDirections: ReadonlyArray<SceneDirection>;
  /** Whether this arc has been completed. */
  readonly isCompleted: boolean;
  /** Timestamp when this arc was last updated. */
  readonly updatedAt: number;
};

// ---------------------------------------------------------------------------
// Session Summary types
// ---------------------------------------------------------------------------
