// apps/frontend/client/src/lib/services/gm/gm_types.ts
//
// Client-local types for the GM Narrative Director system. These are
// UI-layer constructs specific to the Aikami Client — not cross-boundary
// data — so they live in the app's local types, not shared packages.
//
// GmPromptContext, SceneDirection, ArcMemory, and related types are
// used exclusively within the client's GM services and ViewModels.
//
// For AddressMode and SessionSummary, import from $types directly.

// ---------------------------------------------------------------------------
// Address Mode — controls how the GM prompt addresses the player
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Prompt assembly input types
// ---------------------------------------------------------------------------

/**
 * World/character state snapshot fed into the GM prompt assembler.
 */
export type GmPromptContext = {
  readonly worldName: string;
  readonly regionName: string;
  readonly locationName: string;
  readonly locationDescription: string;
  readonly timeOfDay: string;
  readonly weather: string;
  readonly activeQuests: ReadonlyArray<{
    readonly id: string;
    readonly name: string;
    readonly description: string;
    readonly status: string;
  }>;
  readonly nearbyNpcs: ReadonlyArray<GmNpcContext>;
  /** Party members with names + personalities for multi-character voice. */
  readonly partyMembers: ReadonlyArray<GmPartyMemberContext>;
  readonly playerCharacter: {
    readonly name: string;
    readonly class: string;
    readonly level: number;
    readonly currentHp: number;
    readonly maxHp: number;
  };
};

/**
 * Minimal NPC context for the GM system prompt.
 */
export type GmNpcContext = {
  readonly id: string;
  readonly name: string;
  readonly persona: string;
  readonly relationship: string;
  readonly currentActivity: string;
};

/**
 * Party member context for multi-character voice distinction.
 * Injected into the Party-mode GM prompt so the LLM can speak
 * as each party member in their distinct voice.
 */
export type GmPartyMemberContext = {
  readonly id: string;
  readonly name: string;
  readonly personality: string;
};

/**
 * Combat state context when in active combat.
 */
export type GmCombatContext = {
  readonly isInCombat: boolean;
  readonly round: number;
  readonly enemies: ReadonlyArray<{
    readonly name: string;
    readonly currentHp: number;
    readonly maxHp: number;
  }>;
  readonly allies: ReadonlyArray<{
    readonly name: string;
    readonly currentHp: number;
    readonly maxHp: number;
  }>;
};

// ---------------------------------------------------------------------------
// Narrative Director types
// ---------------------------------------------------------------------------

/**
 * A narrative scene direction generated by the background LLM agent.
 *
 * Contains a formatted scene description and optional guidance for what
 * the player might encounter next.
 */
export type SceneDirection = {
  /** Unique identifier for this scene direction. */
  readonly id: string;
  /** The formatted scene description (2–4 sentences). */
  readonly description: string;
  /** Optional hints or guidance for the player. */
  readonly playerGuidance?: string;
  /** Timestamp when this direction was generated. */
  readonly createdAt: number;
  /** Whether the player has acknowledged this direction. */
  readonly acknowledged: boolean;
};

/**
 * Persistent arc memory stored across sessions for a given game.
 *
 * Tracks the narrative arcs that have developed and which scene
 * directions have been delivered. Used by the Narrative Director to
 * maintain continuity across save/load cycles.
 */
export type ArcMemory = {
  /** Unique arc identifier. */
  readonly arcId: string;
  /** Human-readable arc name. */
  readonly arcName: string;
  /** Detailed description of this narrative arc. */
  readonly description: string;
  /** Ordered list of scene directions generated in this arc. */
  readonly sceneDirections: ReadonlyArray<SceneDirection>;
  /** Whether this arc has been completed. */
  readonly isCompleted: boolean;
  /** Timestamp when this arc was last updated. */
  readonly updatedAt: number;
};

// ---------------------------------------------------------------------------
// Session Summary types
// ---------------------------------------------------------------------------
