// .pi/extensions/contract_factory.ts
/**
 * Contract Factory Pi Extension.
 *
 * Registers pi tools for generating engineering contracts from TODO.md
 * backlog items. Wraps the contract_generator.ts logic so pi can create
 * contracts conversationally without invoking external CLI scripts.
 *
 * Tools:
 *   contract_scan_backlog  — Scan TODO.md and list all pending items
 *   contract_generate       — Generate a contract file from a TODO.md feature code
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';
import { Type } from 'typebox';

// ── Types ──────────────────────────────────────────────────

type BacklogItem = {
  featureCode: string;
  title: string;
  tier: string;
  bulletCount: number;
  bullets: string[];
  alreadyGenerated: boolean;
};

// ── Contract template ──────────────────────────────────────

const CONTRACT_TEMPLATE = `# Contract {FEATURE_CODE}: {TITLE}

## Metadata

| Field | Value |
|---|---|
| **Source** | TODO.md — {TIER} tier backlog item |
| **Target** | {path} — {brief description} |
| **Priority** | {TIER} — {one-line justification} |
| **Dependencies** | {DEPS} |
| **Status** | not_started |
| **Contract version** | 1.0.0 |

## Overview

{OVERVIEW}

## Design Reference

{Existing patterns in the repo to follow. Reference specific files, packages, or previous contracts.}

## Architecture Directives

{Use domain-level names and logical paths. Let Pi decide exact file placement based on its aikami-conventions skill.}

## State & Data Models

{Describe the data shape conceptually. STRICTLY FORBIDDEN to write framework boilerplate.}

## Scope Boundaries

- **In Scope:** {Bullet list}
- **Out of Scope:** {Bullet list}

## Acceptance Criteria

### AC-1: {Scenario Name}
**Given** {precondition}
**When** {action}
**Then** {expected outcome}

**Test Hooks**:
- Moon Task: {command}
- Integration: N/A
- E2E / Visual: N/A

## Implementation Sequence
1. **Phase 1 (Data/Logic)**: {first phase}
2. **Phase 2 (Integration)**: {second phase}
3. **Phase 3 (Validation)**: Run \`validate()\` and specific Moon tasks

## Edge Cases & Gotchas
- **{Scenario}**: {handling}

---

<!-- Generated by contract_factory pi extension from TODO.md -->
`;

// ── Dependency inference ───────────────────────────────────

const DEP_KEYWORDS: Record<string, string> = {
  firebase: 'C-014',
  database: 'C-014',
  dataconnect: 'C-014',
  'data connect': 'C-014',
  ai: 'C-015',
  llm: 'C-015',
  engine: 'C-016',
  game: 'C-016',
  pixi: 'C-016',
  ecs: 'C-016',
  canvas: 'C-016',
  svelte: 'C-009',
  viewmodel: 'C-120',
  view: 'C-120',
  sandbox: 'C-139',
  route: 'C-119',
  routing: 'C-119',
  auth: 'C-121',
  onboarding: 'C-122',
  character: 'C-123',
  combat: 'C-144',
  dialogue: 'C-128',
  npc: 'C-141',
  inventory: 'C-142',
  quest: 'C-143',
  audio: 'C-150',
  music: 'C-151',
  save: 'C-132',
  load: 'C-132',
  persist: 'C-132',
  swarm: 'C-300',
  agent: 'C-300',
  convention: 'C-304',
  lint: 'C-304',
  visual: 'C-181',
  test: 'C-011',
  token: 'C-301',
  router: 'C-301',
  cache: 'C-302',
  scratchpad: 'C-302',
};

const _inferDeps = (text: string): string =>
  [
    ...new Set(
      Object.entries(DEP_KEYWORDS)
        .filter(([kw]) => text.toLowerCase().includes(kw))
        .map(([, c]) => c),
    ),
  ]
    .sort()
    .join(', ') || '—';

// ── TODO.md parsing ────────────────────────────────────────

const _parseTodo = (cwd: string): BacklogItem[] => {
  const todoPath = resolve(cwd, 'TODO.md');
  if (!existsSync(todoPath)) {
    return [];
  }

  const content = readFileSync(todoPath, 'utf-8');
  const items: BacklogItem[] = [];

  // Split into sections
  const sections = content.split(/(?=^## )/m);
  let counter = 0;

  for (const section of sections) {
    let tier = 'P1';
    if (/in.progress|needs.polish/i.test(section)) {
      tier = 'P1';
    } else if (/backlog|planned|upcoming/i.test(section)) {
      tier = 'P2';
    } else if (/completed|done/i.test(section)) {
      continue;
    }

    // Extract numbered items
    const re = /###\s+(\d+)\.\s+(.+?)(?=\n###|\n##|$)/gs;
    let m: RegExpExecArray | null;

    while (true) {
      m = re.exec(section);
      if (m === null) {
        break;
      }
      const title = (m[2] ?? '').trim();
      const body = m[0];

      // Extract bullets
      const bullets: string[] = [];
      const br = /^\s*-\s+(.+)/gm;
      let bm: RegExpExecArray | null;
      while (true) {
        bm = br.exec(body);
        if (bm === null) {
          break;
        }
        bullets.push((bm[1] ?? '').trim());
      }

      counter++;
      const code = `C-${tier}-${String(counter).padStart(3, '0')}`;

      // Check if already generated
      const fileName = title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .slice(0, 60)
        .replace(/-$/, '');

      const filePath = resolve(cwd, 'docs', 'contracts', `${code}-${fileName}.md`);
      const alreadyGenerated = existsSync(filePath);

      items.push({
        featureCode: code,
        title,
        tier,
        bulletCount: bullets.length,
        bullets,
        alreadyGenerated,
      });
    }
  }

  return items;
};

// ── Extension registration ─────────────────────────────────

export default function (pi: ExtensionAPI) {
  // ─────────────────────────────────────────────────────────┐
  // Tool 1: contract_scan_backlog                           │
  // ─────────────────────────────────────────────────────────┘

  pi.registerTool({
    name: 'contract_scan_backlog',
    label: 'Contract: Scan Backlog',
    description:
      'Scan TODO.md and list all pending backlog items that can be converted into contracts. ' +
      'Shows feature codes, titles, tiers, and whether a contract file already exists.',
    promptSnippet: 'Use contract_scan_backlog to see what TODO items need contracts.',
    promptGuidelines: [
      'Use this to discover pending items before generating contracts.',
      'Items marked "already generated" have existing contract files.',
      'Use the feature code from this output with contract_generate.',
    ],
    parameters: Type.Object({}),
    async execute(_toolCallId, _params, _signal, _onUpdate, ctx) {
      const items = _parseTodo(ctx.cwd);

      if (items.length === 0) {
        return {
          content: [
            {
              type: 'text',
              text: 'No TODO.md found or no pending backlog items detected.',
            },
          ],
          details: {},
        };
      }

      const pending = items.filter((i) => !i.alreadyGenerated);
      const existing = items.filter((i) => i.alreadyGenerated);

      const lines = ['**TODO.md Backlog Scan**\n'];

      if (pending.length > 0) {
        lines.push(`### Pending (${pending.length})\n`);
        for (const item of pending) {
          lines.push(
            `🔴 \`${item.featureCode}\` — **${item.title}** (${item.tier}, ${item.bulletCount} bullets)`,
          );
        }
      }

      if (existing.length > 0) {
        lines.push(`\n### Already Generated (${existing.length})\n`);
        for (const item of existing) {
          lines.push(`✅ \`${item.featureCode}\` — ${item.title}`);
        }
      }

      lines.push(`\nGenerate a contract: \`contract_generate\` with the feature code.`);

      return {
        content: [{ type: 'text', text: lines.join('\n') }],
        details: { pendingCount: pending.length, existingCount: existing.length },
      };
    },
  });

  // ─────────────────────────────────────────────────────────┐
  // Tool 2: contract_generate                               │
  // ─────────────────────────────────────────────────────────┘

  pi.registerTool({
    name: 'contract_generate',
    label: 'Contract: Generate from Backlog',
    description:
      'Generate a fully formatted engineering contract from a TODO.md backlog item. ' +
      'Writes the contract to docs/contracts/ following TEMPLATE.md structure. ' +
      'Use contract_scan_backlog first to see available feature codes.',
    promptSnippet: 'Use contract_generate to create a contract from a TODO.md item.',
    promptGuidelines: [
      'Run contract_scan_backlog first to find the feature code.',
      'If the contract already exists, it will NOT be overwritten.',
      'Generated contracts include inferred dependencies and test hooks.',
    ],
    parameters: Type.Object({
      featureCode: Type.String({
        description:
          'Feature code from TODO.md scan (e.g., C-P1-001). Use contract_scan_backlog to discover available codes.',
      }),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      const items = _parseTodo(ctx.cwd);
      const item = items.find((i) => i.featureCode === params.featureCode);

      if (!item) {
        return {
          content: [
            {
              type: 'text',
              text: `Feature code "${params.featureCode}" not found in TODO.md.\nRun \`contract_scan_backlog\` to see available items.`,
            },
          ],
          isError: true,
          details: {},
        };
      }

      if (item.alreadyGenerated) {
        const filePath = resolve(
          ctx.cwd,
          'docs',
          'contracts',
          `${item.featureCode}-${item.title
            .toLowerCase()
            .replace(/[^a-z0-9\s-]/g, '')
            .replace(/\s+/g, '-')
            .slice(0, 60)
            .replace(/-$/, '')}.md`,
        );

        return {
          content: [
            {
              type: 'text',
              text: `⚠️ Contract for \`${item.featureCode}\` already exists.\nFile: ${filePath}\n\nDelete it first if you want to regenerate.`,
            },
          ],
          details: { alreadyExists: true, filePath },
        };
      }

      // Build contract content
      const deps = _inferDeps(item.bullets.join(' ') + item.title);
      const overview = (item.bullets.length > 0 ? item.bullets[0] : item.title) ?? item.title;

      const filled = CONTRACT_TEMPLATE.replace(/\{FEATURE_CODE\}/g, item.featureCode)
        .replace(/\{TITLE\}/g, item.title)
        .replace(/\{TIER\}/g, item.tier)
        .replace(/\{DEPS\}/g, deps)
        .replace(/\{OVERVIEW\}/g, overview);

      // Build file name
      const fileNameKey = item.title
        .toLowerCase()
        .replace(/[^a-z0-9\s-]/g, '')
        .replace(/\s+/g, '-')
        .slice(0, 60)
        .replace(/-$/, '');

      const fileName = `${item.featureCode}-${fileNameKey}.md`;
      const contractsDir = resolve(ctx.cwd, 'docs', 'contracts');

      // Ensure directory exists
      if (!existsSync(contractsDir)) {
        mkdirSync(contractsDir, { recursive: true });
      }

      const filePath = resolve(contractsDir, fileName);
      writeFileSync(filePath, filled);

      return {
        content: [
          {
            type: 'text',
            text: [
              `✅ Contract generated: \`${item.featureCode}\``,
              `**${item.title}**`,
              `File: \`docs/contracts/${fileName}\``,
              `Tier: ${item.tier} | Bullets: ${item.bulletCount} | Dependencies: ${deps}`,
              '',
              `Next: Review the generated contract, fill in missing sections, then implement with the contract-implementer skill.`,
            ].join('\n'),
          },
        ],
        details: {
          featureCode: item.featureCode,
          fileName,
          tier: item.tier,
          deps,
        },
      };
    },
  });
}
