// packages/frontend/storage/src/lib/assets_generated.ts
//
// C-510: the `local-generated` registry write seam.
//
// Writes an `assets` row owned by `generated` plus a `local-generated`
// `asset_sources` row at `priority = -1`, so the local copy always outranks a
// seed `r2` row for the same tag (`listSources` orders by
// `priority ASC, backend ASC` — relying on the alphabetical tiebreak would be
// accidental).
//
// Extracted from `assets.ts` so the seeding/derivation repository stays under
// the source-size limit and this ordering-sensitive path is readable on its
// own. No SQL migration is needed: `asset_sources.backend` is a free-text
// `TEXT NOT NULL` with no CHECK constraint.
//
// Contract: C-510 AC-4 / AC-8

import {
  GENERATED_ASSET_PACK_ID,
  LOCAL_GENERATED_SOURCE_BACKEND,
  localGeneratedSourceUrl,
} from '@aikami/constants';
import { logger } from '$logger';
import type { LocalDatabaseInterface } from './storage_adapter.ts';

/** Per-connection, per-tag tails keep the read/calculate/upsert sequence atomic. */
const REGISTRATION_QUEUES = new WeakMap<LocalDatabaseInterface, Map<string, Promise<void>>>();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Input for the generated-asset write.
 *
 * Deliberately a structural subset of `GeneratedAsset` — the registry is
 * metadata-only and knows nothing about bytes, so it takes exactly the fields
 * it persists.
 */
export type GeneratedAssetRegistration = {
  /** Registry tag — must satisfy `AssetRefSchema.tag`. */
  tag: string;
  /** Lowercase hex SHA-256 of the bytes. */
  hash: string;
  sizeBytes: number;
  category: string;
  /** `generated:<engine>` — recorded in `assets.attribution`. */
  provenanceSource: string;
};

/** Result of a {@link registerGeneratedAssetRow} call. */
export type GeneratedAssetRegistrationResult = {
  /** Row version after the write (bumped on a content change). */
  version: number;
  /** True when the tag had no registry row before. */
  created: boolean;
  /** True when identical bytes for this tag were already registered. */
  unchanged: boolean;
};

/**
 * Thrown when a generated tag collides with a tag owned by the boot seed.
 *
 * `_seedCompactChunk` upserts with `ON CONFLICT(id) DO UPDATE SET hash =
 * excluded.hash, version = excluded.version`, so a generated row filed under a
 * seed tag would be silently re-pointed at the remote bytes (and version-
 * bumped) on the next boot. Refusing up front is the only non-destructive
 * option.
 */
export class GeneratedTagCollisionError extends Error {
  /** The conflicting tag. */
  readonly tag: string;
  /** The hash the seed row currently carries. */
  readonly seedHash: string;

  constructor(options: { tag: string; seedHash: string }) {
    super(
      `Cannot register the generated asset "${options.tag}": a catalog (seed) asset already owns that tag (hash ${options.seedHash}). Regenerate under a distinct tag.`,
    );
    this.name = 'GeneratedTagCollisionError';
    this.tag = options.tag;
    this.seedHash = options.seedHash;
  }
}

// ---------------------------------------------------------------------------
// Write seam
// ---------------------------------------------------------------------------

/**
 * Registers locally generated bytes as a first-class registry asset.
 *
 * Idempotent by `tag` + `hash`: re-registering identical bytes leaves the
 * version untouched. Registering *different* bytes for the same tag bumps the
 * version rather than silently re-pointing existing references.
 *
 * @param db — The shared local database connection.
 * @param asset — The descriptor fields the registry persists.
 * @throws {@link GeneratedTagCollisionError} when the tag is owned by the
 *         boot seed (a catalog asset), not by a previous generated write.
 */
export const registerGeneratedAssetRow = async (
  db: LocalDatabaseInterface,
  asset: GeneratedAssetRegistration,
): Promise<GeneratedAssetRegistrationResult> =>
  _serializeRegistration({
    db,
    tag: asset.tag,
    operation: () => _registerGeneratedAssetRow({ db, asset }),
  });

/** Runs the complete generated-row registration while its tag lock is held. */
const _registerGeneratedAssetRow = async (options: {
  db: LocalDatabaseInterface;
  asset: GeneratedAssetRegistration;
}): Promise<GeneratedAssetRegistrationResult> => {
  const { db, asset } = options;
  const existingResult = await db.query({
    sql: 'SELECT id, pack_id, hash, version FROM assets WHERE id = ?',
    args: [asset.tag],
  });
  const existing = existingResult.rows[0];

  if (existing && (existing.pack_id as string) !== GENERATED_ASSET_PACK_ID) {
    throw new GeneratedTagCollisionError({
      tag: asset.tag,
      seedHash: existing.hash as string,
    });
  }

  const unchanged = existing !== undefined && (existing.hash as string) === asset.hash;
  let version = 1;
  if (existing) {
    const existingVersion = existing.version as number;
    version = unchanged ? existingVersion : existingVersion + 1;
  }

  const queries: { sql: string; args: readonly unknown[] }[] = [];

  if (!unchanged) {
    queries.push({
      sql: `INSERT INTO assets (id, pack_id, category, hash, version, size_bytes, license, attribution, tags_json)
            VALUES (?, ?, ?, ?, ?, ?, 'unknown', ?, '[]')
            ON CONFLICT(id) DO UPDATE SET
              pack_id = excluded.pack_id,
              category = excluded.category,
              hash = excluded.hash,
              version = excluded.version,
              size_bytes = excluded.size_bytes,
              attribution = excluded.attribution`,
      args: [
        asset.tag,
        GENERATED_ASSET_PACK_ID,
        asset.category,
        asset.hash,
        version,
        asset.sizeBytes,
        asset.provenanceSource,
      ],
    });
  }

  // Always (re)assert the source row — a half-written previous attempt may
  // have left the asset row without its source, and INSERT OR REPLACE is
  // cheap. The URL is a stable cache key, never a blob: URL.
  queries.push({
    sql: `INSERT OR REPLACE INTO asset_sources (asset_id, backend, url, priority)
          VALUES (?, ?, ?, -1)`,
    args: [asset.tag, LOCAL_GENERATED_SOURCE_BACKEND, localGeneratedSourceUrl(asset.hash)],
  });

  await db.transaction(queries);

  logger.debug('AssetRegistryRepository.registerGenerated', {
    tag: asset.tag,
    hash: asset.hash,
    sizeBytes: asset.sizeBytes,
    version,
    created: existing === undefined,
    unchanged,
  });

  return { version, created: existing === undefined, unchanged };
};

/** Serializes registrations for one tag without blocking unrelated tags. */
const _serializeRegistration = async <T>(options: {
  db: LocalDatabaseInterface;
  tag: string;
  operation: () => Promise<T>;
}): Promise<T> => {
  let queues = REGISTRATION_QUEUES.get(options.db);
  if (!queues) {
    queues = new Map<string, Promise<void>>();
    REGISTRATION_QUEUES.set(options.db, queues);
  }

  const previous = queues.get(options.tag) ?? Promise.resolve();
  const result = previous.then(options.operation, options.operation);
  const tail = result.then(
    () => undefined,
    () => undefined,
  );
  queues.set(options.tag, tail);

  try {
    return await result;
  } finally {
    if (queues.get(options.tag) === tail) {
      queues.delete(options.tag);
    }
  }
};

/**
 * Whether a tag is owned by the boot seed (i.e. a catalog asset, not a locally
 * generated one). The write seam's pre-flight guard.
 */
export const isSeedTagRow = async (db: LocalDatabaseInterface, tag: string): Promise<boolean> => {
  const result = await db.query({
    sql: 'SELECT pack_id FROM assets WHERE id = ?',
    args: [tag],
  });
  const row = result.rows[0];
  return row !== undefined && (row.pack_id as string) !== GENERATED_ASSET_PACK_ID;
};
