// packages/frontend/storage/src/lib/assets_generated.ts
//
// C-510: the `local-generated` registry write seam.
//
// Writes an `assets` row owned by `generated` plus a `local-generated`
// `asset_sources` row at `priority = -1`, so the local copy always outranks a
// seed `r2` row for the same tag (`listSources` orders by
// `priority ASC, backend ASC` — relying on the alphabetical tiebreak would be
// accidental).
//
// Extracted from `assets.ts` so the seeding/derivation repository stays under
// the source-size limit and this ordering-sensitive path is readable on its
// own. No SQL migration is needed: `asset_sources.backend` is a free-text
// `TEXT NOT NULL` with no CHECK constraint.
//
// Contract: C-510 AC-4 / AC-8

import {
  GENERATED_ASSET_PACK_ID,
  LOCAL_GENERATED_SOURCE_BACKEND,
  localGeneratedSourceUrl,
} from '@aikami/constants';
import { logger } from '$logger';
import type { LocalDatabaseInterface, SqlQuery } from './storage_adapter.ts';

/** Per-connection, per-tag tails keep the read/calculate/upsert sequence atomic. */
const REGISTRATION_QUEUES = new WeakMap<LocalDatabaseInterface, Map<string, Promise<void>>>();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Input for the generated-asset write.
 *
 * Deliberately a structural subset of `GeneratedAsset` — the registry is
 * metadata-only and knows nothing about bytes, so it takes exactly the fields
 * it persists.
 */
export type GeneratedAssetRegistration = {
  /** Registry tag — must satisfy `AssetRefSchema.tag`. */
  tag: string;
  /** Lowercase hex SHA-256 of the bytes. */
  hash: string;
  sizeBytes: number;
  category: string;
  /** `generated:<engine>` — recorded in `assets.attribution`. */
  provenanceSource: string;
};

/** Result of a {@link registerGeneratedAssetRow} call. */
export type GeneratedAssetRegistrationResult = {
  /** Row version after the write (bumped on a content change). */
  version: number;
  /** True when the tag had no registry row before. */
  created: boolean;
  /** True when identical bytes for this tag were already registered. */
  unchanged: boolean;
};

/**
 * Thrown when a generated tag collides with a tag owned by the boot seed.
 *
 * `_seedCompactChunk` upserts with `ON CONFLICT(id) DO UPDATE SET hash =
 * excluded.hash, version = excluded.version`, so a generated row filed under a
 * seed tag would be silently re-pointed at the remote bytes (and version-
 * bumped) on the next boot. Refusing up front is the only non-destructive
 * option.
 */
export class GeneratedTagCollisionError extends Error {
  /** The conflicting tag. */
  readonly tag: string;
  /** The hash the seed row currently carries. */
  readonly seedHash: string;

  constructor(options: { tag: string; seedHash: string }) {
    super(
      `Cannot register the generated asset "${options.tag}": a catalog (seed) asset already owns that tag (hash ${options.seedHash}). Regenerate under a distinct tag.`,
    );
    this.name = 'GeneratedTagCollisionError';
    this.tag = options.tag;
    this.seedHash = options.seedHash;
  }
}

// ---------------------------------------------------------------------------
// Write seam
// ---------------------------------------------------------------------------

/**
 * Registers locally generated bytes as a first-class registry asset.
 *
 * Idempotent by `tag` + `hash`: re-registering identical bytes leaves the
 * version untouched. Registering *different* bytes for the same tag bumps the
 * version rather than silently re-pointing existing references.
 *
 * @param db — The shared local database connection.
 * @param asset — The descriptor fields the registry persists.
 * @throws {@link GeneratedTagCollisionError} when the tag is owned by the
 *         boot seed (a catalog asset), not by a previous generated write.
 */
export const registerGeneratedAssetRow = async (
  db: LocalDatabaseInterface,
  asset: GeneratedAssetRegistration,
): Promise<GeneratedAssetRegistrationResult> =>
  _serializeRegistration({
    db,
    tag: asset.tag,
    operation: () => _registerGeneratedAssetRow({ db, asset }),
  });

/**
 * Commits associated authoring rows and the generated registry row together.
 *
 * The callback runs while the per-tag registration lock is held, after registry
 * collision/version reads and immediately before the single transaction.
 */
export const registerGeneratedAssetRowWithAssociatedWrites = async (options: {
  db: LocalDatabaseInterface;
  asset: GeneratedAssetRegistration;
  prepareAssociatedQueries(): Promise<readonly SqlQuery[]>;
}): Promise<GeneratedAssetRegistrationResult> =>
  _serializeRegistration({
    db: options.db,
    tag: options.asset.tag,
    operation: () =>
      _registerGeneratedAssetRow({
        db: options.db,
        asset: options.asset,
        prepareAssociatedQueries: options.prepareAssociatedQueries,
      }),
  });

/** Runs the complete generated-row registration while its tag lock is held. */
const _registerGeneratedAssetRow = async (options: {
  db: LocalDatabaseInterface;
  asset: GeneratedAssetRegistration;
  prepareAssociatedQueries?: () => Promise<readonly SqlQuery[]>;
}): Promise<GeneratedAssetRegistrationResult> => {
  const { db, asset } = options;
  const existingResult = await db.query({
    sql: 'SELECT id, pack_id, hash, version FROM assets WHERE id = ?',
    args: [asset.tag],
  });
  const existing = existingResult.rows[0];

  if (existing && (existing.pack_id as string) !== GENERATED_ASSET_PACK_ID) {
    throw new GeneratedTagCollisionError({
      tag: asset.tag,
      seedHash: existing.hash as string,
    });
  }

  const unchanged = existing !== undefined && (existing.hash as string) === asset.hash;
  let version = 1;
  if (existing) {
    const existingVersion = existing.version as number;
    version = unchanged ? existingVersion : existingVersion + 1;
  }

  const queries: { sql: string; args: readonly unknown[] }[] = [];

  if (!unchanged) {
    queries.push({
      sql: `INSERT INTO assets (id, pack_id, category, hash, version, size_bytes, license, attribution, tags_json)
            VALUES (?, ?, ?, ?, ?, ?, 'unknown', ?, '[]')
            ON CONFLICT(id) DO UPDATE SET
              pack_id = excluded.pack_id,
              category = excluded.category,
              hash = excluded.hash,
              version = excluded.version,
              size_bytes = excluded.size_bytes,
              attribution = excluded.attribution`,
      args: [
        asset.tag,
        GENERATED_ASSET_PACK_ID,
        asset.category,
        asset.hash,
        version,
        asset.sizeBytes,
        asset.provenanceSource,
      ],
    });
  }

  // Always (re)assert the source row — a half-written previous attempt may
  // have left the asset row without its source, and INSERT OR REPLACE is
  // cheap. The URL is a stable cache key, never a blob: URL.
  queries.push({
    sql: `INSERT OR REPLACE INTO asset_sources (asset_id, backend, url, priority)
          VALUES (?, ?, ?, -1)`,
    args: [asset.tag, LOCAL_GENERATED_SOURCE_BACKEND, localGeneratedSourceUrl(asset.hash)],
  });

  const associatedQueries = await options.prepareAssociatedQueries?.();
  await db.transaction([...(associatedQueries ?? []), ...queries]);
  // A user-initiated save must survive an immediate reload — the snapshot
  // adapter's debounce is not durable enough on its own.
  await db.flush?.();

  logger.debug('AssetRegistryRepository.registerGenerated', {
    tag: asset.tag,
    hash: asset.hash,
    sizeBytes: asset.sizeBytes,
    version,
    created: existing === undefined,
    unchanged,
  });

  return { version, created: existing === undefined, unchanged };
};

/** Serializes registrations for one tag without blocking unrelated tags. */
const _serializeRegistration = async <T>(options: {
  db: LocalDatabaseInterface;
  tag: string;
  operation: () => Promise<T>;
}): Promise<T> => {
  let queues = REGISTRATION_QUEUES.get(options.db);
  if (!queues) {
    queues = new Map<string, Promise<void>>();
    REGISTRATION_QUEUES.set(options.db, queues);
  }

  const previous = queues.get(options.tag) ?? Promise.resolve();
  const result = previous.then(options.operation, options.operation);
  const tail = result.then(
    () => undefined,
    () => undefined,
  );
  queues.set(options.tag, tail);

  try {
    return await result;
  } finally {
    if (queues.get(options.tag) === tail) {
      queues.delete(options.tag);
    }
  }
};

export type GeneratedAssetRow = {
  /** Registry tag (`assets.id`). */
  tag: string;
  category: string;
  /** Lowercase hex SHA-256. */
  sha256: string;
  sizeBytes: number;
  /** `assets.attribution` — `generated:<engine>` for C-510 rows. */
  provenanceSource: string;
  /** `install_state.downloaded_at`; the registry has no `created_at` column. */
  createdAt: string | undefined;
  /** True when a `local-generated` source row exists (generated on this device). */
  localGenerated: boolean;
};

/** Outcome of {@link deleteGeneratedAssetRow}. */
export type DeleteGeneratedAssetResult = {
  deleted: boolean;
  /** The content hash the row pointed at, when a row was deleted. */
  hash?: string;
  /** Why nothing was deleted (`not_found` | `seed_tag`). */
  reason?: string;
};

/** Registry tag grammar (`AssetRefSchema.tag`). */
const TAG_PATTERN = /^[a-z0-9]+(:[a-z0-9_.-]+)+$/;

/**
 * Lists every row in the `generated` pack — the studio library's query.
 *
 * Pack-scoped on purpose (C-512 performance budget): the library must never
 * trigger a full registry scan per save.
 */
export const listGeneratedAssetRows = async (
  db: LocalDatabaseInterface,
): Promise<GeneratedAssetRow[]> => {
  const result = await db.query({
    sql: `SELECT a.id AS tag, a.category, a.hash, a.size_bytes, a.attribution, s.downloaded_at,
                 EXISTS (
                   SELECT 1 FROM asset_sources src
                   WHERE src.asset_id = a.id AND src.backend = ?
                 ) AS local_generated
          FROM assets a
          LEFT JOIN install_state s ON s.asset_id = a.id
          WHERE a.pack_id = ?
          ORDER BY COALESCE(s.downloaded_at, '') DESC, a.id ASC`,
    args: [LOCAL_GENERATED_SOURCE_BACKEND, GENERATED_ASSET_PACK_ID],
  });

  return result.rows.map((row) => ({
    tag: row.tag as string,
    category: row.category as string,
    sha256: row.hash as string,
    sizeBytes: row.size_bytes as number,
    provenanceSource: (row.attribution as string | null) ?? '',
    createdAt: (row.downloaded_at as string | null) ?? undefined,
    localGenerated: Number(row.local_generated ?? 0) > 0,
  }));
};

/**
 * Renames a locally generated row and its dependent source/install rows.
 *
 * Only `generated`-pack rows are touchable: a catalog (seed) row is refused,
 * because `_seedCompactChunk` would re-point it at the remote bytes on the
 * next boot and silently discard the rename.
 *
 * @throws Error when the source tag has no row, is seed-owned, or the target
 *         tag already exists (rename is not an overwrite).
 */
export const renameGeneratedAssetRow = async (
  db: LocalDatabaseInterface,
  options: { from: string; to: string },
): Promise<GeneratedAssetRow> => {
  const { from, to } = options;
  if (!TAG_PATTERN.test(to)) {
    throw new Error(`Cannot rename to "${to}" — it does not match the registry tag grammar`);
  }
  if (from === to) {
    throw new Error('Cannot rename an asset to itself');
  }

  const existing = await db.query({
    sql: 'SELECT id, pack_id FROM assets WHERE id IN (?, ?)',
    args: [from, to],
  });
  const source = existing.rows.find((row) => (row.id as string) === from);
  const target = existing.rows.find((row) => (row.id as string) === to);

  if (!source) {
    throw new Error(`Cannot rename "${from}" — no registry row with that tag`);
  }
  if ((source.pack_id as string) !== GENERATED_ASSET_PACK_ID) {
    throw new Error(
      `Cannot rename "${from}" — it belongs to the catalog (pack "${source.pack_id as string}"), not to local generation`,
    );
  }
  if (target) {
    throw new Error(`Cannot rename "${from}" to "${to}" — that tag already exists`);
  }

  await db.transaction([
    // `asset_sources`/`install_state` declare `REFERENCES assets(id)` with no
    // ON UPDATE CASCADE, so the new parent row must exist before its children
    // move and the old parent is removed last.
    {
      sql: `INSERT INTO assets (id, pack_id, category, hash, version, size_bytes, width, height, license, attribution, tags_json)
            SELECT ?, pack_id, category, hash, version, size_bytes, width, height, license, attribution, tags_json
            FROM assets WHERE id = ?`,
      args: [to, from],
    },
    { sql: 'UPDATE asset_sources SET asset_id = ? WHERE asset_id = ?', args: [to, from] },
    { sql: 'UPDATE install_state SET asset_id = ? WHERE asset_id = ?', args: [to, from] },
    {
      sql: 'DELETE FROM assets WHERE id = ? AND pack_id = ?',
      args: [from, GENERATED_ASSET_PACK_ID],
    },
  ]);
  await db.flush?.();

  logger.debug('AssetRegistryRepository.renameGenerated', { from, to });

  const renamed = await listGeneratedAssetRows(db);
  const entry = renamed.find((row) => row.tag === to);
  if (!entry) {
    throw new Error(`Rename of "${from}" to "${to}" did not produce a readable row`);
  }
  return entry;
};

/**
 * Deletes a locally generated row and its dependent source/install rows.
 *
 * Refuses seed tags outright ({@link isSeedTagRow}). Cache bytes are the
 * caller's to remove — the registry is metadata-only.
 */
export const deleteGeneratedAssetRow = async (
  db: LocalDatabaseInterface,
  tag: string,
): Promise<DeleteGeneratedAssetResult> => {
  const result = await db.query({
    sql: 'SELECT id, pack_id, hash FROM assets WHERE id = ?',
    args: [tag],
  });
  const row = result.rows[0];
  if (!row) {
    return { deleted: false, reason: 'not_found' };
  }
  if ((row.pack_id as string) !== GENERATED_ASSET_PACK_ID) {
    return { deleted: false, reason: 'seed_tag' };
  }

  await db.transaction([
    { sql: 'DELETE FROM install_state WHERE asset_id = ?', args: [tag] },
    { sql: 'DELETE FROM asset_sources WHERE asset_id = ?', args: [tag] },
    {
      sql: 'DELETE FROM assets WHERE id = ? AND pack_id = ?',
      args: [tag, GENERATED_ASSET_PACK_ID],
    },
  ]);
  await db.flush?.();

  logger.debug('AssetRegistryRepository.deleteGenerated', { tag, hash: row.hash });
  return { deleted: true, hash: row.hash as string };
};

/**
 * Save ids whose payload mentions `tag`.
 *
 * There is no reference index today, so this is a substring scan over the
 * active save payloads — it can produce false positives (a tag appearing in
 * prose) and cannot see references held outside `saves.payload`. It is a
 * best-effort guard against deleting a tag a save depends on, not a proof of
 * unreferencedness; the studio surfaces a hit as a confirmation step.
 */
export const findSaveReferences = async (
  db: LocalDatabaseInterface,
  tag: string,
): Promise<string[]> => {
  const escapedTag = tag.replaceAll('!', '!!').replaceAll('%', '!%').replaceAll('_', '!_');
  const result = await db.query({
    sql: "SELECT id FROM saves WHERE payload LIKE '%' || ? || '%' ESCAPE '!' LIMIT 20",
    args: [escapedTag],
  });
  return result.rows.map((row) => row.id as string);
};

/**
 * Whether a tag is owned by the boot seed (i.e. a catalog asset, not a locally
 * generated one). The write seam's pre-flight guard.
 */
export const isSeedTagRow = async (db: LocalDatabaseInterface, tag: string): Promise<boolean> => {
  const result = await db.query({
    sql: 'SELECT pack_id FROM assets WHERE id = ?',
    args: [tag],
  });
  const row = result.rows[0];
  return row !== undefined && (row.pack_id as string) !== GENERATED_ASSET_PACK_ID;
};
