// apps/e2e/playwright.config.ts
// Unified Playwright configuration for PWA + Game + AI Services E2E tests.
// Uses Node.js runtime (NOT Bun) to avoid CDP websocket hanging issues.
//
// C-054: Adds setup project for auth state caching (AC-1), custom fixtures,
// and emulator lifecycle hooks.
//
// Port numbers are hardcoded here (not imported from @aikami/constants)
// because the config is loaded by Node.js directly as ESM, and the
// monorepo packages are CJS modules incompatible with ESM imports.

import type { PlaywrightTestConfig } from '@playwright/test';
import { defineConfig, devices } from '@playwright/test';

// ── Emulator Ports (must match development_ports.ts) ─────────

const AUTH_PORT = 9098;
const FIRESTORE_PORT = 8081;
const STORAGE_PORT = 9198;
const PUBSUB_PORT = 8086;
const PWA_PORT = 5274;
const GAME_PORT = 5276;
const PROJECT_ID = 'demo-aikami-emulator';

// ── Environment binding for Firebase Admin SDK ─────────────────

// Protocol-free host strings (no http:// prefix — Firebase Admin SDK requires this)
process.env.FIRESTORE_EMULATOR_HOST = `127.0.0.1:${FIRESTORE_PORT}`;
process.env.FIREBASE_AUTH_EMULATOR_HOST = `127.0.0.1:${AUTH_PORT}`;
process.env.FIREBASE_STORAGE_EMULATOR_HOST = `127.0.0.1:${STORAGE_PORT}`;
process.env.PUBSUB_EMULATOR_HOST = `127.0.0.1:${PUBSUB_PORT}`;
process.env.GCLOUD_PROJECT = PROJECT_ID;

// ── Dev server base URLs ──────────────────────────────────────

const PWA_BASE_URL = `http://localhost:${PWA_PORT}`;
const GAME_BASE_URL = `http://localhost:${GAME_PORT}`;

// Auth state cache file generated by the setup project
const AUTH_STATE_FILE = './.auth/user.json';

// ── Global lifecycle hooks ────────────────────────────────────

const GLOBAL_SETUP = './src/global_setup.ts';
const GLOBAL_TEARDOWN = './src/global_teardown.ts';

// ── Core configuration ────────────────────────────────────────

export default defineConfig({
  // Global setup/teardown for database purging (C-054 AC-3)
  globalSetup: GLOBAL_SETUP,
  globalTeardown: GLOBAL_TEARDOWN,

  // Test directory: app-specific test files live in tests/{client,game,ai-services}/
  testDir: './tests',

  // Run all projects in parallel
  fullyParallel: true,

  // Fail CI on test.only()
  forbidOnly: !!process.env.CI,

  // Retry on CI (flake guard), no retries locally
  retries: process.env.CI ? 2 : 0,

  // Single worker in CI (deterministic), auto locally
  workers: process.env.CI ? 1 : undefined,

  // Reporter: list locally, github in CI
  reporter: process.env.CI ? [['github']] : [['list']],

  // Shared settings for all projects
  use: {
    // Default base URL — overridden per-project
    baseURL: PWA_BASE_URL,

    // Capture trace on first retry
    trace: 'on-first-retry',

    // Screenshots only on failure
    screenshot: 'only-on-failure',

    // Video retained on failure for CI debugging
    video: 'retain-on-failure',
  },

  // Timeout per test
  timeout: 60_000,

  // Expect timeout
  expect: {
    timeout: 15_000,
  },

  // ── Operational domain projects ────────────────────────────

  projects: [
    // ── Setup (Auth State Caching) ──────────────────────────
    {
      name: 'setup',
      testDir: './src',
      testMatch: /auth\.setup\.ts/,
    },

    // ── Client Domain ──────────────────────────────────────
    {
      name: 'client',
      testDir: './tests/client',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: PWA_BASE_URL,
        // Load pre-authenticated session state for protected-route tests.
        // Tests that need unauthenticated access should use the guestUser fixture,
        // which creates its own isolated context without storageState.
        storageState: AUTH_STATE_FILE,
      },
      dependencies: ['setup'],
    },

    // ── PWA Visual (no auth, no setup dep) ────────────────
    // Isolated from setup so visual smoke tests can run without
    // Firebase emulators. Uses guestUser fixture for clean contexts.
    {
      name: 'client-visual',
      testDir: './tests/client',
      testMatch: /(?:lpc|sandbox)_visual\.spec\.ts/,
      use: {
        ...devices['Desktop Chrome'],
        baseURL: PWA_BASE_URL,
        // WebGL rendering in headless Chromium.
        // The Nix bundle ships libvk_swiftshader.so — use Vulkan SwiftShader.
        launchOptions: {
          args: [
            '--use-gl=angle',
            '--use-angle=swiftshader',
            '--enable-webgl',
            '--ignore-gpu-blocklist',
            '--enable-features=Vulkan,UseSkiaRenderer',
          ],
        },
      },
    },

    // ── Game Domain ────────────────────────────────────────
    {
      name: 'game',
      testDir: './tests/game',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: GAME_BASE_URL,
      },
      // Game tests don't need authentication — no setup dependency.
    },

    // ── AI Services Domain (future) ────────────────────────
    {
      name: 'ai-services',
      testDir: './tests/ai-services',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
} satisfies PlaywrightTestConfig);
