// apps/frontend/client/src/lib/services/assets/asset_manager.svelte.ts
//
// C-373: AssetManager — hybrid asset resolution: registry → cache → sources.
//
// Resolves asset tags through the Turso-backed registry, serves verified
// binaries from the content-hash-keyed cache backend (OPFS on Web,
// Tauri FS on Desktop), fetches + SHA-256-verifies on miss, tracks
// per-asset install state, evicts stale binaries when the registry hash
// advances, and hands callers refcounted blob: object URLs (revoked after
// decode via releaseUrl). Raw binaries never touch SQLite rows.
//
// The wrapped resolvers (asset_store.resolveUrl + LPC resolver wiring)
// call acquireUrl() synchronously (refcounted) and warm() in the
// background, so cached assets resolve with zero network traffic and
// uncached assets degrade to the C-372 static-URL fallback.

import {
  BaseFrontendClass,
  type BaseFrontendClassInterface,
  type BaseFrontendClassOptions,
} from '@aikami/frontend/services/base';
import type { AssetRegistryRepository } from '@aikami/frontend/storage';
import type { CommunityAssetSummary, GeneratedAsset, LibraryEntry } from '@aikami/types';
import type {
  CommunityImportOutcome,
  CommunityLibraryEntry,
  CommunityPublishOutcome,
  CommunityPublishRequest,
  GeneratedAssetDeleteOutcome,
  GeneratedAssetLineage,
} from '$types';
import { evictLruCachedAsset, isQuotaExceededError } from './asset_cache_eviction.ts';
import { sha256Hex } from './asset_hasher.ts';
import { rehydrateCachedAssets } from './asset_rehydration.ts';
import { BlobUrlRegistry } from './blob_url_registry.ts';
import {
  exportRegisteredBytes,
  importCommunityAssetIntoRegistry,
  listApprovedCommunityAssets,
  listImportedCommunityAssets,
  listLocalTagsByCategory,
  publishRegisteredBytes,
} from './community_asset_operations.ts';
import {
  type RegisterGeneratedResult,
  registerGeneratedAsset,
} from './generated_asset_registration.ts';
import {
  deleteGeneratedLibraryEntry,
  listGeneratedLibrary,
  renameGeneratedLibraryEntry,
} from './generated_library.ts';
import './blob_url_loader.ts';
import { withStepTimeout } from '$lib/utils/step_timeout';
import type { AssetCacheBackend } from './cache_backend.ts';
import { OpfsCacheBackend } from './opfs_cache_backend.ts';
import { TauriFSCacheBackend } from './tauri_fs_cache_backend.ts';

// ---------------------------------------------------------------------------
// Re-exports
// ---------------------------------------------------------------------------

/** Result of {@link AssetManagerInterface.registerGenerated} (C-510). */
export type { RegisterGeneratedResult } from './generated_asset_registration.ts';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Options for constructing the {@link AssetManager}. */
export type AssetManagerOptions = BaseFrontendClassOptions;

/** Result of a reconcile pass. */
export type AssetReconcileResult = {
  /** Interrupted downloads reset to 'not_downloaded'. */
  interruptedReset: number;
  /** Stale cache entries evicted (hash mismatch vs registry). */
  staleEvicted: number;
};

/**
 * See {@link AssetManagerInterface}.
 */
export type AssetManagerInterface = BaseFrontendClassInterface & {
  /** Whether the manager has been initialized with registry + backend. */
  readonly isInitialized: boolean;
  /** Binds the registry + cache backend and pre-registers cached binaries. */
  initialize(options: {
    registry: AssetRegistryRepository;
    backend: AssetCacheBackend;
    /** Tags to eagerly materialise; everything else resolves lazily. */
    coreTags?: ReadonlySet<string>;
  }): Promise<void>;
  /** Resolves a tag to a blob: URL, fetching + verifying + caching on miss. */
  resolve(tag: string, options?: { signal?: AbortSignal }): Promise<string | null>;
  /** Synchronous lookup of a cached asset's blob URL (wrapped resolvers). */
  peekBlobUrl(tag: string): string | null;
  /** Refcounted synchronous fast-path for wrapped resolvers. */
  acquireUrl(tag: string): string | null;
  /** Fire-and-forget prefetch — same as resolve, safe to not await. */
  warm(tag: string): Promise<string | null>;
  /**
   * Persists generated bytes as a registry asset (C-510): verified cache
   * write + `assets` row + `local-generated` source at priority -1, so
   * {@link resolve} returns a usable URL with no network. No-op when
   * `PUBLIC_ASSET_GENERATION` is falsy.
   */
  registerGenerated(
    asset: GeneratedAsset,
    bytes: Uint8Array,
    lineage?: GeneratedAssetLineage,
  ): Promise<RegisterGeneratedResult>;
  /** Lists locally generated assets as studio library entries (C-512). */
  listGeneratedAssets(): Promise<LibraryEntry[]>;
  /** Renames a locally generated asset (row + source + install state). */
  renameGeneratedAsset(options: { from: string; to: string }): Promise<LibraryEntry>;
  /** Deletes a locally generated asset and its cached bytes (C-512). */
  deleteGeneratedAsset(options: {
    tag: string;
    force?: boolean;
  }): Promise<GeneratedAssetDeleteOutcome>;
  /**
   * Reads a registry asset's cached bytes (C-513 publish).
   *
   * Returns undefined when the tag is unknown or its bytes are not cached —
   * publishing is an explicit online action and never fetches on this path.
   */
  exportBytes(tag: string): Promise<Uint8Array | undefined>;
  /** Downloads + imports one approved community asset (C-513 AC-4/AC-10/AC-11). */
  importCommunityAsset(
    asset: CommunityAssetSummary,
    options?: { collision?: 'version' },
  ): Promise<CommunityImportOutcome>;
  /**
   * Publishes a local asset's bytes to the community namespace (C-513 AC-1).
   *
   * @param tag - The registry tag whose cached bytes are published.
   * @param request - Metadata + the redacted provenance projection.
   */
  publishCommunityAsset(
    tag: string,
    request: Omit<CommunityPublishRequest, 'tag' | 'category' | 'ext'>,
  ): Promise<CommunityPublishOutcome>;
  /** Lists approved community assets from the hub (C-513 AC-4). */
  listCommunityAssets(options?: {
    category?: CommunityAssetSummary['category'];
    cursor?: string;
  }): Promise<{ items: readonly CommunityAssetSummary[]; nextCursor?: string }>;
  /**
   * Lists the tags this device owns in one manifest category (C-513 AC-10).
   *
   * Covers assets the boot-seed manifest cannot know about — community imports
   * and locally generated audio — so a runtime resolver can serve them from the
   * on-device cache after a reload with no network.
   *
   * @param category - Manifest category, e.g. `music`.
   */
  listLocalTags(category: string): Promise<readonly string[]>;
  /**
   * Lists the community assets this device has already imported (C-513 AC-10).
   *
   * Registry-only: the community surface renders this with no network, so the
   * imported assets stay visible after a reload while the hub is unreachable.
   */
  listImportedAssets(): Promise<readonly CommunityLibraryEntry[]>;
  /** Boot-time reconcile: reset interrupted downloads + evict stale binaries. */
  reconcile(): Promise<AssetReconcileResult>;
  /** Aborts an in-flight download for the given tag. */
  cancelDownload(tag: string): void;
  /** Releases a blob URL reference (refcounted; revoked at zero). */
  release(tag: string): void;
  /** Releases a blob URL by its URL string (post-decode revocation). */
  releaseUrl(url: string): void;
  /** Revokes all blob URLs and resets the manager. */
  teardown(): Promise<void>;
};

/**
 * The AssetManager implementation.
 */
class AssetManager extends BaseFrontendClass<AssetManagerOptions> implements AssetManagerInterface {
  /**
   * Ceiling for a single DB/backend call during initialize(). Well under the
   * caller's own 20s step budget so the inner, more specific name wins.
   */
  private static readonly _stepTimeoutMs = 8_000;

  /**
   * How many rehydration fetches run concurrently during initialize().
   *
   * Each cached asset needs its own backend.get() round trip, and on Tauri
   * desktop that's an IPC call to Rust. A large offline-core catalog
   * (10k+ entries) run one-at-a-time blows the caller's 20s step budget even
   * though each individual call is fast — the IPC round-trip overhead is
   * cumulative, not per-item-slow. Running them in bounded-concurrency
   * batches instead of fully sequential keeps wall time roughly
   * proportional to catalog-size / this value.
   *
   * Measured on a 12,726-row catalog (real Tauri desktop hardware, 2026-08-27):
   * 24 in flight completed in 16.6s — under the 20s budget, but close enough
   * that IPC timing variance seen elsewhere (26ms-120ms for a single
   * listHashes() call across runs) could tip it over. Raised for margin;
   * revisit if this proves too aggressive for the IPC channel.
   */
  private static readonly _rehydrateConcurrency = 64;

  /** Whether initialize() has completed. */
  isInitialized = false;

  /** The registry over the shared local DB. */
  private _registry: AssetRegistryRepository | null = null;

  /** The platform cache backend (OPFS or Tauri FS). */
  private _backend: AssetCacheBackend | null = null;

  /** Owns current and superseded refcounted blob URLs. */
  private readonly _blobUrls = new BlobUrlRegistry();

  /**
   * Verified tag → content-hash mappings recorded during initialize()
   * rehydration. Kept separate from {@link _blobUrls} so rehydration never
   * needs to materialise object URLs eagerly; resolve() materialises lazily
   * on first access for any tag whose backend file was missing at boot.
   */
  private readonly _verifiedHashes = new Map<string, string>();

  /** In-flight resolve promises keyed by tag (dedupe concurrent requests). */
  private readonly _inflight = new Map<string, Promise<string | null>>();

  /** AbortControllers for in-flight downloads keyed by tag. */
  private readonly _abortControllers = new Map<string, AbortController>();

  // ── Lifecycle ────────────────────────────────────────────────────────

  /** @inheritdoc */
  async initialize(options: {
    registry: AssetRegistryRepository;
    backend: AssetCacheBackend;
    /**
     * Tags that must resolve synchronously from the first frame (the
     * offline-core set, ~16 tags — see {@link OFFLINE_CORE_PACK_ID}).
     *
     * Only these get their blob URL eagerly materialised during
     * rehydration below. Every other cached tag — the bulk of a real
     * catalog (10k+ downloaded entries) — is left as a verified hash only
     * and lazily materialised on first actual access via
     * {@link AssetManager._doResolve} step 1b. Eagerly fetching all of them
     * at every boot was one IPC round trip per cached blob with no
     * aggregate cap: harmless at Web-OPFS scale, but a real Tauri desktop
     * catalog (12k+ entries) blew the boot pipeline's 20s budget because
     * the IPC channel has a fixed per-call floor that concurrency cannot
     * shrink (raising in-flight calls from 24 to 64 made no measurable
     * difference — confirmed 2026-08-27, 16.6s either way).
     *
     * Omit to eagerly materialise everything (legacy behaviour) — used by
     * tests that don't wire a real core-tags set.
     */
    coreTags?: ReadonlySet<string>;
  }): Promise<void> {
    // Idempotent across boots — drop any state from a previous session.
    await this.teardown();

    this._registry = options.registry;
    this._backend = options.backend;
    const isCoreTag = (tag: string): boolean => options.coreTags?.has(tag) ?? true;

    // Rehydrate verified cached binaries so offline reloads resolve instantly
    // (synchronous acquireUrl/peekBlobUrl) without touching the network. The
    // two passes, the batching and the per-step timeouts live in
    // `asset_rehydration.ts`.
    try {
      const { cachedRows, registered } = await rehydrateCachedAssets({
        registry: this._registry,
        backend: this._backend,
        isCoreTag,
        verifiedHashes: this._verifiedHashes,
        hasBlobUrl: (tag) => this._blobUrls.has(tag),
        registerBlobUrl: (registeredBlob) => this._registerBlobUrl(registeredBlob),
        stepTimeoutMs: AssetManager._stepTimeoutMs,
        concurrency: AssetManager._rehydrateConcurrency,
      });

      this.isInitialized = true;
      this.debug('asset_manager:initialized', { cachedRows, registered });
    } catch (error) {
      await this.teardown();
      throw error;
    }
  }

  /** @inheritdoc */
  async teardown(): Promise<void> {
    this._blobUrls.clear();
    this._verifiedHashes.clear();
    this._inflight.clear();
    this._abortControllers.clear();
    this._registry = null;
    this._backend = null;
    this.isInitialized = false;
  }

  // ── Resolution ───────────────────────────────────────────────────────

  /** @inheritdoc */
  peekBlobUrl(tag: string): string | null {
    return this._blobUrls.peek(tag);
  }

  /** @inheritdoc */
  acquireUrl(tag: string): string | null {
    return this._blobUrls.acquire(tag);
  }

  /** @inheritdoc */
  warm(tag: string): Promise<string | null> {
    return this.resolve(tag);
  }

  /** @inheritdoc */
  async resolve(tag: string, options?: { signal?: AbortSignal }): Promise<string | null> {
    if (!this.isInitialized) {
      return null;
    }

    // Dedupe concurrent resolves for the same tag.
    const inFlight = this._inflight.get(tag);
    if (inFlight) {
      return inFlight;
    }

    const promise = this._doResolve(tag, options?.signal);
    this._inflight.set(tag, promise);
    try {
      const url = await promise;
      if (url) {
        // Every returned URL holds one reference for THIS caller. The
        // _inflight promise is shared by concurrent resolvers, so each of
        // them must acquire — otherwise a sibling's release() could revoke
        // a URL that is still in use.
        this._blobUrls.retain(url);
      }
      return url;
    } finally {
      this._inflight.delete(tag);
    }
  }

  /** @inheritdoc */
  cancelDownload(tag: string): void {
    const controller = this._abortControllers.get(tag);
    controller?.abort();
  }

  // ── Generated assets (C-510) ─────────────────────────────────────────

  /** @inheritdoc */
  registerGenerated(
    asset: GeneratedAsset,
    bytes: Uint8Array,
    lineage?: GeneratedAssetLineage,
  ): Promise<RegisterGeneratedResult> {
    return registerGeneratedAsset(
      {
        registry: this._registry,
        backend: this._backend,
        onRegistered: async (registered, blob) => {
          this._verifiedHashes.set(registered.tag, registered.sha256);
          this._registerBlobUrl({ tag: registered.tag, hash: registered.sha256, blob });
          await this._registry?.setInstallState({
            assetId: registered.tag,
            status: 'cached',
            cachedHash: registered.sha256,
            localPath: registered.sha256,
            downloadedAt: new Date().toISOString(),
          });
        },
        debug: (message, context) => this.debug(message, context),
        info: (message, context) => this.info(message, context),
      },
      asset,
      bytes,
      lineage,
    );
  }

  // ── Community + local library (C-513) ─────────────────────────────────
  //
  // Thin delegators: the operations themselves live in
  // `community_asset_operations.ts`, which takes the registry + cache
  // explicitly rather than reaching for this instance.

  /** The registry + cache the community operations work against. */
  private _communityContext() {
    return { registry: this._registry, backend: this._backend };
  }

  /** @inheritdoc */
  exportBytes(tag: string): Promise<Uint8Array | undefined> {
    return exportRegisteredBytes(this._communityContext(), tag);
  }

  /** @inheritdoc */
  importCommunityAsset(
    asset: CommunityAssetSummary,
    options: { collision?: 'version' } = {},
  ): Promise<CommunityImportOutcome> {
    return importCommunityAssetIntoRegistry(this._communityContext(), asset, options);
  }

  /** @inheritdoc */
  publishCommunityAsset(
    tag: string,
    request: Omit<CommunityPublishRequest, 'tag' | 'category' | 'ext'>,
  ): Promise<CommunityPublishOutcome> {
    return publishRegisteredBytes(this._communityContext(), tag, request);
  }

  /** @inheritdoc */
  listCommunityAssets(
    options: { category?: CommunityAssetSummary['category']; cursor?: string } = {},
  ): Promise<{ items: readonly CommunityAssetSummary[]; nextCursor?: string }> {
    return listApprovedCommunityAssets(options);
  }

  /** @inheritdoc */
  listLocalTags(category: string): Promise<readonly string[]> {
    return listLocalTagsByCategory(this._communityContext(), category);
  }

  /** @inheritdoc */
  listImportedAssets(): Promise<readonly CommunityLibraryEntry[]> {
    return listImportedCommunityAssets(this._communityContext());
  }

  listGeneratedAssets(): Promise<LibraryEntry[]> {
    return listGeneratedLibrary(this._generatedLibraryDeps());
  }

  /** @inheritdoc */
  renameGeneratedAsset(options: { from: string; to: string }): Promise<LibraryEntry> {
    return renameGeneratedLibraryEntry(this._generatedLibraryDeps(), options);
  }

  /** @inheritdoc */
  deleteGeneratedAsset(options: {
    tag: string;
    force?: boolean;
  }): Promise<GeneratedAssetDeleteOutcome> {
    return deleteGeneratedLibraryEntry(this._generatedLibraryDeps(), options);
  }

  private _generatedLibraryDeps() {
    return {
      registry: this._registry,
      backend: this._backend,
      releaseTagUrl: (tag: string) => this._blobUrls.releaseTag(tag),
    };
  }

  // ── Reconcile (AC-3) ─────────────────────────────────────────────────

  /** @inheritdoc */
  async reconcile(): Promise<AssetReconcileResult> {
    if (!this._registry || !this._backend) {
      return { interruptedReset: 0, staleEvicted: 0 };
    }

    const interruptedReset = await this._registry.resetInterruptedDownloads();

    // Evict binaries whose cached hash no longer matches the registry
    // (a new build bumped the sidecar) — AC-3 stale eviction.
    let staleEvicted = 0;
    const states = await this._registry.listInstallStates();
    for (const state of states) {
      if (state.status !== 'cached' || !state.cachedHash) {
        continue;
      }
      const record = await this._registry.findById(state.assetId);
      if (!record || record.hash === state.cachedHash) {
        continue;
      }
      await this._backend.remove(state.cachedHash);
      await this._registry.setInstallState({
        assetId: state.assetId,
        status: 'stale',
        cachedHash: state.cachedHash,
        localPath: state.localPath,
        downloadedAt: state.downloadedAt,
      });
      this.warn('asset_manager:reconcile:stale-evicted', {
        assetId: state.assetId,
        oldHash: state.cachedHash,
        newHash: record.hash,
      });
      staleEvicted += 1;
    }

    this.debug('asset_manager:reconcile:complete', { interruptedReset, staleEvicted });
    return { interruptedReset, staleEvicted };
  }

  // ── Blob URL refcounting ─────────────────────────────────────────────

  /** @inheritdoc */
  release(tag: string): void {
    this._blobUrls.releaseTag(tag);
  }

  /** @inheritdoc */
  releaseUrl(url: string): void {
    this._blobUrls.releaseUrl(url);
  }

  // ── Private ──────────────────────────────────────────────────────────

  /** Full resolve pipeline for a single tag. */
  private async _doResolve(tag: string, externalSignal?: AbortSignal): Promise<string | null> {
    const registry = this._registry;
    const backend = this._backend;
    if (!registry || !backend) {
      return null;
    }

    // 1. Already registered → serve the existing blob URL. (The caller's
    //    reference is acquired by resolve(), not here, so concurrent
    //    inflight-shared callers each hold their own ref.)
    const existing = this._blobUrls.peek(tag);
    if (existing) {
      return existing;
    }

    // 1b. Rehydration recorded a verified tag→hash mapping but the blob URL
    //     was not materialised (e.g. the backend file was missing at boot) —
    //     materialise lazily on first access.
    const verifiedHash = this._verifiedHashes.get(tag);
    if (verifiedHash) {
      this._verifiedHashes.delete(tag);
      const blob = await withStepTimeout({
        name: 'backend.get(lazy)',
        timeoutMs: AssetManager._stepTimeoutMs,
        run: () => backend.get(verifiedHash),
      }).catch(() => undefined);
      if (blob) {
        const state = await registry.getInstallState(tag);
        if (state?.status !== 'cached') {
          await registry.setInstallState({
            assetId: tag,
            status: 'cached',
            cachedHash: verifiedHash,
            localPath: verifiedHash,
            downloadedAt: state?.downloadedAt ?? new Date().toISOString(),
          });
        }
        const url = this._registerBlobUrl({ tag, hash: verifiedHash, blob });
        this.debug('asset_manager:lazy-materialised', { assetId: tag });
        return url;
      }
    }

    // 2. Registry row — unknown tags fall back to the static manifest URL.
    const record = await registry.findById(tag);
    if (!record) {
      this.debug('asset_manager:unregistered', { assetId: tag });
      return null;
    }

    const t0 = performance.now();
    const state = await registry.getInstallState(tag);

    // 3. Cache hit: the backend holds the authoritative hash. The content
    //    hash IS the cache key, so presence alone is sufficient — even when
    //    install_state bookkeeping is missing (e.g. an in-memory DB fallback
    //    lost the rows). Target: <10ms/item.
    const cachedHash = state?.status === 'cached' ? state.cachedHash : record.hash;
    if (cachedHash === record.hash && (await backend.has(record.hash))) {
      const blob = await withStepTimeout({
        name: 'backend.get(cacheHit)',
        timeoutMs: AssetManager._stepTimeoutMs,
        run: () => backend.get(record.hash),
      }).catch(() => undefined);
      if (blob) {
        if (state?.status !== 'cached') {
          await registry.setInstallState({
            assetId: tag,
            status: 'cached',
            cachedHash: record.hash,
            localPath: record.hash,
            downloadedAt: new Date().toISOString(),
          });
        }
        const url = this._registerBlobUrl({ tag, hash: record.hash, blob });
        this.debug('asset_manager:cache-hit', {
          assetId: tag,
          ms: Math.round(performance.now() - t0),
        });
        return url;
      }
      // Backend lost the file — fall through and re-fetch.
    }

    // 4. Stale entry: backend has an old hash → evict it now.
    if (state?.cachedHash && state.cachedHash !== record.hash) {
      await backend.remove(state.cachedHash);
      await registry.setInstallState({
        assetId: tag,
        status: 'stale',
        cachedHash: state.cachedHash,
        localPath: state.localPath,
        downloadedAt: state.downloadedAt,
      });
      this.warn('asset_manager:stale-evicted', {
        assetId: tag,
        oldHash: state.cachedHash,
        newHash: record.hash,
      });
    }

    // 5. Fetch from sources (highest priority first), verify, cache, serve.
    const sources = await registry.listSources(tag);
    if (sources.length === 0) {
      return null;
    }
    const sorted = [...sources].sort((a, b) => a.priority - b.priority);

    const controller = externalSignal ? undefined : new AbortController();
    const signal = externalSignal ?? controller?.signal;
    if (controller) {
      this._abortControllers.set(tag, controller);
    }

    try {
      await registry.setInstallState({
        assetId: tag,
        status: 'downloading',
        downloadedAt: new Date().toISOString(),
      });

      for (const source of sorted) {
        if (signal?.aborted) {
          return null;
        }
        try {
          const response = await fetch(source.url, { signal });
          if (!response.ok) {
            throw new Error(`HTTP ${response.status} ${response.statusText}`);
          }
          const blob = await response.blob();

          // Verify SHA-256 against the registry hash BEFORE caching/serving.
          const actualHash = await sha256Hex(blob);
          if (actualHash !== record.hash) {
            this.warn('asset_manager:hash-mismatch', {
              assetId: tag,
              expected: record.hash,
              actual: actualHash,
              source: source.url,
            });
            continue; // discard — try the next source
          }

          // Cache unavailable (e.g. OPFS init failed) — serve online without
          // persisting. The game keeps working; caching retries next boot.
          if (!backend.isAvailable) {
            const url = this._registerBlobUrl({ tag, hash: record.hash, blob });
            this.debug('asset_manager:cache-disabled', { assetId: tag });
            return url;
          }

          try {
            await backend.put({ hash: record.hash, blob });
          } catch (putError) {
            if (!isQuotaExceededError(putError)) {
              throw putError;
            }
            this.warn('asset_manager:quota-exceeded', { assetId: tag });
            const evicted = await this._evictLru();
            if (evicted) {
              // Retry the put once after LRU eviction.
              await backend.put({ hash: record.hash, blob });
            } else {
              await registry.setInstallState({ assetId: tag, status: 'not_downloaded' });
              return null;
            }
          }

          await registry.setInstallState({
            assetId: tag,
            status: 'cached',
            cachedHash: record.hash,
            localPath: record.hash,
            downloadedAt: new Date().toISOString(),
          });
          const url = this._registerBlobUrl({ tag, hash: record.hash, blob });
          this.debug('asset_manager:cache-store', {
            assetId: tag,
            ms: Math.round(performance.now() - t0),
            sizeBytes: blob.size,
          });
          return url;
        } catch (error) {
          if (signal?.aborted) {
            // Interrupted download — leave 'downloading'; reconciled at boot.
            this.debug('asset_manager:cancelled', { assetId: tag });
            return null;
          }
          this.warn('asset_manager:source-failed', {
            assetId: tag,
            source: source.url,
            error: String(error),
          });
        }
      }

      // Every source failed — reset so the next request retries cleanly.
      await registry.setInstallState({ assetId: tag, status: 'not_downloaded' });
      return null;
    } finally {
      if (controller) {
        this._abortControllers.delete(tag);
      }
    }
  }

  /**
   * Evicts the least-recently-downloaded non-core cached asset to free quota
   * (C-373 AC-3). Policy lives in `asset_cache_eviction.ts`.
   *
   * @returns True when an entry was evicted (caller may retry the put).
   */
  private _evictLru(): Promise<boolean> {
    const registry = this._registry;
    const backend = this._backend;
    if (!registry || !backend) {
      return Promise.resolve(false);
    }
    return evictLruCachedAsset({
      registry,
      backend,
      warn: (message, context) => this.warn(message, context),
    });
  }

  /**
   * Registers the current blob URL for a tag. A changed hash publishes a new
   * URL while callers holding the superseded URL keep its exact entry alive.
   */
  private _registerBlobUrl(options: { tag: string; hash: string; blob: Blob }): string {
    return this._blobUrls.register(options);
  }

  /**
   * Runs `fn` over `items` with at most `concurrency` calls in flight at
   * once, rather than one after another. Used to bound wall time for
   * per-item IPC round trips during rehydration without unbounding it
   * entirely (a single `Promise.all` over 10k+ items would flood Tauri's
   * IPC channel at once).
   */
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Selects the platform cache backend: Tauri native disk on desktop,
 * OPFS in the webview/browser.
 */
export const createPlatformCacheBackend = (): AssetCacheBackend => {
  const isTauri = typeof window !== 'undefined' && '__TAURI__' in window;
  return isTauri ? new TauriFSCacheBackend() : new OpfsCacheBackend();
};

// ---------------------------------------------------------------------------
// Singleton
// ---------------------------------------------------------------------------

/** Shared AssetManager singleton (registry + cache resolution). */
export const assetManager: AssetManagerInterface = AssetManager.create({
  className: 'AssetManager',
});
