// apps/frontend/client/src/lib/services/assets/asset_store.svelte.ts
//
// AssetStore — Svelte 5 $state rune-based reactive cache for the asset
// manifest. Loads manifest.json from the static game-assets directory
// and provides tag→URL resolution for PixiJS Assets.load().
//
// The manifest.json is generated by the engine's buildManifest() running
// locally (Bun CLI / Tauri sidecar) and placed in static/game-assets/.
//
// Contract: C-243

import type { AssetManifest, AssetStoreState } from '@aikami/types';
import { logger } from '$logger';

/** Path to the static manifest JSON file. */
const MANIFEST_URL = '/game-assets/manifest.json';

/** Base path for static asset files. */
const ASSETS_BASE = '/game-assets';

export type AssetStore = AssetStoreState & {
  /** Fetch the manifest from the static file. */
  fetchManifest: () => Promise<void>;
  /** Reload the manifest (same as fetchManifest for client-side). */
  rescanAssets: () => Promise<void>;
  /** Resolve a tag to a static file URL. Returns null if tag not found. */
  resolveUrl: (tag: string) => string | null;
  /** Set the current background tag (triggers crossfade in engine). */
  setBackground: (tag: string | null) => void;
  /** Set the current music tag. */
  setMusic: (tag: string | null) => void;
  /** Toggle audio mute state. */
  setAudioMuted: (muted: boolean) => void;
};

class AssetStoreImpl implements AssetStore {
  manifest: AssetManifest | null = $state(null);
  isLoading: boolean = $state(false);
  error: string | null = $state(null);
  currentBackground: string | null = $state(null);
  currentMusic: string | null = $state(null);
  audioMuted: boolean = $state(false);

  // -----------------------------------------------------------------------
  // fetchManifest
  // -----------------------------------------------------------------------

  async fetchManifest(): Promise<void> {
    this.isLoading = true;
    this.error = null;

    try {
      const response = await fetch(MANIFEST_URL);
      if (!response.ok) {
        if (response.status === 404) {
          // No manifest yet — treat as empty
          this.manifest = {
            scannedAt: new Date().toISOString(),
            count: 0,
            assets: {},
            byCategory: { music: [], sfx: [], ambient: [], sprites: [], backgrounds: [] },
          };
          return;
        }
        throw new Error(`Failed to load manifest: ${response.status} ${response.statusText}`);
      }
      this.manifest = await response.json();
      logger.debug('assetStore: manifest loaded', { count: this.manifest?.count });
    } catch (err) {
      this.error = `Failed to load manifest: ${String(err)}`;
      logger.error('assetStore: fetchManifest failed', err);
    } finally {
      this.isLoading = false;
    }
  }

  // -----------------------------------------------------------------------
  // rescanAssets
  // -----------------------------------------------------------------------

  async rescanAssets(): Promise<void> {
    // In the client-side SPA, rescan just reloads the manifest.
    // The actual filesystem scan runs locally (Bun CLI / Tauri sidecar)
    // and writes manifest.json to static/game-assets/.
    await this.fetchManifest();
  }

  // -----------------------------------------------------------------------
  // resolveUrl
  // -----------------------------------------------------------------------

  resolveUrl(tag: string): string | null {
    if (!this.manifest) {
      return null;
    }

    const entry = this.manifest.assets[tag];
    if (!entry) {
      return null;
    }

    return `${ASSETS_BASE}/${entry.path}`;
  }

  // -----------------------------------------------------------------------
  // Playback state
  // -----------------------------------------------------------------------

  setBackground(tag: string | null): void {
    this.currentBackground = tag;
  }

  setMusic(tag: string | null): void {
    this.currentMusic = tag;
  }

  setAudioMuted(muted: boolean): void {
    this.audioMuted = muted;
  }
}

export const assetStore: AssetStore = new AssetStoreImpl();
