// apps/frontend/client/src/lib/services/assets/generated_asset_registration.ts
//
// C-510: the local generated-asset write seam.
//
// Persists generated bytes as a first-class registry asset: verified cache
// write, `assets` row, and a `local-generated` source at `priority = -1` so the
// local copy always outranks a catalog row for the same tag. Local-only — no
// cloud call on this path.
//
// Extracted from AssetManager so the manager stays a resolution/cache service
// and this ordering-sensitive write path is testable on its own.
//
// Contract: C-510 AC-4

import { MAX_UPLOAD_SIZE } from '@aikami/constants';
import type { AssetRegistryRepository } from '@aikami/frontend/storage';
import { bytesToBlob } from '@aikami/local-ai';
import type { GeneratedAsset } from '@aikami/types';
import { isAssetGenerationEnabled } from './asset_generation_flag.ts';
import { sha256Hex } from './asset_hasher.ts';
import { type AssetCacheBackend, AssetHashMismatchError } from './cache_backend.ts';

/** Result of a {@link registerGeneratedAsset} call. */
export type RegisterGeneratedResult = {
  /** True when the asset is now resolvable through the AssetManager. */
  registered: boolean;
  /** The registry tag. */
  tag: string;
  /** Hex SHA-256 the bytes were verified against. */
  sha256: string;
  /** Registry row version after the write. */
  version?: number;
  /** True when identical bytes were already registered for this tag. */
  unchanged?: boolean;
  /** Why the call was a no-op (kill switch off / manager uninitialised). */
  reason?: string;
};

/** The seams the write needs — supplied by the AssetManager. */
export type GeneratedAssetRegistrationDeps = {
  /** Registry over the shared local DB, or null before initialisation. */
  registry: AssetRegistryRepository | null;
  /** Content-hash cache backend, or null before initialisation. */
  backend: AssetCacheBackend | null;
  /**
   * Called after the registry row commits, with the verified blob. The
   * manager uses it to register the blob URL and install state, so a
   * resolvable tag is never published before its bytes exist.
   */
  onRegistered(asset: GeneratedAsset, blob: Blob): Promise<void>;
  /** Debug logger (the manager's own, so log context stays consistent). */
  debug(message: string, context: Record<string, unknown>): void;
  /** Info logger. */
  info(message: string, context: Record<string, unknown>): void;
};

/**
 * Registers generated bytes as a first-class registry asset.
 *
 * Order matters and is the whole point of the seam:
 * 1. kill switch / initialisation checks (no-op, never a throw),
 * 2. size cap, then content-hash verification — nothing unverified is cached,
 * 3. seed-collision guard (a catalog tag must never be shadowed),
 * 4. cache write, then the registry row; the cache write is rolled back if
 *    the row fails, so a crash cannot leave a resolvable tag pointing at
 *    missing bytes.
 *
 * @param deps — Registry, cache backend and post-commit hook.
 * @param asset — The shared descriptor (`toGeneratedAsset` derivation).
 * @param bytes — Raw bytes; their SHA-256 must equal `asset.sha256`.
 * @throws When the bytes do not match the descriptor's hash, exceed
 *         `MAX_UPLOAD_SIZE`, or the tag collides with a boot-seed tag.
 */
export const registerGeneratedAsset = async (
  deps: GeneratedAssetRegistrationDeps,
  asset: GeneratedAsset,
  bytes: Uint8Array,
): Promise<RegisterGeneratedResult> => {
  const base = { tag: asset.tag, sha256: asset.sha256 };

  if (!isAssetGenerationEnabled()) {
    deps.debug('asset_manager:registerGenerated:disabled', { tag: asset.tag });
    return { ...base, registered: false, reason: 'generation_disabled' };
  }

  const { registry, backend } = deps;
  if (!registry || !backend) {
    deps.debug('asset_manager:registerGenerated:uninitialised', { tag: asset.tag });
    return { ...base, registered: false, reason: 'not_initialized' };
  }

  // Size cap first — fail fast rather than stalling the write.
  if (bytes.length > MAX_UPLOAD_SIZE) {
    throw new Error(
      `Generated asset "${asset.tag}" is ${(bytes.length / 1024 / 1024).toFixed(1)} MB — over the ${MAX_UPLOAD_SIZE / 1024 / 1024} MB cap`,
    );
  }

  // Identity is the content hash — never cache or register unverified bytes.
  const blob = bytesToBlob(bytes, asset.mimeType);
  const actualHash = await sha256Hex(blob);
  if (actualHash !== asset.sha256) {
    throw new AssetHashMismatchError({ expectedHash: asset.sha256, actualHash });
  }

  // Seed-collision guard runs BEFORE the cache write so a rejected
  // registration leaves no orphan bytes behind.
  if (await registry.isSeedTag(asset.tag)) {
    const existing = await registry.findById(asset.tag);
    throw new Error(
      `Cannot register the generated asset "${asset.tag}": a catalog (seed) asset already owns that tag (hash ${existing?.hash ?? 'unknown'}). Regenerate under a distinct tag.`,
    );
  }

  // 1. Cache first (the backend re-verifies the hash), 2. then the registry
  //    row. A failure between the two must not leave a resolvable tag
  //    pointing at missing bytes, so the cache write is rolled back.
  await backend.put({ hash: asset.sha256, blob });

  let registration: Awaited<ReturnType<AssetRegistryRepository['registerGenerated']>>;
  try {
    registration = await registry.registerGenerated({
      tag: asset.tag,
      hash: asset.sha256,
      sizeBytes: bytes.length,
      category: asset.category,
      provenanceSource: asset.provenance.source,
    });
  } catch (error) {
    await backend.remove(asset.sha256).catch(() => undefined);
    throw error;
  }

  await deps.onRegistered(asset, blob);

  deps.info('asset_manager:registerGenerated', {
    tag: asset.tag,
    sha256: asset.sha256,
    sizeBytes: bytes.length,
    version: registration.version,
    unchanged: registration.unchanged,
  });

  return {
    ...base,
    registered: true,
    version: registration.version,
    unchanged: registration.unchanged,
  };
};
