// packages/shared/types/src/lib/config_errors.ts
//
// Typed failure taxonomy for configuration and setup operations (C-481).
// These errors are generated by the config service, migration, vault, and
// setup operations — not by the AI gateway (see ai_gateway.ts for those).
//
// Every failure is typed and carries enough context for the caller to
// decide retry vs. recovery vs. user-facing messaging without parsing
// string messages.
//
// Contract: C-481

// ---------------------------------------------------------------------------
// Error code union
// ---------------------------------------------------------------------------

/** Error codes for configuration and setup operations. */
export type ConfigErrorCode =
  /** No AI configuration exists at all — first-time setup. */
  | 'not_configured'
  /** The requested operation is not supported by this provider/adapter. */
  | 'unsupported'
  /** The configuration is structurally invalid (schema violation). */
  | 'invalid_config'
  /** Authentication failed (wrong key, expired, etc.). */
  | 'auth_failed'
  /** Transport-level failure (network error, connection refused). */
  | 'transport_failed'
  /** Request timed out. */
  | 'timeout'
  /** Operation was cancelled by the caller. */
  | 'cancelled'
  /** Result is stale — configuration changed since the operation started. */
  | 'stale_result'
  /** Vault is locked (wrong PIN) or corrupt. */
  | 'vault_locked'
  /** Vault is in an unknown version format. */
  | 'vault_unsupported_version'
  /** Persistence write failed (storage full, quota exceeded). */
  | 'persistence_failed'
  /** Conflict: another instance/tab wrote a newer revision. */
  | 'persistence_conflict'
  /** The requested provider or connection was not found. */
  | 'not_found'
  /** Operation aborted — inconsistent state detected. */
  | 'aborted';

// ---------------------------------------------------------------------------
// Typed error class
// ---------------------------------------------------------------------------

/** Typed error for configuration and setup operations. */
export class ConfigError extends Error {
  /** Machine-readable error code. */
  readonly code: ConfigErrorCode;
  /** Whether retrying the operation may succeed. */
  readonly retryable: boolean;
  /** Whether this error indicates a recoverable state (vault locked, etc.). */
  readonly recoverable: boolean;
  /** Original error, for debugging. Never logged with secrets. */
  readonly originalError?: unknown;

  constructor(options: {
    code: ConfigErrorCode;
    message: string;
    retryable?: boolean;
    recoverable?: boolean;
    originalError?: unknown;
  }) {
    super(options.message);
    this.name = 'ConfigError';
    this.code = options.code;
    this.retryable = options.retryable ?? false;
    this.recoverable = options.recoverable ?? false;
    this.originalError = options.originalError;
  }
}

// ---------------------------------------------------------------------------
// Factory helpers
// ---------------------------------------------------------------------------

/** Create a 'not_configured' error. */
export const notConfigured = (message = 'No AI configuration found'): ConfigError =>
  new ConfigError({ code: 'not_configured', message, recoverable: true });

/** Create an 'unsupported' error. */
export const unsupported = (message = 'Operation not supported'): ConfigError =>
  new ConfigError({ code: 'unsupported', message });

/** Create an 'invalid_config' error. */
export const invalidConfig = (message = 'Invalid configuration'): ConfigError =>
  new ConfigError({ code: 'invalid_config', message, recoverable: true });

/** Create an 'auth_failed' error. */
export const authFailed = (message = 'Authentication failed'): ConfigError =>
  new ConfigError({ code: 'auth_failed', message, retryable: true });

/** Create a 'transport_failed' error. */
export const transportFailed = (message = 'Transport error'): ConfigError =>
  new ConfigError({ code: 'transport_failed', message, retryable: true });

/** Create a 'timeout' error. */
export const timeout = (message = 'Request timed out'): ConfigError =>
  new ConfigError({ code: 'timeout', message, retryable: true });

/** Create a 'cancelled' error. */
export const cancelled = (message = 'Operation cancelled'): ConfigError =>
  new ConfigError({ code: 'cancelled', message });

/** Create a 'stale_result' error. */
export const staleResult = (message = 'Result is stale'): ConfigError =>
  new ConfigError({ code: 'stale_result', message, retryable: true });

/** Create a 'vault_locked' error. */
export const vaultLocked = (message = 'Vault is locked or corrupt'): ConfigError =>
  new ConfigError({ code: 'vault_locked', message, recoverable: true });

/** Create a 'vault_unsupported_version' error. */
export const vaultUnsupportedVersion = (message = 'Vault has an unknown version'): ConfigError =>
  new ConfigError({ code: 'vault_unsupported_version', message, recoverable: true });

/** Create a 'persistence_failed' error. */
export const persistenceFailed = (message = 'Persistence write failed'): ConfigError =>
  new ConfigError({ code: 'persistence_failed', message, retryable: true });

/** Create a 'persistence_conflict' error. */
export const persistenceConflict = (message = 'Persistence conflict'): ConfigError =>
  new ConfigError({ code: 'persistence_conflict', message, retryable: true });

/** Create a 'not_found' error. */
export const notFound = (message = 'Not found'): ConfigError =>
  new ConfigError({ code: 'not_found', message });

/** Create an 'aborted' error. */
export const aborted = (message = 'Operation aborted'): ConfigError =>
  new ConfigError({ code: 'aborted', message });

// ---------------------------------------------------------------------------
// Type guard
// ---------------------------------------------------------------------------

/** Type guard for ConfigError. */
export const isConfigError = (error: unknown): error is ConfigError => error instanceof ConfigError;

// ---------------------------------------------------------------------------
// Redaction
// ---------------------------------------------------------------------------

/**
 * Redacts secrets from an error message for safe logging or display.
 * Strips anything that looks like an API key, bearer token, or secret URL
 * query parameter.
 */
export const redactErrorMessage = (message: string): string => {
  // Redact API key patterns (sk-..., any 32+ char alphanumeric sequence)
  let redacted = message.replace(/\b(sk-[A-Za-z0-9]{20,})\b/g, 'sk-***');
  redacted = redacted.replace(/\b([A-Za-z0-9]{32,})\b/g, '***');
  // Redact Bearer tokens
  redacted = redacted.replace(/Bearer\s+\S+/gi, 'Bearer ***');
  // Redact query param secrets
  redacted = redacted.replace(/([?&]api_key|key|token|secret)=[^&\s]+/gi, '$1=***');
  redacted = redacted.replace(/([?&]password|passwd)=[^&\s]+/gi, '$1=***');
  return redacted;
};
