/**
 * apps/backend/local-stack/stack/env_writer.ts
 *
 * .env generation for the local stack (C-391). Turns a StackPlan into the
 * C-390 .env contract: COMPOSE_PROFILES, COMPOSE_FILE (platform-correct
 * separator), TEXT_MODEL / IMAGE_MODEL pointing at the selected manifest
 * entries, licence acceptance, and the port table.
 *
 * Guarantees (Quality Requirements):
 *   - Atomic: write to a temp file then rename — an interrupted `init`
 *     leaves the prior .env intact.
 *   - Re-run safe: diff against the existing file and require confirmation
 *     before overwrite; a declined re-run leaves the file byte-identical.
 *   - Backup: the previous file is copied to .env.bak before overwrite.
 */

import { constants } from 'node:fs';
import { access, copyFile, readFile, rename, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { EMULATOR_PORTS } from '@aikami/constants';
import type { HardwareProfile, ModelManifest, StackBackend, StackPlan } from '@aikami/local-ai';

/** Backend → compose override file (C-390). `metal` has no override. */
export const BACKEND_COMPOSE_FILE: Readonly<Record<StackBackend, string>> = {
  cpu: 'compose.yaml:compose.cpu.yaml',
  cuda: 'compose.yaml:compose.cuda.yaml',
  rocm: 'compose.yaml:compose.rocm.yaml',
  vulkan: 'compose.yaml:compose.vulkan.yaml',
  intel: 'compose.yaml:compose.intel.yaml',
  musa: 'compose.yaml:compose.musa.yaml',
  metal: 'compose.yaml',
} as const;

/** Separator for COMPOSE_FILE: ':' on POSIX, ';' on Windows (AC-11). */
export const composeSeparator = (platform: HardwareProfile['platform']): ':' | ';' =>
  platform === 'win32' ? ';' : ':';

/**
 * Renders the .env content for a plan + profile.
 *
 * @returns The full .env text.
 */
export const renderEnv = (options: {
  readonly profile: HardwareProfile;
  readonly plan: StackPlan;
  readonly manifest: ModelManifest;
  /** Extra env lines (e.g. TEXT_SERVER_IMAGE for CUDA 13 hosts). */
  readonly extras?: Readonly<Record<string, string>>;
  /** Set when `text` was dropped in favour of a detected/forced host Ollama (see detect_ollama.ts). */
  readonly hostOllamaPort?: number;
}): string => {
  const { profile, plan, manifest, extras, hostOllamaPort } = options;
  const separator = composeSeparator(profile.platform);
  // C-393: the STT port lives in compose.stt.yaml (AC-7 — the default stack
  // must bind no STT port). `stack init` appends the override when the plan
  // includes the stt modality so the generated .env actually publishes it.
  const sttOverride = plan.modalities.includes('stt') ? `${separator}compose.stt.yaml` : '';
  const composeFile = BACKEND_COMPOSE_FILE[plan.backend].split(':').join(separator) + sttOverride;
  const lines: string[] = [];

  lines.push('# Generated by `bun run stack init` (C-391). Edit freely; a re-run shows a diff.');
  lines.push(`# Hardware profile: ${describeProfile(profile)}`);
  lines.push('');
  lines.push('# ── Modality selection ────────────────────────────────────');
  if (hostOllamaPort !== undefined) {
    lines.push(
      `# text intentionally excluded — using existing Ollama on port ${hostOllamaPort} (detected at init). Re-run \`stack init --text-source bundled\` to switch to the bundled engine.`,
    );
  }
  lines.push(`COMPOSE_PROFILES=${plan.modalities.join(',')}`);
  lines.push('');
  lines.push('# ── Hardware backend ──────────────────────────────────────');
  lines.push(`COMPOSE_FILE=${composeFile}`);
  if (plan.nativeEngines) {
    lines.push('# Engines run natively (bin/run-native-*.sh) — only client is containerised.');
  }
  lines.push('');

  // ── Model selection (paths inside the models volume) ──────────────────
  // The compose services read TEXT_MODEL / IMAGE_MODEL (single-file
  // checkpoints, e.g. SD1.5) or IMAGE_DIFFUSION_MODEL + IMAGE_VAE_MODEL /
  // IMAGE_LLM_MODEL / IMAGE_CLIP_L_MODEL / IMAGE_CLIP_G_MODEL /
  // IMAGE_T5XXL_MODEL (a diffusion model whose VAE/text-encoder ship as
  // separate files, e.g. Anima) as file names inside the models volume.
  // Resolve from the manifest entries via the plan's manifestId → the
  // targetPath the fetcher wrote.
  const targetOf = (manifestId: string): string | undefined =>
    manifest.entries.find((entry) => entry.id === manifestId)?.targetPath;
  const textEntry = plan.models.find((m) => m.modality === 'text');
  const imageEntry = plan.models.find((m) => m.modality === 'image' && !m.role);
  const imageCompanions = plan.models.filter((m) => m.modality === 'image' && m.role);
  const textPath = textEntry ? targetOf(textEntry.manifestId) : undefined;
  const imagePath = imageEntry ? targetOf(imageEntry.manifestId) : undefined;
  const companionEnvVar: Readonly<Record<string, string>> = {
    vae: 'IMAGE_VAE_MODEL',
    llm: 'IMAGE_LLM_MODEL',
    // biome-ignore-start lint/style/useNamingConvention: matches the manifest's companion `role` literals, which match sd-server's own --clip_l/--clip_g flag spelling
    clip_l: 'IMAGE_CLIP_L_MODEL',
    clip_g: 'IMAGE_CLIP_G_MODEL',
    // biome-ignore-end lint/style/useNamingConvention: matches the manifest's companion `role` literals, which match sd-server's own --clip_l/--clip_g flag spelling
    t5xxl: 'IMAGE_T5XXL_MODEL',
  };
  if (textPath || imagePath) {
    lines.push('# ── Model selection (paths inside the models volume) ──────');
    if (textPath) {
      lines.push(`TEXT_MODEL=${basename(textPath)}`);
    }
    if (imagePath) {
      if (imageCompanions.length > 0) {
        lines.push(`IMAGE_DIFFUSION_MODEL=${basename(imagePath)}`);
        for (const companion of imageCompanions) {
          const companionPath = targetOf(companion.manifestId);
          const envVar = companion.role ? companionEnvVar[companion.role] : undefined;
          if (companionPath && envVar) {
            lines.push(`${envVar}=${basename(companionPath)}`);
          }
        }
      } else {
        lines.push(`IMAGE_MODEL=${basename(imagePath)}`);
      }
    }
    lines.push('');
  }

  // ── Licences ──────────────────────────────────────────────────────────
  const acknowledged = plan.models.filter((m) => m.requiresAcknowledgement);
  if (acknowledged.length > 0) {
    lines.push('# ── Licences ─────────────────────────────────────────────');
    lines.push('# The plan includes use-restricted model(s); accepted below.');
    // A primary entry and its companions (e.g. Anima's vae/llm) often share
    // one license — dedupe so AIKAMI_ACCEPT_LICENSES doesn't repeat it.
    lines.push(
      `AIKAMI_ACCEPT_LICENSES=${[...new Set(acknowledged.map((m) => m.license))].join(',')}`,
    );
    lines.push('');
  }

  // ── Voice extras ──────────────────────────────────────────────────────
  if (plan.modalities.includes('stt')) {
    lines.push('# ── Voice extras ─────────────────────────────────────────');
    lines.push('ENABLE_STT=true');
    lines.push('');
  }

  // ── Ports (defaults from development_ports.ts) ───────────────────────
  lines.push('# ── Ports (defaults from packages/shared/constants/development_ports.ts) ─');
  lines.push(`TEXT_PORT=${EMULATOR_PORTS.text}`);
  lines.push(`IMAGE_PORT=${EMULATOR_PORTS.image}`);
  lines.push(`TTS_PORT=${EMULATOR_PORTS.voice}`);
  lines.push(`STT_PORT=${EMULATOR_PORTS.stt}`);
  lines.push(`CLIENT_PORT=${EMULATOR_PORTS.client}`);
  lines.push('');

  if (extras) {
    for (const [key, value] of Object.entries(extras)) {
      lines.push(`${key}=${value}`);
    }
  }

  return `${lines.join('\n')}\n`;
};

/** One-line hardware description for the .env header. */
export const describeProfile = (profile: HardwareProfile): string => {
  const gpu =
    profile.gpu.vendor === 'none'
      ? 'no GPU'
      : `${profile.gpu.vendor}${profile.gpu.name ? ` ${profile.gpu.name}` : ''}${profile.gpu.vramMb ? ` (${profile.gpu.vramMb} MiB)` : ''}`;
  return `${profile.platform}/${profile.arch}, ${gpu}, ${profile.ramMb} MiB RAM, ${profile.cores} cores, ${(profile.freeDiskBytes / 1024 / 1024 / 1024).toFixed(1)} GiB free`;
};

/** True when the path exists. */
export const exists = async (path: string): Promise<boolean> => {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
};

/**
 * Loads the existing .env contents, if any.
 */
export const readExistingEnv = async (path: string): Promise<string | undefined> => {
  if (!(await exists(path))) {
    return undefined;
  }
  return readFile(path, 'utf8');
};

/**
 * Computes a minimal unified diff between two .env texts (old → new).
 * One line per change: `- old` / `+ new` / `  context`.
 */
export const diffEnv = (oldText: string, newText: string): string => {
  const oldLines = oldText.split('\n');
  const newLines = newText.split('\n');
  const oldMap = new Map<string, number>();
  for (let i = 0; i < oldLines.length; i += 1) {
    const line = oldLines[i] as string;
    if (line && !line.startsWith('#')) {
      oldMap.set(line, (oldMap.get(line) ?? 0) + 1);
    }
  }
  const newMap = new Map<string, number>();
  for (let i = 0; i < newLines.length; i += 1) {
    const line = newLines[i] as string;
    if (line && !line.startsWith('#')) {
      newMap.set(line, (newMap.get(line) ?? 0) + 1);
    }
  }

  const out: string[] = ['  # .env diff (existing → generated)'];
  const keys = new Set([...oldMap.keys(), ...newMap.keys()]);
  for (const key of keys) {
    const oldCount = oldMap.get(key) ?? 0;
    const newCount = newMap.get(key) ?? 0;
    if (oldCount === 0) {
      out.push(`+ ${key}`);
    } else if (newCount === 0) {
      out.push(`- ${key}`);
    } else if (oldCount !== newCount) {
      out.push(`- ${key}`);
      out.push(`+ ${key}`);
    }
  }
  if (out.length === 1) {
    out.push('  (no changes)');
  }
  return out.join('\n');
};

/**
 * Atomically writes the .env: temp file in the same directory, then rename.
 * Backs up an existing file to `<path>.bak` first.
 *
 * @throws Error when the directory is missing or the write fails.
 */
export const writeEnvAtomic = async (options: {
  readonly path: string;
  readonly content: string;
}): Promise<void> => {
  const { path, content } = options;
  const dir = dirname(path);
  const tmp = join(dir, `.env.tmp-${process.pid}`);
  await writeFile(tmp, content, 'utf8');
  if (await exists(path)) {
    await copyFile(path, `${path}.bak`);
  }
  await rename(tmp, path);
};

/** Env extras for CUDA 13 hosts (AC-2: server-cuda vs server-cuda13). */
export const cudaExtras = (profile: HardwareProfile): Record<string, string> | undefined => {
  if (profile.gpu.vendor !== 'nvidia' || profile.gpu.cudaMajor !== 13) {
    return undefined;
  }
  return {
    // biome-ignore lint/style/useNamingConvention: env var key, SCREAMING_SNAKE_CASE is the .env convention
    TEXT_SERVER_IMAGE: 'ghcr.io/ggml-org/llama.cpp:server-cuda13',
  };
};
