// apps/e2e/src/auth.setup.ts
// Playwright project dependency setup — authenticates a test identity against
// the local Firebase Auth emulator and serialises the session state to
// .auth/user.json for reuse by downstream browser projects.
//
// C-054 AC-1: Authentication State Caching
// The setup project runs before any test suites. It creates a test user via
// the Auth emulator REST API, injects the Firebase Auth session into the
// browser's IndexedDB storage layer, and persists the full storageState
// (cookies + localStorage + IndexedDB origins) to disk.

import { test as setup } from '@playwright/test';
import { EMULATOR_PORTS } from './config';

// ── Configuration ───────────────────────────────────────────

/** PWA dev server base URL. */
const CLIENT_BASE_URL = `http://localhost:${EMULATOR_PORTS.client}`;

/** Auth emulator REST base URL. */
const AUTH_EMULATOR_URL = `http://127.0.0.1:${EMULATOR_PORTS.auth}`;

/** Auth state cache file generated by this setup project. */
const AUTH_STATE_FILE = './.auth/user.json';

/** Test user credentials — matches EMULATOR_USERS in @aikami/mocks seed data. */
const TEST_EMAIL = 'user@example.com';
const TEST_PASSWORD = 'asdasd';

/** Firebase API key for the emulator. */
const FIREBASE_API_KEY = 'fake-api-key';

/** Firebase Auth IndexedDB persistence key format: firebase:authUser:{apiKey}:{appName} */
const AUTH_STORAGE_KEY = `firebase:authUser:${FIREBASE_API_KEY}:[DEFAULT]`;

// ── Auth Emulator REST helpers ──────────────────────────────

type AuthTokens = {
  localId: string;
  idToken: string;
  refreshToken: string;
};

/**
 * Creates a user account in the Auth emulator via REST API.
 */
const _createEmulatorUser = async (options: {
  email: string;
  password: string;
}): Promise<AuthTokens> => {
  const resp = await fetch(
    `${AUTH_EMULATOR_URL}/identitytoolkit.googleapis.com/v1/accounts:signUp?key=${FIREBASE_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: options.email,
        password: options.password,
        returnSecureToken: true,
      }),
    },
  );
  const data = (await resp.json()) as {
    localId: string;
    idToken: string;
    refreshToken: string;
  };
  return {
    localId: data.localId,
    idToken: data.idToken,
    refreshToken: data.refreshToken,
  };
};

/**
 * Signs in an existing user and returns fresh tokens.
 */
const _signInEmulatorUser = async (options: {
  email: string;
  password: string;
}): Promise<AuthTokens> => {
  const resp = await fetch(
    `${AUTH_EMULATOR_URL}/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=${FIREBASE_API_KEY}`,
    {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        email: options.email,
        password: options.password,
        returnSecureToken: true,
      }),
    },
  );
  const data = (await resp.json()) as {
    localId: string;
    idToken: string;
    refreshToken: string;
  };
  return {
    localId: data.localId,
    idToken: data.idToken,
    refreshToken: data.refreshToken,
  };
};

// ── Setup test ──────────────────────────────────────────────

setup('authenticate test user', async ({ page }) => {
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] Starting test user authentication setup');
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log(`[auth.setup] Auth emulator: ${AUTH_EMULATOR_URL}`);
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log(`[auth.setup] PWA target: ${CLIENT_BASE_URL}`);

  // Step 1 — Ensure the test user exists in the Auth emulator.
  const { localId } = await _createEmulatorUser({
    email: TEST_EMAIL,
    password: TEST_PASSWORD,
  });
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log(`[auth.setup] Test user localId: ${localId}`);

  // Step 2 — Sign in to get fresh tokens.
  const { idToken, refreshToken } = await _signInEmulatorUser({
    email: TEST_EMAIL,
    password: TEST_PASSWORD,
  });
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] Tokens obtained');

  // Step 3 — Inject the Firebase Auth session into IndexedDB BEFORE
  // navigating to the PWA. Uses `page.context().addInitScript` so the state
  // is available when Firebase Auth SDK initialises.
  await page.context().addInitScript(
    (initData: unknown) => {
      const {
        key,
        idToken: _idToken,
        refreshToken: _refreshToken,
        email: _email,
        uid: _uid,
      } = initData as {
        key: string;
        idToken: string;
        refreshToken: string;
        email: string;
        uid: string;
      };

      return new Promise<void>((resolve, reject) => {
        const request = indexedDB.open('firebaseLocalStorageDb', 1);

        request.onupgradeneeded = () => {
          const db = request.result;
          if (!db.objectStoreNames.contains('firebaseLocalStorage')) {
            db.createObjectStore('firebaseLocalStorage');
          }
        };

        request.onsuccess = () => {
          const db = request.result;
          const transaction = db.transaction(['firebaseLocalStorage'], 'readwrite');
          const store = transaction.objectStore('firebaseLocalStorage');

          const authUser = {
            uid: _uid,
            email: _email,
            emailVerified: false,
            isAnonymous: false,
            providerData: [
              {
                providerId: 'password',
                uid: _email,
                email: _email,
              },
            ],
            stsTokenManager: {
              refreshToken: _refreshToken,
              accessToken: _idToken,
              expirationTime: Date.now() + 3_600_000,
            },
            createdAt: String(Date.now()),
            lastLoginAt: String(Date.now()),
            apiKey: FIREBASE_API_KEY,
            appName: '[DEFAULT]',
          };

          store.put({ name: key, value: authUser });

          transaction.oncomplete = () => {
            db.close();
            resolve();
          };
          transaction.onerror = () => {
            db.close();
            reject(transaction.error);
          };
        };

        request.onerror = () => {
          reject(request.error);
        };
      });
    },
    {
      key: AUTH_STORAGE_KEY,
      idToken,
      refreshToken,
      email: TEST_EMAIL,
      uid: localId,
    },
  );
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] Auth state init script registered');

  // Step 4 — Navigate to the PWA. The addInitScript runs before any page
  // scripts, so Firebase Auth SDK finds the injected state.
  await page.goto(CLIENT_BASE_URL, { waitUntil: 'domcontentloaded' });
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] PWA loaded with pre-injected auth state');

  // Step 5 — Wait for the PWA to process the auth state.
  await page.waitForLoadState('networkidle');
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] PWA fully loaded');

  // Step 6 — Persist the storageState (cookies + localStorage + IndexedDB).
  await page.context().storageState({ path: AUTH_STATE_FILE });
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log(`[auth.setup] Auth state saved to ${AUTH_STATE_FILE}`);
  // biome-ignore lint/suspicious/noConsole: setup lifecycle logging
  console.log('[auth.setup] Setup complete');
});
