# packages/backend/configs/moon.yml
$schema: 'https://moonrepo.dev/schemas/project.json'

language: 'typescript'
layer: 'library'
tags:
  - 'config'
  - 'backend'
  - 'library'

project:
  name: 'backend-configs'
  description: 'Shared backend configuration files and environment schemas.'
  channel: '#backend'
  owner: 'Backend Team'

dependsOn:
  - 'constants'
  - 'schemas'
  - 'types'

