// scripts/src/lib/ops/gen_model_bundle.ts
//
// Generates a LocalModelBundle literal from a HuggingFace repo + revision +
// file list. Downloads each file, computes SHA-256, and prints the
// TypeScript literal for copy-paste into packages/shared/constants/src/lib/local_models.ts.
//
// Usage:
//   bun run scripts/src/lib/ops/gen_model_bundle.ts --repo onnx-community/Kokoro-82M-ONNX \
//     --revision f46687f7e41512228ae953af24a11b2640ea0f22 \
//     --files config.json tokenizer.json onnx/model_quantized.onnx
//
// Output:
//   A LocalModelBundle literal with computed sizes and SHA-256 hashes.

import { createHash } from 'node:crypto';

type Asset = {
  path: string;
  bytes: number;
  sha256: string;
};

const parseArgs = (): { repo: string; revision: string; files: string[] } => {
  const args = process.argv.slice(2);
  const repo = args[args.indexOf('--repo') + 1] ?? '';
  const revision = args[args.indexOf('--revision') + 1] ?? '';
  const filesIdx = args.indexOf('--files');
  const files = filesIdx >= 0 ? args.slice(filesIdx + 1) : [];

  if (!repo || !revision || files.length === 0) {
    console.error(
      'Usage: gen_model_bundle.ts --repo <repo> --revision <revision> --files <file1> <file2> ...',
    );
    console.error('  --repo      HuggingFace repo id (e.g. onnx-community/Kokoro-82M-ONNX)');
    console.error('  --revision  Pinned commit hash');
    console.error('  --files     One or more file paths within the repo');
    process.exit(1);
  }

  return { repo, revision, files };
};

const downloadFile = async (url: string): Promise<Buffer> => {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to download ${url}: HTTP ${response.status}`);
  }
  const buffer = Buffer.from(await response.arrayBuffer());
  return buffer;
};

const sha256Hex = (buffer: Buffer): string => createHash('sha256').update(buffer).digest('hex');

const generateBundle = async (): Promise<void> => {
  const { repo, revision, files } = parseArgs();

  console.error(`Downloading ${files.length} files from ${repo} @ ${revision}...`);

  const assets: Asset[] = [];
  for (const file of files) {
    const url = `https://huggingface.co/${repo}/resolve/${revision}/${file}`;
    console.error(`  Fetching ${url}...`);
    const buffer = await downloadFile(url);
    const hash = sha256Hex(buffer);
    assets.push({ path: file, bytes: buffer.length, sha256: hash });
    console.error(`    ${buffer.length} bytes, SHA-256: ${hash}`);
  }

  // Print the TypeScript literal
  console.log('\n// Generated by gen_model_bundle.ts');
  console.log('// Source:', `${repo} @ ${revision}`);
  console.log('assets: [');
  for (const asset of assets) {
    console.log(`  {
    path: '${asset.path}',
    bytes: ${asset.bytes},
    sha256: '${asset.sha256}',
  },`);
  }
  console.log('],');
};

await generateBundle();
