// scripts/src/lib/ops/sync_emberwatch_credits.ts
//
// Adds the Emberwatch pack's own attribution entries to
// `scripts/src/lib/catalog/project_licenses.json`.
//
// The publish preflight hard-fails any catalog tag that appears in none of the
// three committed attribution sources (LPC CREDITS join, LPC supplement,
// project licences). When the pack gained new artifacts — the props atlas
// pages, the two expansion maps, pack portraits, prop source art and hostile
// creature art — those tags had no entry and the release was refused with
// `unresolved: sprites:tilesets:props.webp`.
//
// The licence is DERIVED, never guessed:
//   • art produced by this repository's local image pipeline carries a
//     generated-rights block whose OUTPUT classification is read from
//     `model_rights_evidence.ts` — pinned quotations from the model's licence
//     at the exact revision used, never a paraphrase;
//   • everything the project authored itself (pack JSON, packed atlas pages,
//     recomposed maps) is the repository's own MIT work.
//
// ── Why generated entries record TWO licences ──────────────────────────────
//
// A generated asset's `licenses` array holds the GENERATOR MODEL's licence,
// which is what an upstream credits page must show. That string is NOT the
// artifact's distribution terms, and the release gate does not read it as such:
// the gate reads `rights.outputRights`. Anima's pinned licence restricts the
// model while explicitly permitting its outputs commercially, so an entry that
// recorded only the model licence was unreadable — it said "non-commercial"
// about an artifact that may in fact ship.
//
// Run: bun scripts/src/lib/ops/sync_emberwatch_credits.ts [--check]

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MODEL_RIGHTS_EVIDENCE, type ModelRightsRecord } from '../catalog/model_rights_evidence.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repository = join(here, '../../../..');
const licensesPath = join(repository, 'scripts/src/lib/catalog/project_licenses.json');
const packRoot = join(repository, 'content/packs/emberwatch');

type Credit = {
  licenses: string[];
  authors: string[];
  sourceUrls: string[];
  licenseNote: string;
  rights?: GeneratedRights;
};

type GeneratedRights = {
  kind: 'generated';
  generator: { model: string; revision: string; engine: string };
  modelUse: string;
  modelRedistribution: string;
  outputRights: string;
  evidence: { url: string; revision: string; retrievedAt: string; quote: string };
  upstream: { id: string; licenseName: string; outputRights: string };
};

const PROJECT: Credit = {
  licenses: ['MIT'],
  authors: ['Aikami Studio'],
  sourceUrls: [],
  licenseNote:
    "Project-authored Emberwatch content-pack artifact, committed in-repo under the repo's MIT licence.",
};

/** A local generation model, resolved from the stack manifest and rights registry. */
const localGeneratedCredit = (options: {
  modelId: string;
  engine: string;
  author: string;
}): Credit => {
  const manifest = JSON.parse(
    readFileSync(join(repository, 'apps/backend/local-stack/stack/models.manifest.json'), 'utf8'),
  ) as {
    entries: { id: string; license: string; repo?: string; revision?: string }[];
  };
  const entry = manifest.entries.find((candidate) => candidate.id === options.modelId);
  if (entry === undefined) {
    throw new Error(
      `sync_emberwatch_credits: ${options.modelId} is not in the stack manifest — refusing to invent a licence for generated art`,
    );
  }
  // The stack manifest pins the revision; the evidence registry must vouch for
  // THAT revision. A drift here is a real problem, not a formatting issue: it
  // would mean the pinned evidence describes different weights.
  const record: ModelRightsRecord | undefined = MODEL_RIGHTS_EVIDENCE.find(
    (candidate) => candidate.modelId === entry.id,
  );
  if (record === undefined) {
    throw new Error(
      `sync_emberwatch_credits: no pinned rights evidence for "${entry.id}" — refusing to classify generated output without evidence`,
    );
  }
  if (entry.revision !== undefined && entry.revision !== record.revision) {
    throw new Error(
      `sync_emberwatch_credits: the stack manifest pins "${entry.id}" at ${entry.revision} but the ` +
        `rights evidence was read at ${record.revision} — re-read the licence at the pinned revision ` +
        'before publishing art generated by it',
    );
  }
  if (record.outputRights !== 'commercial-permitted') {
    throw new Error(
      `sync_emberwatch_credits: "${entry.id}" output rights are "${record.outputRights}" — the pack cannot be published`,
    );
  }

  const rights: GeneratedRights = {
    kind: 'generated',
    generator: { model: record.modelId, revision: record.revision, engine: options.engine },
    modelUse: record.modelUse,
    modelRedistribution: record.modelRedistribution,
    outputRights: record.outputRights,
    evidence: record.evidence,
    upstream: {
      id: record.upstream.id,
      licenseName: record.upstream.licenseName,
      outputRights: record.upstream.outputRights,
    },
  };

  return {
    // The MODEL's licence, shown verbatim on the credits page.
    licenses: [entry.license],
    // The MODEL is the author of generated work. `asset_provenance.ts` forbids
    // fabricating a human author for generated output.
    authors: [options.author],
    sourceUrls: entry.repo === undefined ? [] : [`https://huggingface.co/${entry.repo}`],
    licenseNote:
      options.modelId === 'image-anima-aesthetic-v1.1'
        ? `Generated by this repository's local image pipeline with ${record.modelId}@${record.revision.slice(0, 12)}. ` +
          `The model's ${record.licenseName} restricts the MODEL (use: ${record.modelUse}; redistribution: ` +
          `${record.modelRedistribution}) but its OUTPUTS are explicitly commercially usable — ` +
          `"${record.evidence.quote}" — so this artifact is published under outputRights=` +
          `"${record.outputRights}". The weights themselves are never distributed.`
        : `Generated by this repository's local ${options.engine} pipeline with ${record.modelId}@${record.revision.slice(0, 12)}. ` +
          `Pinned evidence classifies model use as ${record.modelUse}, model redistribution as ` +
          `${record.modelRedistribution}, and generated outputs as ${record.outputRights}.`,
    rights,
  };
};

const localImageCredit = (): Credit =>
  localGeneratedCredit({
    modelId: 'image-anima-aesthetic-v1.1',
    engine: 'local-sd-cpp',
    author: 'image-anima-aesthetic-v1.1 (local sd.cpp + Anima pipeline)',
  });

const localAudioCredit = (): Credit =>
  localGeneratedCredit({
    modelId: 'audio-ace-step-v1-3.5b',
    engine: 'ace-step',
    author: 'ace-step (audio-ace-step-v1-3.5b)',
  });

/** True when an existing entry is the machine-derived generated credit. */
const isDerivedGeneratedEntry = (credit: Credit): boolean =>
  credit.rights?.kind === 'generated' ||
  (credit.rights === undefined &&
    (credit.authors ?? []).some(
      (author) =>
        author.includes('local sd.cpp + Anima pipeline') ||
        author === 'ace-step (audio-ace-step-v1-3.5b)',
    ));

const main = (): void => {
  const checkOnly = process.argv.includes('--check');
  const file = JSON.parse(readFileSync(licensesPath, 'utf8')) as {
    credits: Record<string, Credit>;
  };
  const manifest = JSON.parse(readFileSync(join(packRoot, 'manifest.json'), 'utf8')) as {
    props: Record<string, { frame: string; provenance?: { source?: string } }>;
    npcs: Record<string, { portraits?: { variants: Record<string, string> } }>;
    audio?: { bindings?: { tag: string }[] };
  };

  const local = localImageCredit();
  const localAudio = localAudioCredit();
  const legacyGeneratedAudioTags = new Set<string>();
  const additions: Record<string, Credit> = {
    // Packed atlas pages and their descriptors are project output.
    'sprites:tilesets:props.webp': PROJECT,
    'sprites:tilesets:props.json': PROJECT,
    'sprites:tilesets:props.pages.json': PROJECT,
  };

  for (const mapId of ['village', 'inn', 'merchant_shop', 'old_road', 'ruined_shrine']) {
    additions[`emberwatch:maps:${mapId}`] = PROJECT;
  }

  for (const binding of manifest.audio?.bindings ?? []) {
    additions[binding.tag] = localAudio;
    legacyGeneratedAudioTags.add(binding.tag);
  }

  // Portraits are published from the GAME-DATA root (that is where the client
  // resolves them), so their catalog tag carries no `emberwatch` segment. The
  // CONTENT-PACK scan of the same bytes produces the prefixed form instead, and
  // both are real catalog tags — so both are credited, or one root's copy of the
  // identical file is classified from a stale entry.
  for (const [, npc] of Object.entries(manifest.npcs)) {
    for (const [variant, url] of Object.entries(npc.portraits?.variants ?? {})) {
      const npcId = url.split('/')[4] ?? '';
      additions[`portraits:emberwatch:${npcId}:${variant}`] = local;
      additions[`emberwatch:portraits:${npcId}:${variant}`] = local;
    }
  }

  // Every file actually present in the pack's art directories, so an unused or
  // newly added file cannot slip past the preflight. The licence follows the
  // provenance the prop table records — never a blanket licence.
  const localFrames = new Set(
    Object.values(manifest.props)
      .filter((def) => (def.provenance?.source ?? '').startsWith('generated:local'))
      .map((def) => def.frame.replace(/\.png$/, '')),
  );
  for (const dir of ['props', 'enemies', 'audio']) {
    const dirPath = join(packRoot, dir);
    if (!existsSync(dirPath)) {
      continue;
    }
    for (const name of readdirSync(dirPath).sort()) {
      if (!/\.(png|webp|webm|ogg|mp3|wav)$/i.test(name)) {
        continue;
      }
      const stem = name.replace(/\.[^.]+$/, '');
      let credit = PROJECT;
      if (dir === 'audio') {
        credit = localAudio;
      } else if (localFrames.has(stem)) {
        credit = local;
      }
      additions[`emberwatch:${dir}:${stem}`] = credit;
      if (dir === 'audio') {
        legacyGeneratedAudioTags.add(`emberwatch:${dir}:${stem}`);
      }
    }
  }

  let changed = 0;
  const changedTags: string[] = [];
  for (const [tag, credit] of Object.entries(additions)) {
    const existing = file.credits[tag];
    if (existing === undefined) {
      file.credits[tag] = credit;
      changed += 1;
      changedTags.push(tag);
      continue;
    }
    if (JSON.stringify(existing) === JSON.stringify(credit)) {
      continue;
    }
    // A hand-authored entry wins. A MACHINE-derived one is upgraded in place:
    // the previous shape recorded only the model's licence, which the release
    // gate could not read as the artifact's output rights, so leaving it would
    // keep the whole pack blocked by a classification that does not apply.
    const isLegacyAudioPlaceholder =
      legacyGeneratedAudioTags.has(tag) && JSON.stringify(existing) === JSON.stringify(PROJECT);
    if (isDerivedGeneratedEntry(existing) || isLegacyAudioPlaceholder) {
      file.credits[tag] = credit;
      changed += 1;
      changedTags.push(tag);
    }
  }

  if (checkOnly) {
    if (changedTags.length > 0) {
      console.error(
        `emberwatch credits are incomplete or stale — ${changedTags.length} tag(s), e.g. ${changedTags.slice(0, 3).join(', ')}`,
      );
      process.exit(1);
    }
    console.log('emberwatch credits are complete');
    return;
  }

  if (changed > 0) {
    writeFileSync(licensesPath, `${JSON.stringify(file, null, 2)}\n`);
    // The sidecar is a committed source file, so it must land in the repo's
    // formatter's shape: `JSON.stringify` spacing is not Biome's JSON style,
    // and a hand-shaped sidecar fails `scripts:lint` on every release run.
    const format = Bun.spawnSync(['bunx', 'biome', 'check', '--write', licensesPath], {
      cwd: repository,
      stdout: 'ignore',
      stderr: 'inherit',
    });
    if (format.exitCode !== 0) {
      throw new Error('sync_emberwatch_credits: could not format project_licenses.json');
    }
  }
  console.log(
    `sync_emberwatch_credits: ${changed} credit(s) updated, ${Object.keys(file.credits).length} total`,
  );
};

main();
