// scripts/src/lib/ops/sync_emberwatch_credits.ts
//
// Adds the Emberwatch pack's own attribution entries to
// `scripts/src/lib/catalog/project_licenses.json`.
//
// The publish preflight hard-fails any catalog tag that appears in none of the
// three committed attribution sources (LPC CREDITS join, LPC supplement,
// project licences). When the pack gained new artifacts — the props atlas
// pages, the two expansion maps, pack portraits, prop source art and hostile
// creature art — those tags had no entry and the release was refused with
// `unresolved: sprites:tilesets:props.webp`.
//
// The licence is DERIVED, never guessed:
//   • art produced by this repository's local image pipeline is attributed to
//     the model that produced it, with that model's licence from
//     `stack/models.manifest.json` — never a fabricated human author;
//   • everything the project authored itself (pack JSON, packed atlas pages,
//     recomposed maps) is the repository's own MIT work.
//
// Run: bun scripts/src/lib/ops/sync_emberwatch_credits.ts [--check]

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repository = join(here, '../../../..');
const licensesPath = join(repository, 'scripts/src/lib/catalog/project_licenses.json');
const packRoot = join(repository, 'content/packs/emberwatch');

type Credit = {
  licenses: string[];
  authors: string[];
  sourceUrls: string[];
  licenseNote: string;
};

const PROJECT: Credit = {
  licenses: ['MIT'],
  authors: ['Aikami Studio'],
  sourceUrls: [],
  licenseNote:
    "Project-authored Emberwatch content-pack artifact, committed in-repo under the repo's MIT licence.",
};

/** The local image pipeline's model, resolved from the stack manifest. */
const localImageCredit = (): Credit => {
  const manifest = JSON.parse(
    readFileSync(join(repository, 'apps/backend/local-stack/stack/models.manifest.json'), 'utf8'),
  ) as {
    entries: { id: string; license: string; repo?: string; revision?: string }[];
  };
  const entry = manifest.entries.find((candidate) => candidate.id === 'image-anima-aesthetic-v1.1');
  if (entry === undefined) {
    throw new Error(
      'sync_emberwatch_credits: the local image model is not in the stack manifest — refusing to invent a licence for generated art',
    );
  }
  return {
    licenses: [entry.license],
    // The MODEL is the author of generated work. `asset_provenance.ts` forbids
    // fabricating a human author for generated output.
    authors: [`${entry.id} (local sd.cpp + Anima pipeline)`],
    sourceUrls: entry.repo === undefined ? [] : [`https://huggingface.co/${entry.repo}`],
    licenseNote:
      "Generated by this repository's local image pipeline. The licence is the base model's inference/production terms; the generated-output and game-redistribution rights decision is recorded separately.",
  };
};

const main = (): void => {
  const checkOnly = process.argv.includes('--check');
  const file = JSON.parse(readFileSync(licensesPath, 'utf8')) as {
    credits: Record<string, Credit>;
  };
  const manifest = JSON.parse(readFileSync(join(packRoot, 'manifest.json'), 'utf8')) as {
    props: Record<string, { frame: string; provenance?: { source?: string } }>;
    npcs: Record<string, { portraits?: { variants: Record<string, string> } }>;
  };

  const local = localImageCredit();
  const additions: Record<string, Credit> = {
    // Packed atlas pages and their descriptors are project output.
    'sprites:tilesets:props.webp': PROJECT,
    'sprites:tilesets:props.json': PROJECT,
    'sprites:tilesets:props.pages.json': PROJECT,
  };

  // Every map the pack declares.
  const index = JSON.parse(readFileSync(join(repository, 'content/packs/index.json'), 'utf8')) as {
    packs: { id: string; name: string }[];
  };
  void index;
  for (const mapId of ['village', 'inn', 'merchant_shop', 'old_road', 'ruined_shrine']) {
    additions[`emberwatch:maps:${mapId}`] = PROJECT;
  }

  // Portraits are published from the GAME-DATA root (that is where the client
  // resolves them), so their catalog tag carries no `emberwatch` segment.
  for (const [, npc] of Object.entries(manifest.npcs)) {
    for (const [variant, url] of Object.entries(npc.portraits?.variants ?? {})) {
      const npcId = url.split('/')[4] ?? '';
      additions[`portraits:emberwatch:${npcId}:${variant}`] = local;
    }
  }

  // Every file actually present in the pack's art directories, so an unused or
  // newly added file cannot slip past the preflight. The licence follows the
  // provenance the prop table records - never a blanket licence.
  const localFrames = new Set(
    Object.values(manifest.props)
      .filter((def) => (def.provenance?.source ?? '').startsWith('generated:local'))
      .map((def) => def.frame.replace(/\.png$/, '')),
  );
  for (const dir of ['props', 'enemies', 'audio']) {
    const dirPath = join(packRoot, dir);
    if (!existsSync(dirPath)) {
      continue;
    }
    for (const name of readdirSync(dirPath).sort()) {
      if (!/\.(png|webp|webm|ogg|mp3|wav)$/i.test(name)) {
        continue;
      }
      const stem = name.replace(/\.[^.]+$/, '');
      additions[`emberwatch:${dir}:${stem}`] = localFrames.has(stem) ? local : PROJECT;
    }
  }

  let changed = 0;
  for (const [tag, credit] of Object.entries(additions)) {
    const existing = file.credits[tag];
    if (existing === undefined) {
      file.credits[tag] = credit;
      changed += 1;
      continue;
    }
    // An existing hand-authored entry wins; only fill a missing one.
    if (JSON.stringify(existing) !== JSON.stringify(credit)) {
    }
  }

  if (checkOnly) {
    const missing = Object.keys(additions).filter((tag) => file.credits[tag] === undefined);
    if (missing.length > 0) {
      console.error(
        `emberwatch credits are incomplete — missing ${missing.length} tag(s), e.g. ${missing.slice(0, 3).join(', ')}`,
      );
      process.exit(1);
    }
    console.log('emberwatch credits are complete');
    return;
  }

  if (changed > 0) {
    writeFileSync(licensesPath, `${JSON.stringify(file, null, 2)}\n`);
  }
  console.log(
    `sync_emberwatch_credits: ${changed} credit(s) added, ${Object.keys(file.credits).length} total`,
  );
};

main();
