// apps/frontend/client/src/lib/services/image/generated_asset_workflow.ts
//
// C-512: the byte/descriptor seam between image generation and the C-510
// registry write.
//
// `imageGenerationService.generateImage` hands back a `Blob` (plus the engine
// id and seed); `registerGenerated` needs a `GeneratedAsset` descriptor and a
// `Uint8Array`. Nothing else may bridge the two: a ViewModel must never fetch a
// blob URL or touch engine transport to obtain bytes (C-512 Architecture
// Directives — "one generation path").
//
// Contract: C-512 AC-1 / AC-3 / AC-6

import { expressionAssetTag } from '@aikami/constants';
import { extForMimeType, requireRecipe, toGeneratedAsset } from '@aikami/local-ai';
import type {
  AssetRecipe,
  GeneratedAsset,
  GenerationEngineId,
  GenerationResult,
} from '@aikami/types';
import { logger } from '$logger';
import type { GeneratedAssetOutcome, GeneratedAssetSaveOutcome } from '$types';
import { assetManager } from '../assets/asset_manager.svelte.ts';
import type { RegisterGeneratedResult } from '../assets/generated_asset_registration.ts';
import { imageGenerationService } from './image_generation_service.svelte.ts';

/** What the seam needs from the image engine. */
type GeneratedAssetWorkflowDeps = {
  /** Generates bytes. `blob` is the raw engine output — never a `blob:` URL. */
  generateImage(options: {
    prompt: string;
    negativePrompt?: string;
    /**
     * Reference face as a data URL (img2img) — AC-3's "uploaded/reference
     * face". Kept as a payload, never a registry tag: the engine needs bytes.
     */
    initImage?: string;
    /** Extra reference images (character consistency). */
    referenceImages?: readonly string[];
    signal?: AbortSignal;
  }): Promise<{
    blob: Blob;
    mimeType: string;
    engineId: GenerationEngineId;
    seed?: number;
    isDemo: boolean;
  }>;
  /** The C-510 write seam (`assetManager.registerGenerated`). */
  registerGenerated(asset: GeneratedAsset, bytes: Uint8Array): Promise<RegisterGeneratedResult>;
};

/** Options for the workflow's `generate`. */
type GeneratedAssetGenerateOptions = {
  recipeId: string;
  prompt: string;
  negativePrompt?: string;
  /** Set for NPC-bound assets — drives the `expressionAssetTag` override. */
  npcId?: string;
  /** Emotion for an NPC-bound asset. Defaults to `neutral`. */
  emotion?: string;
  /** Reference face (data URL) for a consistent expression pack. */
  initImage?: string;
  /** Extra reference images (character consistency). */
  referenceImages?: readonly string[];
  /** Explicit registry tag override; wins over the NPC-bound derivation. */
  tag?: string;
  signal?: AbortSignal;
};

type GeneratedAssetWorkflow = {
  generate(options: GeneratedAssetGenerateOptions): Promise<GeneratedAssetOutcome>;
  /**
   * Registers the bytes produced by the last {@link generate} for `tag`.
   *
   * @throws Error when nothing was generated for that tag, or when the
   *         registry write fails (quota, seed collision) — the caller must
   *         surface it, never swallow it.
   */
  save(options: { tag: string }): Promise<GeneratedAssetSaveOutcome>;
  /** Revokes the preview URL and drops the pending bytes for a tag. */
  discard(tag: string): void;
  /** Revokes every pending preview URL (teardown). */
  dispose(): void;
};

/** Bounded so a long studio session cannot accumulate generated bytes. */
const MAX_PENDING_RESULTS = 8;

/**
 * Builds the seam. One instance per composition root — it holds the pending
 * generated bytes between the review step and the save.
 */
export const createGeneratedAssetWorkflow = (
  deps: GeneratedAssetWorkflowDeps,
): GeneratedAssetWorkflow => {
  const pending = new Map<
    string,
    { asset: GeneratedAsset; bytes: Uint8Array; previewUrl: string }
  >();

  const evictOldest = (): void => {
    if (pending.size < MAX_PENDING_RESULTS) {
      return;
    }
    const oldest = pending.keys().next().value;
    if (oldest !== undefined) {
      discard(oldest);
    }
  };

  const discard = (tag: string): void => {
    const entry = pending.get(tag);
    if (!entry) {
      return;
    }
    pending.delete(tag);
    try {
      URL.revokeObjectURL(entry.previewUrl);
    } catch {
      // A non-DOM environment (tests) has nothing to revoke.
    }
  };

  return {
    async generate(options: GeneratedAssetGenerateOptions): Promise<GeneratedAssetOutcome> {
      const recipe = requireRecipe(options.recipeId);
      const generated = await deps.generateImage({
        prompt: options.prompt,
        negativePrompt: options.negativePrompt,
        ...(options.initImage === undefined ? {} : { initImage: options.initImage }),
        ...(options.referenceImages === undefined
          ? {}
          : { referenceImages: options.referenceImages }),
        signal: options.signal,
      });

      const bytes = new Uint8Array(await generated.blob.arrayBuffer());
      if (bytes.length === 0) {
        throw new Error('The image engine returned an empty result');
      }

      // An engine may emit a different format than the recipe declares
      // (sd-server always returns PNG). Registering PNG bytes under a `.webp`
      // recipe would hand the renderer a MIME the bytes do not have, so the
      // seam reconciles the declared ext with what actually came back.
      const effectiveRecipe = reconcileRecipeExt(recipe, generated.mimeType);

      const tag = options.tag ?? deriveSeamTag({ recipe: effectiveRecipe, options });

      const result: GenerationResult = {
        bytes,
        mimeType: generated.mimeType,
        engine: generated.engineId,
        metadata: {
          prompt: options.prompt,
          ...(options.emotion === undefined ? {} : { emotion: options.emotion }),
          ...(options.npcId === undefined ? {} : { npcId: options.npcId }),
        },
        ...(generated.seed === undefined ? {} : { seed: generated.seed }),
      };

      const asset = await toGeneratedAsset(result, effectiveRecipe, generated.engineId, {
        prompt: options.prompt,
        tag,
      });

      discard(asset.tag);
      evictOldest();

      const previewUrl = createObjectUrl(generated.blob, generated.mimeType);
      pending.set(asset.tag, { asset, bytes, previewUrl });

      logger.debug('generated_asset_workflow:generated', {
        tag: asset.tag,
        engine: asset.engine,
        sizeBytes: bytes.length,
        ext: asset.ext,
        demo: generated.isDemo,
      });

      return {
        tag: asset.tag,
        sha256: asset.sha256,
        engine: asset.engine,
        ...(asset.seed === undefined ? {} : { seed: asset.seed }),
        sizeBytes: bytes.length,
        ext: asset.ext,
        mimeType: asset.mimeType,
        previewUrl,
        isDemo: generated.isDemo,
      };
    },

    async save(options: { tag: string }): Promise<GeneratedAssetSaveOutcome> {
      const entry = pending.get(options.tag);
      if (!entry) {
        throw new Error(
          `No generated bytes are pending for "${options.tag}" — generate before saving`,
        );
      }

      const result = await deps.registerGenerated(entry.asset, entry.bytes);

      logger.debug('generated_asset_workflow:saved', {
        tag: result.tag,
        registered: result.registered,
        version: result.version,
        unchanged: result.unchanged,
        reason: result.reason,
      });

      if (result.registered) {
        // Bytes are owned by the registry (and its cache) now — drop the preview.
        discard(options.tag);
      }

      return {
        registered: result.registered,
        tag: result.tag,
        sha256: result.sha256,
        ...(result.version === undefined ? {} : { version: result.version }),
        ...(result.unchanged === undefined ? {} : { unchanged: result.unchanged }),
        ...(result.reason === undefined ? {} : { reason: result.reason }),
      };
    },

    discard,

    dispose(): void {
      for (const tag of [...pending.keys()]) {
        discard(tag);
      }
    },
  };
};

/**
 * The resolver tag for a generate request.
 *
 * An NPC-bound portrait/expression lands on `expressionAssetTag` so the
 * runtime resolver finds it; the prompt slug `deriveTag` would produce never
 * matches the resolver's tag family (C-512 tag discipline).
 */
const deriveSeamTag = (options: {
  recipe: AssetRecipe;
  options: GeneratedAssetGenerateOptions;
}): string | undefined => {
  const { recipe, options: request } = options;
  if (!request.npcId) {
    return undefined;
  }
  if (recipe.category !== 'portraits') {
    return undefined;
  }
  return expressionAssetTag({
    npcId: request.npcId,
    emotion: request.emotion ?? 'neutral',
  });
};

/**
 * Returns the recipe with its declared ext reconciled to the engine's actual
 * MIME type, so the descriptor's ext and MIME always agree with the bytes.
 */
const reconcileRecipeExt = (recipe: AssetRecipe, mimeType: string): AssetRecipe => {
  const actualExt = extForMimeType(mimeType);
  if (actualExt === undefined || actualExt === recipe.output.ext) {
    return recipe;
  }
  logger.warn('generated_asset_workflow:ext-reconciled', {
    recipeId: recipe.id,
    declared: recipe.output.ext,
    actual: actualExt,
    mimeType,
  });
  return { ...recipe, output: { ...recipe.output, ext: actualExt } };
};

/** Object URL for the review step; falls back to a data-less blob in tests. */
const createObjectUrl = (blob: Blob, mimeType: string): string => {
  try {
    return URL.createObjectURL(blob.type ? blob : new Blob([blob], { type: mimeType }));
  } catch {
    return '';
  }
};

/**
 * The production seam: the image engine service and the C-510 registry write.
 *
 * Built here rather than in a composition because two features need the same
 * instance — the studio (review then save) and contextual generation
 * (fire-and-forget). A second instance would hold a second pending-bytes map.
 */
export const generatedAssetWorkflow: GeneratedAssetWorkflow = createGeneratedAssetWorkflow({
  generateImage: async (options) => {
    const result = await imageGenerationService.generateImage({
      prompt: options.prompt,
      ...(options.negativePrompt === undefined ? {} : { negativePrompt: options.negativePrompt }),
      ...(options.initImage === undefined ? {} : { initImage: options.initImage }),
      ...(options.signal === undefined ? {} : { signal: options.signal }),
    });
    if (!result.isDemo) {
      imageGenerationService.releaseResultUrl(result.url);
    }
    return {
      blob: result.blob,
      mimeType: result.mimeType,
      engineId: result.engineId,
      ...(result.seed === undefined ? {} : { seed: result.seed }),
      isDemo: result.isDemo,
    };
  },
  registerGenerated: (asset, bytes) => assetManager.registerGenerated(asset, bytes),
});
