// apps/frontend/pwa/src/lib/game/core/ai/prompts/character_extraction_schema.ts
//
// TypeBox schema for extracting structured character data from the DM
// conversation. Used by aiTextIntelligenceService.extractStructure() to
// guarantee the LLM output matches the PersonaData shape required by the
// game engine.
//
// Contract: C-081

import Type from 'typebox';

// ---------------------------------------------------------------------------
// Schema
// ---------------------------------------------------------------------------

/** Strict TypeBox schema for the character extraction phase. */
export const CharacterExtractionSchema = Type.Object(
  {
    name: Type.String({ minLength: 1, description: 'Character name' }),
    background: Type.String({ minLength: 1, description: 'Character background story' }),
    appearance: Type.Object(
      {
        physicalDescription: Type.String({
          minLength: 1,
          description: 'Physical description for avatar generation',
        }),
        clothing: Type.String({ minLength: 1, description: 'Clothing style and outfit' }),
      },
      { additionalProperties: false },
    ),
    abilityScores: Type.Object(
      {
        strength: Type.Integer({ minimum: 8, maximum: 18 }),
        dexterity: Type.Integer({ minimum: 8, maximum: 18 }),
        constitution: Type.Integer({ minimum: 8, maximum: 18 }),
        intelligence: Type.Integer({ minimum: 8, maximum: 18 }),
        wisdom: Type.Integer({ minimum: 8, maximum: 18 }),
        charisma: Type.Integer({ minimum: 8, maximum: 18 }),
      },
      { additionalProperties: false },
    ),
  },
  { additionalProperties: false },
);

/** Inferred TypeScript type from the schema. */
export type ExtractedCharacter = Type.Static<typeof CharacterExtractionSchema>;

// ---------------------------------------------------------------------------
// Extraction system prompt
// ---------------------------------------------------------------------------

/**
 * System prompt used during the extraction phase. Appended after the schema
 * instruction generated by aiTextIntelligenceService.
 */
export const CHARACTER_EXTRACTION_SYSTEM_PROMPT =
  `You are a Dungeon Master finalizing a character creation session.

Review the conversation history and extract the final character persona as a strictly-typed JSON object. 

Guidelines:
- Name: the character's chosen name.
- Background: a concise 2-4 sentence backstory combining species, class, origin, and personality.
- Appearance > physicalDescription: a vivid description suitable for image generation (hair, eyes, build, skin, distinctive features, race-specific traits).
- Appearance > clothing: the character's typical outfit and gear.
- Ability Scores: use the 2024 standard array (15, 14, 13, 12, 10, 8) arranged optimally for the chosen class.

Only respond with the exact JSON structure defined by the schema. Do not include markdown fences, explanations, or additional text.` as const;
