// apps/backend/cloudflare/src/lib/config_gen.ts
//
// C-455: Generate apps/frontend/hub/wrangler.jsonc from D1_DATABASES / R2_BUCKETS
// (@aikami/constants) for the production entry.
//
// wrangler.jsonc cannot be per-mode at rest — it's the base config worker/'s
// deploy rewrites per mode, same as today.
//
// Usage:
//   bun run apps/backend/cloudflare/src/lib/config_gen.ts [--check]
//
// With --check: exits zero if the generated output matches the checked-in file,
// non-zero if there's a diff (fail-closed for CI).

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { D1_DATABASES, R2_BUCKETS } from '@aikami/constants';

// From apps/backend/cloudflare/src/lib/, root is 5 levels up
const ROOT = resolve(import.meta.dir, '../../../../..');
const HUB_WRANGLER_PATH = resolve(ROOT, 'apps/frontend/hub/wrangler.jsonc');

/** Generate the production wrangler.jsonc content for the hub Worker. */
export const generateHubWranglerConfig = (): string => {
	const prodD1 = D1_DATABASES.hub.production;
	const savesBucket = R2_BUCKETS.saves.production;
	const catalogBucket = R2_BUCKETS.catalog.production;

	const config: Record<string, unknown> = {
		$schema: './node_modules/wrangler/config-schema.json',
		name: 'aikami-hub',
		compatibility_date: '2026-08-21',
		compatibility_flags: ['nodejs_compat'],
		main: 'build/_worker.js',
		assets: {
			binding: 'ASSETS',
			directory: 'build/client',
		},
		d1_databases: [
			{
				binding: prodD1.binding,
				database_name: prodD1.databaseName,
				database_id: prodD1.databaseId,
				migrations_dir: '../../packages/backend/database/drizzle-d1',
			},
		],
		r2_buckets: [
			{
				binding: savesBucket.binding,
				bucket_name: savesBucket.bucketName,
			},
		],
		routes: [
			{
				pattern: 'hub.bearlysleeping.com',
				custom_domain: true,
			},
		],
		observability: {
			enabled: true,
		},
	};

	// Add catalog bucket if different from saves
	// (cast to string to avoid as const literal type narrowing)
	if (String(catalogBucket.bucketName) !== String(savesBucket.bucketName)) {
		(config.r2_buckets as Array<Record<string, unknown>>).push({
			binding: catalogBucket.binding,
			bucket_name: catalogBucket.bucketName,
		});
	}

	// Source of truth comment
	const comment = '// Generated by apps/backend/cloudflare/src/lib/config_gen.ts from @aikami/constants\n';
	return comment + JSON.stringify(config, null, 2) + '\n';
};

/** Write the generated config to the hub's wrangler.jsonc. */
export const writeHubWranglerConfig = (): void => {
	const content = generateHubWranglerConfig();
	writeFileSync(HUB_WRANGLER_PATH, content, 'utf-8');
	console.log(`Generated ${HUB_WRANGLER_PATH}`);
};

/** Check if the generated config matches the checked-in file. Exits non-zero on diff. */
export const checkHubWranglerConfig = (): boolean => {
	const generated = generateHubWranglerConfig();
	const existing = readFileSync(HUB_WRANGLER_PATH, 'utf-8');

	if (generated === existing) {
		console.log('✅ Generated config matches checked-in file — no diff.');
		return true;
	}

	console.error('❌ Generated config DIFFERS from checked-in file:');
	const genLines = generated.split('\n');
	const existingLines = existing.split('\n');
	for (let i = 0; i < Math.max(genLines.length, existingLines.length); i++) {
		if (genLines[i] !== existingLines[i]) {
			console.error(`  Line ${i + 1}:`);
			console.error(`    expected: ${genLines[i]?.trim() ?? '(empty)'}`);
			console.error(`    actual:   ${existingLines[i]?.trim() ?? '(empty)'}`);
		}
	}
	return false;
};

// ── CLI entry ──────────────────────────────────────────────────────────

const main = (): void => {
	const isCheck = Bun.argv.includes('--check');

	if (isCheck) {
		const ok = checkHubWranglerConfig();
		process.exit(ok ? 0 : 1);
	}

	writeHubWranglerConfig();
};

const isMainModule = import.meta.path === Bun.main;
if (isMainModule) {
	main();
}
