// packages/backend/auth/src/lib/poll_device_handoff.ts

import { getFirestore } from '@aikami/backend/configs/firestore';
import type { CallableFunctionResponse } from '@aikami/types';
import { toAppError } from '@aikami/utils';
import { logger } from '$logger';

/** Codes older than this are treated as expired and never handed out. */
const HANDOFF_TTL_MS = 5 * 60 * 1000;

/**
 * Polled by a device that isn't signed in yet (the Tauri desktop app) to
 * retrieve the custom token a browser tab wrote via completeDeviceHandoff.
 *
 * Single-use: the doc is deleted as soon as it's read, whether by this poll
 * or by the deep-link-triggered call racing it — whichever asks first wins.
 * Deployed as its own unauthenticated callable (apps/backend/firebase/src/
 * controllers/callable/poll_device_handoff.ts) — deliberately NOT routed
 * through the multiplexed `auth` callable, whose shared dispatcher
 * (createApiHandler) requires a non-null caller context for every action.
 * The caller here has no session yet; codes are 128-bit random UUIDs
 * generated by the desktop app itself, not user-visible, so they aren't
 * guessable.
 */
export const pollDeviceHandoff = async (options: {
  code: string;
}): Promise<CallableFunctionResponse<'poll_device_handoff'>> => {
  const { code } = options;

  if (!code) {
    throw toAppError({
      errorType: 'invalid-argument',
      errorMessage: 'code is required for device handoff polling',
    });
  }

  const ref = getFirestore().collection('device_handoffs').doc(code);
  const snapshot = await ref.get();

  if (!snapshot.exists) {
    return { customFirebaseSignInToken: null };
  }

  // Always delete on read — an expired doc is just as single-use as a fresh one.
  await ref.delete();

  const data = snapshot.data();
  const createdAt = data?.createdAt ? new Date(data.createdAt as string).getTime() : 0;
  if (!createdAt || Date.now() - createdAt > HANDOFF_TTL_MS) {
    logger.debug('pollDeviceHandoff:expired', { code });
    return { customFirebaseSignInToken: null };
  }

  const customFirebaseSignInToken = data?.customToken as string | undefined;
  if (!customFirebaseSignInToken) {
    return { customFirebaseSignInToken: null };
  }

  logger.info('pollDeviceHandoff:resolved', { code });
  return { customFirebaseSignInToken };
};
