// apps/frontend/client/src/lib/types/gm.ts
//
// Client-local types for the GM Narrative Director system.

/**
 * Whom the GM prompt should address or scope the narrative around.
 *
 * - `'scene'`:  Omniscient narrator — describes the world (default, all-access)
 * - `'party'`:  Group-focused — addresses the player's party collectively
 * - `'gm'`:     Direct GM-to-player — 4th-wall "you notice..." style.
 *               Only available when the player has elected GM mode.
 */
export type AddressMode = 'scene' | 'party' | 'gm';

/**
 * Summary of a completed play session.
 *
 * Generated by a low-temperature LLM call at session end. Stores key
 * events, character progression, and a resume point for the next session.
 */
export type SessionSummary = {
  /** Unique summary identifier. */
  readonly id: string;
  /** Timestamp when this summary was generated. */
  readonly createdAt: number;
  /** Total playtime in minutes for this session. */
  readonly playtimeMinutes: number;
  /** Brief synopsis of the session (3–5 sentences). */
  readonly synopsis: string;
  /** Key events that occurred, ordered chronologically. */
  readonly keyEvents: ReadonlyArray<string>;
  /** Notable NPC interactions during this session. */
  readonly npcInteractions: ReadonlyArray<{
    readonly npcName: string;
    readonly context: string;
  }>;
  /** Character progression summary. */
  readonly characterProgression?: {
    readonly levelsGained: number;
    readonly itemsAcquired: ReadonlyArray<string>;
    readonly questsCompleted: ReadonlyArray<string>;
  };
  /**
   * A non-empty resume point string that allows the GameSaveService
   * to restore the game state to where the session left off.
   */
  readonly resumePoint: string;
};
