#!/usr/bin/env bun
// scripts/src/lib/deploy/updater_manifest.ts
//
// Tauri auto-updater manifest support for the desktop release pipeline.
//
// Fragments: every platform leg (build or reuse) that attaches artifacts to a
// GitHub Release emits a small JSON fragment describing its own updater
// platform entries (`<os>-<arch>` → { signature, url }). Written to
// `<cwd>/updater-fragments/<platform>.json` and uploaded as a workflow
// artifact by release.yml.
//
// Merge: the `update-manifest` job downloads every leg's fragment and runs
// `--merge` to assemble the full static manifest (version + notes + pub_date +
// platforms), then uploads it to the triggering release as `latest.json`
// (--clobber). GitHub's `releases/latest/download/latest.json` URL then always
// resolves to the newest release's manifest — no CDN or update server needed.
//
// Signature/url contract (Tauri updater static JSON):
//   - signature: the RAW content of the `.sig` file generated by `tauri build`
//     with `createUpdaterArtifacts: true`. With that config the signed artifact
//     is the AppImage / MSI / `.app.tar.gz` itself, and the `.sig` sits next to
//     it. A path or URL does NOT work — the content is the signature.
//   - url: the browser_download_url of the signed artifact on the release.
//   - platform keys: `os-arch` — `linux-x86_64`, `windows-x86_64`,
//     `darwin-x86_64`, `darwin-aarch64`. A universal macOS build is emitted
//     under BOTH `darwin-aarch64` and `darwin-x86_64` pointing at the same
//     artifact (the updater has no single "universal" key).

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { c, error, log, ok, parseCliArgs, run, warn } from '../cli_utils';
import { readCargoVersion } from './tauri_release';

// ── Types ────────────────────────────────────────────────────────────────

export type PlatformName = 'linux' | 'windows' | 'macos';

export type UpdaterPlatformEntry = {
  signature: string;
  url: string;
};

export type UpdaterFragment = Record<string, UpdaterPlatformEntry>;

export type UpdaterManifest = {
  version: string;
  notes: string;
  pub_date: string;
  platforms: UpdaterFragment;
};

// ── Constants ────────────────────────────────────────────────────────────

const PLATFORM_OS_PREFIX: Record<PlatformName, string> = {
  linux: 'linux-',
  windows: 'windows-',
  macos: 'darwin-',
} as const;

const UPDATER_SIGNED_SUFFIXES = ['.appimage', '.msi', '.exe', '.app.tar.gz'] as const;

const ARCH_TO_TAURI: Record<string, string> = {
  x64: 'x86_64',
  amd64: 'x86_64',
  x86_64: 'x86_64',
  arm64: 'aarch64',
  aarch64: 'aarch64',
  ia32: 'i686',
  x86: 'i686',
  i686: 'i686',
  arm: 'armv7',
  armv7: 'armv7',
  universal: 'universal',
} as const;

// ── Helpers ──────────────────────────────────────────────────────────────

const repoSlug = (): string => {
  if (process.env.GITHUB_REPOSITORY) {
    return process.env.GITHUB_REPOSITORY;
  }
  try {
    const remote = readFileSync(join(process.cwd(), '.git', 'config'), 'utf8');
    const match = remote.match(
      /url\s*=\s*(?:git@|https:\/\/)[^:]+[:/]([^/\s]+)\/([^/\s]+?)(?:\.git)?\s*$/m,
    );
    if (match?.[1] && match?.[2]) {
      return `${match[1]}/${match[2]}`;
    }
  } catch {
    // Fallback
  }
  return 'BearlySleeping/aikami';
};

export const releaseDownloadUrl = (releaseTag: string, assetName: string): string => {
  return `https://github.com/${repoSlug()}/releases/download/${releaseTag}/${encodeURIComponent(assetName)}`;
};

const isUpdaterSignedFile = (fileName: string): boolean => {
  const lower = fileName.toLowerCase();
  return UPDATER_SIGNED_SUFFIXES.some((suffix) => lower.endsWith(suffix));
};

export type UpdaterArtifactPair = {
  signed: string;
  signature: string;
};

export const collectUpdaterArtifacts = (paths: readonly string[]): UpdaterArtifactPair[] => {
  const byName = new Map<string, string>(paths.map((p) => [basename(p), p]));
  const pairs: UpdaterArtifactPair[] = [];
  for (const sigPath of paths) {
    if (!basename(sigPath).toLowerCase().endsWith('.sig')) {
      continue;
    }
    const signedName = basename(sigPath).slice(0, -'.sig'.length);
    if (!isUpdaterSignedFile(signedName)) {
      continue;
    }
    const signed = byName.get(signedName);
    if (!signed) {
      continue;
    }
    pairs.push({ signed, signature: readFileSync(sigPath, 'utf8').trim() });
  }
  return pairs;
};

export const deriveUpdaterPlatformKeys = (options: {
  platform: PlatformName;
  arch: string;
}): string[] => {
  const prefix = PLATFORM_OS_PREFIX[options.platform];
  if (options.platform === 'macos' && options.arch === 'universal') {
    return [`${prefix}aarch64`, `${prefix}x86_64`];
  }
  const arch = ARCH_TO_TAURI[options.arch] ?? options.arch;
  return [`${prefix}${arch}`];
};

const archFromFileName = (fileName: string): string | undefined => {
  const match = fileName.match(
    /(?:^|_)(amd64|x86_64|x64|aarch64|arm64|i686|armv7|universal)(?:_|\.)/,
  );
  return match?.[1];
};

export type FragmentBuildOptions = {
  platform: PlatformName;
  artifactPaths: readonly string[];
  releaseTag: string;
  arch?: string;
  sourceManifest?: UpdaterManifest | null;
};

export const buildPlatformFragment = (options: FragmentBuildOptions): UpdaterFragment => {
  const { platform, artifactPaths, releaseTag } = options;
  const fragment: UpdaterFragment = {};
  const pairs = collectUpdaterArtifacts(artifactPaths);
  for (const pair of pairs) {
    const keys = updaterKeysForPair({
      platform,
      pair,
      arch: options.arch,
      sourceManifest: options.sourceManifest,
    });
    const url = releaseDownloadUrl(releaseTag, basename(pair.signed));
    for (const key of keys) {
      fragment[key] = { signature: pair.signature, url };
    }
  }
  return fragment;
};

const updaterKeysForPair = (options: {
  platform: PlatformName;
  pair: UpdaterArtifactPair;
  arch?: string;
  sourceManifest?: UpdaterManifest | null;
}): string[] => {
  const { platform, pair } = options;
  const prefix = PLATFORM_OS_PREFIX[platform];

  if (options.sourceManifest) {
    const matching = Object.keys(options.sourceManifest.platforms ?? {}).filter((key) => {
      return (
        key.startsWith(prefix) &&
        options.sourceManifest?.platforms[key]?.signature === pair.signature
      );
    });
    if (matching.length > 0) {
      return matching;
    }
    warn(
      `  No source-manifest key matches the reused signature for ${basename(pair.signed)} — deriving from file name.`,
    );
  }

  const fileNameArch = archFromFileName(basename(pair.signed));
  const arch = fileNameArch ?? options.arch ?? process.arch;
  return deriveUpdaterPlatformKeys({ platform, arch });
};

export const writeFragmentFile = (platform: PlatformName, fragment: UpdaterFragment): void => {
  const dir = join(process.cwd(), 'updater-fragments');
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${platform}.json`);
  writeFileSync(file, `${JSON.stringify(fragment, null, 2)}\n`);
  if (Object.keys(fragment).length === 0) {
    warn(`  No updater artifacts for ${platform} — wrote empty fragment ${file}`);
  } else {
    log(
      `  ${c.dim}Wrote updater fragment: ${file} (${Object.keys(fragment).join(', ')})${c.reset}`,
    );
  }
};

// ── Merge mode ───────────────────────────────────────────────────────────

const collectJsonFiles = (dir: string): string[] => {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current)) {
      const full = join(current, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (entry.endsWith('.json')) {
        found.push(full);
      }
    }
  };
  walk(dir);
  return found;
};

const loadFragments = (dir: string): UpdaterFragment => {
  const merged: UpdaterFragment = {};
  const files = collectJsonFiles(dir);
  for (const file of files) {
    try {
      const parsed = JSON.parse(readFileSync(file, 'utf8')) as UpdaterFragment;
      const keyCount = Object.keys(parsed).length;
      if (keyCount === 0) {
        warn(`Fragment file ${file} is empty (zero platform keys) — skipping.`);
        continue;
      }
      Object.assign(merged, parsed);
    } catch (err) {
      warn(
        `  Skipping unreadable fragment ${file}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }
  return merged;
};

const fetchReleaseNotes = async (releaseTag: string): Promise<string> => {
  const res = await run(['gh', 'release', 'view', releaseTag, '--json', 'body', '--jq', '.body']);
  if (res.code !== 0) {
    warn(`  gh release view ${releaseTag} failed: ${res.err || res.out}`);
    return '';
  }
  return res.out;
};

const uploadManifest = async (releaseTag: string, manifestPath: string): Promise<void> => {
  const res = await run(['gh', 'release', 'upload', releaseTag, manifestPath, '--clobber']);
  if (res.code !== 0) {
    throw new Error(`gh release upload ${releaseTag} failed: ${res.err || res.out}`);
  }
};

async function main(): Promise<void> {
  const opts = parseCliArgs(Bun.argv.slice(2), {
    merge: { type: 'boolean' },
    'fragments-dir': { type: 'string' },
    'release-tag': { type: 'string' },
    'tauri-dir': { type: 'string' },
  });

  if (!opts.merge) {
    error('No mode specified — updater_manifest.ts only supports --merge.');
    process.exit(1);
  }

  const fragmentsDir = opts['fragments-dir'] ?? 'updater-fragments-merged';
  const releaseTag = opts['release-tag'] ?? process.env.RELEASE_TAG ?? '';
  if (!releaseTag) {
    error('--release-tag (or RELEASE_TAG) is required for merge mode.');
    process.exit(1);
  }

  log(`\n${c.bold}📋 Building update manifest for ${c.cyan}${releaseTag}${c.reset}`);

  const platforms = loadFragments(fragmentsDir);
  const platformKeyCount = Object.keys(platforms).length;
  if (platformKeyCount === 0) {
    error(
      `No valid platform fragments found under ${fragmentsDir} — refusing to upload an empty manifest.`,
    );
    process.exit(1);
  }

  const tauriDir = opts['tauri-dir'] ?? 'apps/frontend/client/src-tauri';
  const manifest: UpdaterManifest = {
    version: readCargoVersion(tauriDir),
    notes: await fetchReleaseNotes(releaseTag),
    pub_date: new Date().toISOString(),
    platforms,
  };

  const manifestPath = join(process.cwd(), 'latest.json');
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  ok(`Merged ${platformKeyCount} platform key(s) into ${manifestPath}`);
  log(`  version:  ${manifest.version}`);
  log(`  pub_date: ${manifest.pub_date}`);

  await uploadManifest(releaseTag, manifestPath);
  ok(`Uploaded latest.json to release ${releaseTag} (--clobber)`);
}

if (import.meta.main) {
  await main();
}
