#!/usr/bin/env bun
// scripts/src/lib/deploy/updater_manifest.ts
//
// Tauri auto-updater manifest support for the desktop release pipeline.
//
// Fragments: every platform leg (build or reuse) that attaches artifacts to a
// GitHub Release emits a small JSON fragment describing its own updater
// platform entries (`<os>-<arch>` → { signature, url }). Written to
// `<cwd>/updater-fragments/<platform>.json` and uploaded as a workflow
// artifact by release.yml.
//
// Merge: the `update-manifest` job downloads every leg's fragment and runs
// `--merge` to assemble the full static manifest (version + notes + pub_date +
// platforms), then uploads it to the triggering release as `latest.json`
// (--clobber). GitHub's `releases/latest/download/latest.json` URL then always
// resolves to the newest release's manifest — no CDN or update server needed.
//
// Signature/url contract (Tauri updater static JSON):
//   - signature: the RAW content of the `.sig` file generated by `tauri build`
//     with `createUpdaterArtifacts: true`. With that config the signed artifact
//     is the AppImage / MSI / `.app.tar.gz` itself, and the `.sig` sits next to
//     it. A path or URL does NOT work — the content is the signature.
//   - url: the browser_download_url of the signed artifact on the release.
//   - platform keys: `os-arch` — `linux-x86_64`, `windows-x86_64`,
//     `darwin-x86_64`, `darwin-aarch64`. A universal macOS build is emitted
//     under BOTH `darwin-aarch64` and `darwin-x86_64` pointing at the same
//     artifact (the updater has no single "universal" key).

import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { c, error, log, ok, parseCliArgs, run, warn } from '../cli_utils';
import { readCargoVersion } from './tauri_release';

// ── Types ────────────────────────────────────────────────────────────────

export type PlatformName = 'linux' | 'windows' | 'macos';

/** One platform entry of the static updater manifest. */
export type UpdaterPlatformEntry = {
  /** Raw content of the .sig file (not a path or URL). */
  signature: string;
  /** browser_download_url of the signed artifact on the release. */
  url: string;
};

/** `os-arch` → platform entry (e.g. `{ "windows-x86_64": { … } }`). */
export type UpdaterFragment = Record<string, UpdaterPlatformEntry>;

/** Full static manifest consumed by tauri-plugin-updater. */
export type UpdaterManifest = {
  version: string;
  notes: string;
  pub_date: string;
  platforms: UpdaterFragment;
};

// ── Constants ────────────────────────────────────────────────────────────

const PLATFORM_OS_PREFIX: Record<PlatformName, string> = {
  linux: 'linux-',
  windows: 'windows-',
  macos: 'darwin-',
} as const;

/** Signed updater artifacts produced by `createUpdaterArtifacts: true`. */
const UPDATER_SIGNED_SUFFIXES = ['.appimage', '.msi', '.exe', '.app.tar.gz'] as const;

/** File-name arch tokens (from Tauri artifact names) and Node arch → Tauri arch. */
const ARCH_TO_TAURI: Record<string, string> = {
  x64: 'x86_64',
  amd64: 'x86_64',
  x86_64: 'x86_64',
  arm64: 'aarch64',
  aarch64: 'aarch64',
  ia32: 'i686',
  x86: 'i686',
  i686: 'i686',
  arm: 'armv7',
  armv7: 'armv7',
  universal: 'universal',
} as const;

// ── Helpers ──────────────────────────────────────────────────────────────

/**
 * Resolve `<owner>/<repo>` from the GitHub Actions context, then the git
 * remote, then a hardcoded fallback. Used to build artifact download URLs.
 */
const repoSlug = (): string => {
  if (process.env.GITHUB_REPOSITORY) {
    return process.env.GITHUB_REPOSITORY;
  }
  try {
    const remote = readFileSync(join(process.cwd(), '.git', 'config'), 'utf8');
    const match = remote.match(
      /url\s*=\s*(?:git@|https:\/\/)[^:]+[:/]([^/\s]+)\/([^/\s]+?)(?:\.git)?\s*$/m,
    );
    if (match?.[1] && match?.[2]) {
      return `${match[1]}/${match[2]}`;
    }
  } catch {
    // Fall through to the hardcoded default.
  }
  return 'BearlySleeping/aikami';
};

/** browser_download_url for a release asset. */
export const releaseDownloadUrl = (releaseTag: string, assetName: string): string => {
  return `https://github.com/${repoSlug()}/releases/download/${releaseTag}/${encodeURIComponent(assetName)}`;
};

/** True when a file name identifies an updater-relevant signed artifact. */
const isUpdaterSignedFile = (fileName: string): boolean => {
  const lower = fileName.toLowerCase();
  return UPDATER_SIGNED_SUFFIXES.some((suffix) => lower.endsWith(suffix));
};

export type UpdaterArtifactPair = {
  /** Path to the signed artifact (the file the `.sig` verifies). */
  signed: string;
  /** Raw `.sig` file content. */
  signature: string;
};

/**
 * Map every `.sig` file in `paths` to the artifact it signs (`<file>.sig` →
 * `<file>`), keeping only updater-relevant signed files whose artifact is
 * also present (deb/rpm/dmg signatures are ignored — the updater never
 * consumes them).
 */
export const collectUpdaterArtifacts = (paths: readonly string[]): UpdaterArtifactPair[] => {
  const byName = new Map<string, string>(paths.map((p) => [basename(p), p]));
  const pairs: UpdaterArtifactPair[] = [];
  for (const sigPath of paths) {
    if (!basename(sigPath).toLowerCase().endsWith('.sig')) {
      continue;
    }
    const signedName = basename(sigPath).slice(0, -'.sig'.length);
    if (!isUpdaterSignedFile(signedName)) {
      continue;
    }
    const signed = byName.get(signedName);
    if (!signed) {
      continue;
    }
    pairs.push({ signed, signature: readFileSync(sigPath, 'utf8').trim() });
  }
  return pairs;
};

/**
 * Tauri updater platform key(s) for a platform + arch. A universal macOS
 * build is emitted under BOTH `darwin-aarch64` and `darwin-x86_64` — there is
 * no single combined key (see tauri-action's upload-version-json.ts).
 */
export const deriveUpdaterPlatformKeys = (options: {
  platform: PlatformName;
  arch: string;
}): string[] => {
  const prefix = PLATFORM_OS_PREFIX[options.platform];
  if (options.platform === 'macos' && options.arch === 'universal') {
    return [`${prefix}aarch64`, `${prefix}x86_64`];
  }
  const arch = ARCH_TO_TAURI[options.arch] ?? options.arch;
  return [`${prefix}${arch}`];
};

/** Arch token embedded in a Tauri artifact file name, if any. */
const archFromFileName = (fileName: string): string | undefined => {
  const match = fileName.match(
    /(?:^|_)(amd64|x86_64|x64|aarch64|arm64|i686|armv7|universal)(?:_|\.)/,
  );
  return match?.[1];
};

export type FragmentBuildOptions = {
  /** Leg platform (linux / windows / macos). */
  platform: PlatformName;
  /** Paths of the leg's artifacts (build leg) or downloaded files (reuse leg). */
  artifactPaths: readonly string[];
  /** Release tag the fragment's URLs point at. */
  releaseTag: string;
  /** Arch token for the build host; defaults to process.arch. */
  arch?: string;
  /**
   * Source release manifest (reuse legs only): its platform keys are reused
   * verbatim for matching signatures so a copied-forward artifact keeps the
   * exact keys it was originally built with (e.g. both darwin keys for a
   * universal build). Ignored when the source release predates the updater.
   */
  sourceManifest?: UpdaterManifest | null;
};

/**
 * Build the updater fragment for one platform leg: every signed updater
 * artifact found in `artifactPaths` becomes one or more `<os>-<arch>` entries
 * pointing at this release.
 */
export const buildPlatformFragment = (options: FragmentBuildOptions): UpdaterFragment => {
  const { platform, artifactPaths, releaseTag } = options;
  const fragment: UpdaterFragment = {};
  const pairs = collectUpdaterArtifacts(artifactPaths);
  for (const pair of pairs) {
    const keys = updaterKeysForPair({
      platform,
      pair,
      arch: options.arch,
      sourceManifest: options.sourceManifest,
    });
    const url = releaseDownloadUrl(releaseTag, basename(pair.signed));
    for (const key of keys) {
      fragment[key] = { signature: pair.signature, url };
    }
  }
  return fragment;
};

const updaterKeysForPair = (options: {
  platform: PlatformName;
  pair: UpdaterArtifactPair;
  arch?: string;
  sourceManifest?: UpdaterManifest | null;
}): string[] => {
  const { platform, pair } = options;
  const prefix = PLATFORM_OS_PREFIX[platform];

  // Reuse legs: prefer the source release's own keys (authoritative for arch
  // and universal builds) when a signature matches verbatim.
  if (options.sourceManifest) {
    const matching = Object.keys(options.sourceManifest.platforms ?? {}).filter((key) => {
      return (
        key.startsWith(prefix) &&
        options.sourceManifest?.platforms[key]?.signature === pair.signature
      );
    });
    if (matching.length > 0) {
      return matching;
    }
    warn(
      `  No source-manifest key matches the reused signature for ${basename(pair.signed)} — deriving from file name.`,
    );
  }

  const fileNameArch = archFromFileName(basename(pair.signed));
  const arch = fileNameArch ?? options.arch ?? process.arch;
  return deriveUpdaterPlatformKeys({ platform, arch });
};

/** Write a leg's fragment to `<cwd>/updater-fragments/<platform>.json`. */
export const writeFragmentFile = (platform: PlatformName, fragment: UpdaterFragment): void => {
  const dir = join(process.cwd(), 'updater-fragments');
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${platform}.json`);
  writeFileSync(file, `${JSON.stringify(fragment, null, 2)}\n`);
  if (Object.keys(fragment).length === 0) {
    warn(`  No updater artifacts for ${platform} — wrote empty fragment ${file}`);
  } else {
    log(
      `  ${c.dim}Wrote updater fragment: ${file} (${Object.keys(fragment).join(', ')})${c.reset}`,
    );
  }
};

// ── Merge mode (update-manifest job) ─────────────────────────────────────

const collectJsonFiles = (dir: string): string[] => {
  const found: string[] = [];
  const walk = (current: string): void => {
    for (const entry of readdirSync(current)) {
      const full = join(current, entry);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else if (entry.endsWith('.json')) {
        found.push(full);
      }
    }
  };
  walk(dir);
  return found;
};

const loadFragments = (dir: string): UpdaterFragment => {
  const merged: UpdaterFragment = {};
  const files = collectJsonFiles(dir);
  for (const file of files) {
    try {
      const parsed = JSON.parse(readFileSync(file, 'utf8')) as UpdaterFragment;
      Object.assign(merged, parsed);
    } catch (err) {
      warn(
        `  Skipping unreadable fragment ${file}: ${err instanceof Error ? err.message : String(err)}`,
      );
    }
  }
  return merged;
};

const fetchReleaseNotes = async (releaseTag: string): Promise<string> => {
  const res = await run(['gh', 'release', 'view', releaseTag, '--json', 'body', '--jq', '.body']);
  if (res.code !== 0) {
    warn(`  gh release view ${releaseTag} failed: ${res.err || res.out}`);
    return '';
  }
  return res.out;
};

const uploadManifest = async (releaseTag: string, manifestPath: string): Promise<void> => {
  const res = await run(['gh', 'release', 'upload', releaseTag, manifestPath, '--clobber']);
  if (res.code !== 0) {
    throw new Error(`gh release upload ${releaseTag} failed: ${res.err || res.out}`);
  }
};

async function main(): Promise<void> {
  const opts = parseCliArgs(Bun.argv.slice(2), {
    merge: { type: 'boolean' },
    'fragments-dir': { type: 'string' },
    'release-tag': { type: 'string' },
    'tauri-dir': { type: 'string' },
  });

  if (!opts.merge) {
    error('No mode specified — updater_manifest.ts only supports --merge.');
    process.exit(1);
  }

  const fragmentsDir = opts['fragments-dir'] ?? 'updater-fragments-merged';
  const releaseTag = opts['release-tag'] ?? process.env.RELEASE_TAG ?? '';
  if (!releaseTag) {
    error('--release-tag (or RELEASE_TAG) is required for merge mode.');
    process.exit(1);
  }

  log(`\n${c.bold}📋 Building update manifest for ${c.cyan}${releaseTag}${c.reset}`);

  const platforms = loadFragments(fragmentsDir);
  const platformKeyCount = Object.keys(platforms).length;
  if (platformKeyCount === 0) {
    error(
      `No platform fragments found under ${fragmentsDir} — refusing to upload an empty manifest.`,
    );
    process.exit(1);
  }

  // A missing platform key just means that platform's users see no update
  // this release (same as always, until a future release rebuilds it) — it
  // does NOT justify withholding the manifest from platforms that DID build
  // successfully. One flaky Windows/macOS runner shouldn't block Linux users
  // (or vice versa) from getting notified. Still uploads below; the process
  // exits non-zero at the end so the job shows red and gets investigated —
  // loud for the maintainer, invisible to unaffected users.
  const requiredPlatforms = ['linux-x86_64', 'windows-x86_64', 'darwin-x86_64', 'darwin-aarch64'];
  const missingPlatforms = requiredPlatforms.filter((key) => !platforms[key]);
  if (missingPlatforms.length > 0) {
    warn(
      `Missing platform fragment(s): ${missingPlatforms.join(', ')} — publishing a PARTIAL manifest anyway. Those platforms won't see this update until a future release rebuilds them.`,
    );
  }

  const tauriDir = opts['tauri-dir'] ?? 'apps/frontend/client/src-tauri';
  const manifest: UpdaterManifest = {
    // Cargo.toml version — no leading 'v'. Must be bumped per release for
    // the updater to detect a newer build.
    version: readCargoVersion(tauriDir),
    notes: await fetchReleaseNotes(releaseTag),
    pub_date: new Date().toISOString(),
    platforms,
  };

  const manifestPath = join(process.cwd(), 'latest.json');
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  ok(`Merged ${platformKeyCount} platform key(s) into ${manifestPath}`);
  log(`  version:  ${manifest.version}`);
  log(`  pub_date: ${manifest.pub_date}`);

  await uploadManifest(releaseTag, manifestPath);
  ok(`Uploaded latest.json to release ${releaseTag} (--clobber)`);

  if (missingPlatforms.length > 0) {
    error(
      `Manifest published, but missing ${missingPlatforms.length} platform(s): ${missingPlatforms.join(', ')} — re-run the missing leg(s) and re-publish.`,
    );
    process.exit(1);
  }
}

// Only run the CLI when invoked directly — this module is also imported by
// ci_run.ts / tauri_release.ts for the fragment helpers.
if (import.meta.main) {
  await main();
}
