// apps/backend/image/scripts/generate_asset.ts
/** biome-ignore-all lint/suspicious/noConsole: CLI script — console is the interface */
// Engine-agnostic asset generation CLI (C-510).
//
// One command, no transport code: resolve a recipe, dispatch to the shared
// `GenerationEngineClient` in @aikami/local-ai, derive the shared
// `GeneratedAsset` descriptor, and write catalog-ready staging output.
//
// The staging directory holds:
//   <out>/<category>/<name><ext>   the generated bytes
//   <out>/manifest.json            AssetManifest fragment (merged across runs)
//   <out>/hashes.json              AssetHashesFile fragment (merged across runs)
//   <out>/generated_asset.json     the GeneratedAsset descriptor
//
// Both fragments are consumable by scripts/src/lib/ops/generate_asset_seed.ts
// without hand-editing.
//
// Usage:
//   bun run --cwd apps/backend/image generate:asset prop "rusty iron gate"
//   bun run --cwd apps/backend/image generate:asset portrait "elven ranger" \
//     --engine sdcpp --seed 42 --steps 20 --cfg 7 --width 512 --height 512
//
// The bare root form `bun run generate:asset` fails — the script is declared in
// apps/backend/image/package.json, not the root manifest.
//
// Contract: C-510 Engine-Agnostic Asset Generation Pipeline

import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { runAssetGeneration } from '@aikami/local-ai';
import type { AssetHashesFile, AssetManifest, GenerationEngineId } from '@aikami/types';

/** Default engine endpoint — the local-stack `image` compose profile. */
const SD_SERVER = 'http://127.0.0.1:8188';

/** Default staging directory (gitignored — `src/output` is scratch space). */
const DEFAULT_OUT_DIR = resolve(import.meta.dir, '../src/output/generated');

/**
 * Default poll deadline in seconds. sd-server is CPU-only: a 512×512/20-step
 * job measured ~140s, so anything near that has no headroom. Matches the
 * pre-C-510 `generate:avatar --timeout` default.
 */
const DEFAULT_TIMEOUT_SECONDS = 900;

const MANIFEST_FILENAME = 'manifest.json';
const HASHES_FILENAME = 'hashes.json';
const DESCRIPTOR_FILENAME = 'generated_asset.json';

/** Parsed CLI arguments. */
type CliOptions = {
  recipeId: string;
  prompt: string;
  engine?: GenerationEngineId;
  baseUrl: string;
  outDir: string;
  model?: string;
  negativePrompt?: string;
  width?: number;
  height?: number;
  steps?: number;
  cfgScale?: number;
  seed?: number;
  /** Poll deadline in seconds. Defaults to the shared engine's 900s CPU budget. */
  timeoutSeconds: number;
};

const readFlag = (args: readonly string[], flag: string): string | undefined => {
  const index = args.indexOf(flag);
  if (index === -1) {
    return undefined;
  }
  const value = args[index + 1];
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
};

const readNumberFlag = (
  args: readonly string[],
  flag: string,
  parse: (raw: string) => number,
): number | undefined => {
  const raw = readFlag(args, flag);
  if (raw === undefined) {
    return undefined;
  }
  const value = parse(raw);
  if (!Number.isFinite(value)) {
    throw new Error(`${flag} must be a finite number (got "${raw}")`);
  }
  return value;
};

/** Flags this CLI understands — used to separate positionals from values. */
const KNOWN_FLAGS = new Set([
  '--engine',
  '--base-url',
  '--out',
  '--model',
  '--checkpoint',
  '--negative',
  '--width',
  '--height',
  '--steps',
  '--cfg',
  '--seed',
  '--timeout',
]);

const parseOptions = (): CliOptions => {
  const args = process.argv.slice(2);

  // Walk the argv once: a known flag consumes the next token as its value,
  // anything else that is not a flag is positional.
  const positionals: string[] = [];
  for (let index = 0; index < args.length; index++) {
    const arg = args[index] as string;
    if (KNOWN_FLAGS.has(arg)) {
      index++;
      continue;
    }
    if (arg.startsWith('--')) {
      throw new Error(`Unknown flag "${arg}"`);
    }
    positionals.push(arg);
  }

  const recipeId = positionals[0];
  const prompt = positionals[1];

  if (!recipeId || !prompt) {
    throw new Error(
      'Usage: bun run generate:asset <recipe> "<prompt>" [--engine sdcpp|comfyui] [--seed N] [--steps N] [--cfg N] [--width N] [--height N] [--model ID] [--timeout SECONDS] [--out DIR]',
    );
  }

  const engineRaw = readFlag(args, '--engine');
  if (engineRaw !== undefined && engineRaw !== 'sdcpp' && engineRaw !== 'comfyui') {
    throw new Error(`--engine must be "sdcpp" or "comfyui" (got "${engineRaw}")`);
  }

  const outRaw = readFlag(args, '--out');

  const timeoutRaw = readFlag(args, '--timeout');
  let timeoutSeconds = DEFAULT_TIMEOUT_SECONDS;
  if (timeoutRaw !== undefined) {
    if (!/^[+]?[0-9]+$/.test(timeoutRaw) || Number.parseInt(timeoutRaw, 10) <= 0) {
      throw new Error(
        `--timeout must be a positive integer number of seconds (got "${timeoutRaw}")`,
      );
    }
    timeoutSeconds = Number.parseInt(timeoutRaw, 10);
  }

  return {
    recipeId,
    prompt,
    engine: engineRaw,
    baseUrl: readFlag(args, '--base-url') ?? SD_SERVER,
    outDir: outRaw ? resolve(outRaw) : DEFAULT_OUT_DIR,
    model: readFlag(args, '--model') ?? readFlag(args, '--checkpoint'),
    negativePrompt: readFlag(args, '--negative'),
    width: readNumberFlag(args, '--width', (raw) => Number.parseInt(raw, 10)),
    height: readNumberFlag(args, '--height', (raw) => Number.parseInt(raw, 10)),
    steps: readNumberFlag(args, '--steps', (raw) => Number.parseInt(raw, 10)),
    cfgScale: readNumberFlag(args, '--cfg', (raw) => Number.parseFloat(raw)),
    seed: readNumberFlag(args, '--seed', (raw) => Number.parseInt(raw, 10)),
    timeoutSeconds,
  };
};

/** Reads a JSON fragment written by a previous run, or undefined when absent. */
const readJson = <T>(path: string): T | undefined => {
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as T;
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return undefined;
    }
    throw error;
  }
};

const main = async (): Promise<void> => {
  const options = parseOptions();

  console.log('🎨 generate:asset (C-510)\n');
  console.log(`  Recipe:  ${options.recipeId}`);
  console.log(`  Prompt:  ${options.prompt}`);
  console.log(`  Engine:  ${options.engine ?? '(recipe default)'}`);
  console.log(`  Timeout: ${options.timeoutSeconds}s`);
  console.log(`  Out:     ${options.outDir}\n`);

  const staging = await runAssetGeneration({
    recipeId: options.recipeId,
    prompt: options.prompt,
    engineId: options.engine,
    baseUrl: options.baseUrl,
    queueWaitMs: options.timeoutSeconds * 1000,
    overrides: {
      model: options.model,
      negativePrompt: options.negativePrompt,
      width: options.width,
      height: options.height,
      steps: options.steps,
      cfgScale: options.cfgScale,
      seed: options.seed,
    },
    onProgress: (progress) => {
      process.stdout.write(
        `\r  ${progress.label} ${Math.round(progress.fraction * 100)}%          `,
      );
    },
  });

  process.stdout.write('\n');

  const entry = staging.manifest.assets[staging.descriptor.tag];
  if (!entry) {
    // Unreachable by construction — asserted so a silent drop can never ship.
    throw new Error(
      `Internal error: no manifest entry produced for tag "${staging.descriptor.tag}"`,
    );
  }

  const assetPath = join(options.outDir, entry.path);
  mkdirSync(dirname(assetPath), { recursive: true });
  await Bun.write(assetPath, staging.bytes);

  // Merge into the existing staging fragments so repeated runs accumulate.
  const existingManifest = readJson<AssetManifest>(join(options.outDir, MANIFEST_FILENAME));
  const manifest: AssetManifest = existingManifest
    ? {
        ...existingManifest,
        scannedAt: staging.manifest.scannedAt,
        assets: { ...existingManifest.assets, ...staging.manifest.assets },
        byCategory: { ...existingManifest.byCategory },
      }
    : staging.manifest;
  if (existingManifest) {
    const categoryEntries = manifest.byCategory[staging.descriptor.category] ?? [];
    manifest.byCategory[staging.descriptor.category] = [
      ...categoryEntries.filter((existing) => existing.tag !== staging.descriptor.tag),
      entry,
    ];
  }
  manifest.count = Object.keys(manifest.assets).length;
  await Bun.write(join(options.outDir, MANIFEST_FILENAME), JSON.stringify(manifest, null, 2));

  const existingHashes = readJson<AssetHashesFile>(join(options.outDir, HASHES_FILENAME));
  const hashes: AssetHashesFile = existingHashes
    ? {
        scannedAt: staging.hashes.scannedAt,
        hashes: { ...existingHashes.hashes, ...staging.hashes.hashes },
      }
    : staging.hashes;
  await Bun.write(join(options.outDir, HASHES_FILENAME), JSON.stringify(hashes, null, 2));

  await Bun.write(
    join(options.outDir, DESCRIPTOR_FILENAME),
    JSON.stringify(staging.descriptor, null, 2),
  );

  console.log(`✓ ${entry.path}  ${(staging.descriptor.sizeBytes / 1024).toFixed(1)}KB`);
  console.log(`  tag:        ${staging.descriptor.tag}`);
  console.log(`  category:   ${staging.descriptor.category}`);
  console.log(`  sha256:     ${staging.descriptor.sha256}`);
  console.log(`  provenance: ${staging.descriptor.provenance.source}`);
  if (staging.descriptor.seed !== undefined) {
    console.log(`  seed:       ${staging.descriptor.seed}`);
  }
  console.log(`\nStaged in: ${options.outDir}`);
  console.log('  manifest.json + hashes.json are consumable by generate_asset_seed.ts');
};

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`\n✗ ${message}`);
  process.exit(1);
});
