// apps/backend/image/scripts/generate_asset.ts
/** biome-ignore-all lint/suspicious/noConsole: CLI script — console is the interface */
// Engine-agnostic asset generation CLI (C-510, extended for audio in C-511).
//
// One command, no transport code: resolve a recipe, dispatch to the shared
// `GenerationEngineClient` in @aikami/local-ai, derive the shared
// `GeneratedAsset` descriptor, and write catalog-ready staging output.
//
// The staging directory holds:
//   <out>/<category>/<name><ext>   the generated bytes
//   <out>/manifest.json            AssetManifest fragment (merged across runs)
//   <out>/hashes.json              AssetHashesFile fragment (merged across runs)
//   <out>/generated_asset.json     the GeneratedAsset descriptor
//
// Both fragments are consumable by scripts/src/lib/ops/generate_asset_seed.ts
// without hand-editing.
//
// Usage:
//   bun run --cwd apps/backend/image generate:asset prop "rusty iron gate"
//   bun run --cwd apps/backend/image generate:asset portrait "elven ranger" \
//     --engine sdcpp --seed 42 --steps 20 --cfg 7 --width 512 --height 512
//   bun run --cwd apps/backend/image generate:asset music "calm forest loop"
//   bun run --cwd apps/backend/image generate:asset sfx "metal gate slam" --duration 3
//
// The bare root form `bun run generate:asset` fails — the script is declared in
// apps/backend/image/package.json, not the root manifest.
//
// Contract: C-510 Engine-Agnostic Asset Generation Pipeline
// Contract: C-511 Local Audio Generation Modality

import { mkdirSync, readFileSync } from 'node:fs';
import { basename, dirname, join, resolve } from 'node:path';
import { EMULATOR_PORTS } from '@aikami/constants';
import { type ArtifactReader, requireRecipe, runAssetGeneration } from '@aikami/local-ai';
import type { AssetHashesFile, AssetManifest, GenerationEngineId } from '@aikami/types';

/** Default image engine endpoint — the local-stack `image` compose profile. */
const SD_SERVER = 'http://127.0.0.1:8188';

/** Default audio engine endpoint — the local-stack `audio` compose profile. */
const ACE_STEP_SERVER = `http://127.0.0.1:${EMULATOR_PORTS.audio}`;

/** Checkpoint directory as seen by the ACE-Step container. */
const DEFAULT_ACE_STEP_CHECKPOINT = '/models/audio/ace-step-v1-3.5b';

/** Output directory as seen by the ACE-Step container. */
const DEFAULT_ACE_STEP_OUTPUT_DIR = '/models/audio/output';

/** Default staging directory (gitignored — `src/output` is scratch space). */
const DEFAULT_OUT_DIR = resolve(import.meta.dir, '../src/output/generated');

/**
 * Default poll deadline in seconds. sd-server is CPU-only: a 512×512/20-step
 * job measured ~140s, so anything near that has no headroom. Matches the
 * pre-C-510 `generate:avatar --timeout` default.
 */
const DEFAULT_TIMEOUT_SECONDS = 900;

/**
 * Default poll deadline for the audio engine. ACE-Step's `/generate` is a
 * single synchronous request and a 60-second track on a GPU takes tens of
 * seconds — the deadline is the HTTP budget, so give it room.
 */
const DEFAULT_AUDIO_TIMEOUT_SECONDS = 1800;

const MANIFEST_FILENAME = 'manifest.json';
const HASHES_FILENAME = 'hashes.json';
const DESCRIPTOR_FILENAME = 'generated_asset.json';

const ENGINES: readonly GenerationEngineId[] = ['sdcpp', 'comfyui', 'ace-step'];

/** Parsed CLI arguments. */
type CliOptions = {
  recipeId: string;
  prompt: string;
  engine?: GenerationEngineId;
  baseUrl?: string;
  outDir: string;
  model?: string;
  negativePrompt?: string;
  width?: number;
  height?: number;
  steps?: number;
  cfgScale?: number;
  seed?: number;
  /** C-511 audio overrides. */
  durationSeconds?: number;
  tags?: string;
  lyrics?: string;
  bpm?: number;
  key?: string;
  instrumental?: boolean;
  /** ACE-Step engine wiring (C-511). */
  audioUrl?: string;
  audioCheckpoint: string;
  audioOutputDir: string;
  audioOutputMount?: string;
  /** Poll deadline in seconds. Defaults to the shared engine's 900s CPU budget. */
  timeoutSeconds?: number;
};

/** Flags that take no value — they must not consume the next token. */
const BOOLEAN_FLAGS = new Set(['--instrumental', '--no-instrumental']);

/** Flags this CLI understands — used to separate positionals from values. */
const KNOWN_FLAGS = new Set([
  '--engine',
  '--base-url',
  '--out',
  '--model',
  '--checkpoint',
  '--negative',
  '--width',
  '--height',
  '--steps',
  '--cfg',
  '--seed',
  '--timeout',
  // C-511 audio
  '--duration',
  '--tags',
  '--lyrics',
  '--bpm',
  '--key',
  '--audio-url',
  '--audio-checkpoint',
  '--audio-output-dir',
  '--audio-output-mount',
  ...BOOLEAN_FLAGS,
]);

const readFlag = (args: readonly string[], flag: string): string | undefined => {
  const index = args.indexOf(flag);
  if (index === -1) {
    return undefined;
  }
  const value = args[index + 1];
  if (value === undefined || value.startsWith('--')) {
    throw new Error(`${flag} requires a value`);
  }
  return value;
};

const readNumberFlag = (
  args: readonly string[],
  flag: string,
  parse: (raw: string) => number,
): number | undefined => {
  const raw = readFlag(args, flag);
  if (raw === undefined) {
    return undefined;
  }
  const value = parse(raw);
  if (!Number.isFinite(value)) {
    throw new Error(`${flag} must be a finite number (got "${raw}")`);
  }
  return value;
};

const parseOptions = (): CliOptions => {
  const args = process.argv.slice(2);

  // Walk the argv once: a known flag consumes the next token as its value,
  // anything else that is not a flag is positional.
  const positionals: string[] = [];
  for (let index = 0; index < args.length; index++) {
    const arg = args[index] as string;
    if (KNOWN_FLAGS.has(arg)) {
      if (!BOOLEAN_FLAGS.has(arg)) {
        index++;
      }
      continue;
    }
    if (arg.startsWith('--')) {
      throw new Error(`Unknown flag "${arg}"`);
    }
    positionals.push(arg);
  }

  const recipeId = positionals[0];
  const prompt = positionals[1];

  if (!recipeId || !prompt) {
    throw new Error(
      'Usage: bun run generate:asset <recipe> "<prompt>" [--engine sdcpp|comfyui|ace-step] [--seed N] [--steps N] [--cfg N] [--width N] [--height N] [--model ID] [--timeout SECONDS] [--out DIR] [--duration SECONDS] [--tags T] [--lyrics L] [--bpm N] [--key K] [--instrumental|--no-instrumental] [--audio-url URL] [--audio-checkpoint DIR] [--audio-output-dir DIR] [--audio-output-mount DIR]',
    );
  }

  const engineRaw = readFlag(args, '--engine');
  if (engineRaw !== undefined && !ENGINES.includes(engineRaw as GenerationEngineId)) {
    throw new Error(`--engine must be "sdcpp", "comfyui" or "ace-step" (got "${engineRaw}")`);
  }

  const outRaw = readFlag(args, '--out');

  const timeoutRaw = readFlag(args, '--timeout');
  let timeoutSeconds: number | undefined;
  if (timeoutRaw !== undefined) {
    if (!/^[+]?[0-9]+$/.test(timeoutRaw) || Number.parseInt(timeoutRaw, 10) <= 0) {
      throw new Error(
        `--timeout must be a positive integer number of seconds (got "${timeoutRaw}")`,
      );
    }
    timeoutSeconds = Number.parseInt(timeoutRaw, 10);
  }

  const modelsPath = process.env.MODELS_PATH?.trim();
  const audioOutputMount =
    readFlag(args, '--audio-output-mount') ??
    (modelsPath ? join(modelsPath, 'audio/output') : undefined);

  const instrumental = args.includes('--instrumental')
    ? true
    : args.includes('--no-instrumental')
      ? false
      : undefined;

  return {
    recipeId,
    prompt,
    engine: engineRaw as GenerationEngineId | undefined,
    baseUrl: readFlag(args, '--base-url'),
    outDir: outRaw ? resolve(outRaw) : DEFAULT_OUT_DIR,
    model: readFlag(args, '--model') ?? readFlag(args, '--checkpoint'),
    negativePrompt: readFlag(args, '--negative'),
    width: readNumberFlag(args, '--width', (raw) => Number.parseInt(raw, 10)),
    height: readNumberFlag(args, '--height', (raw) => Number.parseInt(raw, 10)),
    steps: readNumberFlag(args, '--steps', (raw) => Number.parseInt(raw, 10)),
    cfgScale: readNumberFlag(args, '--cfg', (raw) => Number.parseFloat(raw)),
    seed: readNumberFlag(args, '--seed', (raw) => Number.parseInt(raw, 10)),
    durationSeconds: readNumberFlag(args, '--duration', (raw) => Number.parseFloat(raw)),
    tags: readFlag(args, '--tags'),
    lyrics: readFlag(args, '--lyrics'),
    bpm: readNumberFlag(args, '--bpm', (raw) => Number.parseFloat(raw)),
    key: readFlag(args, '--key'),
    instrumental,
    audioUrl: readFlag(args, '--audio-url'),
    audioCheckpoint: readFlag(args, '--audio-checkpoint') ?? DEFAULT_ACE_STEP_CHECKPOINT,
    audioOutputDir: readFlag(args, '--audio-output-dir') ?? DEFAULT_ACE_STEP_OUTPUT_DIR,
    audioOutputMount,
    timeoutSeconds,
  };
};

/**
 * Builds the reader that pulls an engine-written artifact off the host.
 *
 * The ACE-Step server writes the WAV to a path on ITS filesystem and returns
 * the path; the CLI reads the same file through the shared models mount. A
 * path outside the configured engine output directory is resolved by base
 * name so a server that rewrites the path still works.
 */
const makeArtifactReader = (engineOutputDir: string, hostMount: string): ArtifactReader => {
  const hostRoot = resolve(hostMount);
  return async (enginePath: string): Promise<Uint8Array> => {
    const relative = enginePath.startsWith(engineOutputDir)
      ? enginePath.slice(engineOutputDir.length).replace(/^\/+/, '')
      : basename(enginePath);
    const hostPath = resolve(join(hostRoot, relative));
    if (!hostPath.startsWith(hostRoot)) {
      throw new Error(`Refusing to read "${enginePath}" — it escapes ${hostRoot}`);
    }
    const file = Bun.file(hostPath);
    if (!(await file.exists())) {
      throw new Error(
        `ACE-Step reported "${enginePath}" but ${hostPath} does not exist — is the models volume a host bind mount? Set MODELS_PATH (or --audio-output-mount) to the directory the engine writes into.`,
      );
    }
    return new Uint8Array(await file.arrayBuffer());
  };
};

/** Reads a JSON fragment written by a previous run, or undefined when absent. */
const readJson = <T>(path: string): T | undefined => {
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as T;
  } catch (error) {
    if (error && typeof error === 'object' && 'code' in error && error.code === 'ENOENT') {
      return undefined;
    }
    throw error;
  }
};

const main = async (): Promise<void> => {
  const options = parseOptions();
  const recipe = requireRecipe(options.recipeId);
  const engineId = options.engine ?? recipe.engine ?? 'sdcpp';

  const baseUrl =
    options.baseUrl ??
    (engineId === 'ace-step' ? (options.audioUrl ?? ACE_STEP_SERVER) : SD_SERVER);

  const timeoutSeconds =
    options.timeoutSeconds ??
    (engineId === 'ace-step' ? DEFAULT_AUDIO_TIMEOUT_SECONDS : DEFAULT_TIMEOUT_SECONDS);

  console.log('🎨 generate:asset (C-510/C-511)\n');
  console.log(`  Recipe:  ${options.recipeId}`);
  console.log(`  Prompt:  ${options.prompt}`);
  console.log(`  Engine:  ${engineId}`);
  console.log(`  Endpoint: ${baseUrl}`);
  console.log(`  Timeout: ${timeoutSeconds}s`);
  console.log(`  Out:     ${options.outDir}\n`);

  if (engineId === 'ace-step' && options.audioOutputMount === undefined) {
    throw new Error(
      "ACE-Step writes the generated audio on the engine's own filesystem, so the CLI needs the matching host directory. Set MODELS_PATH to your models bind mount, or pass --audio-output-mount <dir>.",
    );
  }

  const engineOptions =
    engineId === 'ace-step' && options.audioOutputMount !== undefined
      ? {
          aceStep: {
            checkpointPath: options.audioCheckpoint,
            outputDir: options.audioOutputDir,
            readArtifact: makeArtifactReader(options.audioOutputDir, options.audioOutputMount),
          },
        }
      : undefined;

  const staging = await runAssetGeneration({
    recipeId: options.recipeId,
    prompt: options.prompt,
    engineId: options.engine,
    baseUrl,
    queueWaitMs: timeoutSeconds * 1000,
    engineOptions,
    overrides: {
      model: options.model,
      negativePrompt: options.negativePrompt,
      width: options.width,
      height: options.height,
      steps: options.steps,
      cfgScale: options.cfgScale,
      seed: options.seed,
      durationSeconds: options.durationSeconds,
      tags: options.tags,
      lyrics: options.lyrics,
      bpm: options.bpm,
      key: options.key,
      instrumental: options.instrumental,
    },
    onProgress: (progress) => {
      process.stdout.write(
        `\r  ${progress.label} ${Math.round(progress.fraction * 100)}%          `,
      );
    },
  });

  process.stdout.write('\n');

  const entry = staging.manifest.assets[staging.descriptor.tag];
  if (!entry) {
    // Unreachable by construction — asserted so a silent drop can never ship.
    throw new Error(
      `Internal error: no manifest entry produced for tag "${staging.descriptor.tag}"`,
    );
  }

  const assetPath = join(options.outDir, entry.path);
  mkdirSync(dirname(assetPath), { recursive: true });
  await Bun.write(assetPath, staging.bytes);

  // Merge into the existing staging fragments so repeated runs accumulate.
  const existingManifest = readJson<AssetManifest>(join(options.outDir, MANIFEST_FILENAME));
  const manifest: AssetManifest = existingManifest
    ? {
        ...existingManifest,
        scannedAt: staging.manifest.scannedAt,
        assets: { ...existingManifest.assets, ...staging.manifest.assets },
        byCategory: { ...existingManifest.byCategory },
      }
    : staging.manifest;
  if (existingManifest) {
    const categoryEntries = manifest.byCategory[staging.descriptor.category] ?? [];
    manifest.byCategory[staging.descriptor.category] = [
      ...categoryEntries.filter((existing) => existing.tag !== staging.descriptor.tag),
      entry,
    ];
  }
  manifest.count = Object.keys(manifest.assets).length;
  await Bun.write(join(options.outDir, MANIFEST_FILENAME), JSON.stringify(manifest, null, 2));

  const existingHashes = readJson<AssetHashesFile>(join(options.outDir, HASHES_FILENAME));
  const hashes: AssetHashesFile = existingHashes
    ? {
        scannedAt: staging.hashes.scannedAt,
        hashes: { ...existingHashes.hashes, ...staging.hashes.hashes },
      }
    : staging.hashes;
  await Bun.write(join(options.outDir, HASHES_FILENAME), JSON.stringify(hashes, null, 2));

  await Bun.write(
    join(options.outDir, DESCRIPTOR_FILENAME),
    JSON.stringify(staging.descriptor, null, 2),
  );

  console.log(`✓ ${entry.path}  ${(staging.descriptor.sizeBytes / 1024).toFixed(1)}KB`);
  console.log(`  tag:        ${staging.descriptor.tag}`);
  console.log(`  category:   ${staging.descriptor.category}`);
  console.log(`  sha256:     ${staging.descriptor.sha256}`);
  console.log(`  provenance: ${staging.descriptor.provenance.source}`);
  if (staging.descriptor.model !== undefined) {
    console.log(`  model:      ${staging.descriptor.model}`);
  }
  if (staging.descriptor.seed !== undefined) {
    console.log(`  seed:       ${staging.descriptor.seed}`);
  }
  console.log(`\nStaged in: ${options.outDir}`);
  console.log('  manifest.json + hashes.json are consumable by generate_asset_seed.ts');
};

main().catch((error) => {
  const message = error instanceof Error ? error.message : String(error);
  console.error(`\n✗ ${message}`);
  process.exit(1);
});
