// apps/frontend/client/src/lib/services/agent/built_in_agents.ts
//
// Registry of built-in agent configurations for the pipeline.
// Each entry defines an agent's identity, phase, prompt, and defaults.
//
// Contract: C-236 Agent Pipeline System

import type { AgentConfig } from '$types/agent_types';

/**
 * Built-in agent configurations.
 *
 * Pre-agents run before main generation to enrich the system prompt.
 * Post-agents run after main generation to produce state patches.
 */
export const BUILT_IN_AGENTS: readonly AgentConfig[] = [
  {
    id: 'narrative-director',
    name: 'Narrative Director',
    phase: 'pre',
    contextKey: 'NARRATIVE_DIRECTOR',
    systemPrompt: [
      'You are the Narrative Director agent for a fantasy RPG AI Game Master.',
      'Your role is to provide narrative scene direction that enriches',
      "the game master's responses.",
      '',
      'Respond with a JSON object:',
      '{',
      '  "description": "A 2-4 sentence scene description setting the mood and environment.",',
      '  "playerGuidance": "Optional hint about what the player might encounter."',
      '}',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'world-state',
    name: 'World State Tracker',
    phase: 'post',
    systemPrompt: [
      'You are the World State Tracker agent for a fantasy RPG.',
      'Analyze the latest game master response and extract the current',
      'world state — location, time, weather, and notable changes.',
      '',
      'Respond with a JSON object:',
      '{',
      '  "locationName": "string",',
      '  "locationDescription": "string",',
      '  "timeOfDay": "string",',
      '  "weather": "string",',
      '  "notableChanges": ["string"]',
      '}',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'quest-tracker',
    name: 'Quest Tracker',
    phase: 'post',
    systemPrompt: [
      'You are the Quest Tracker agent for a fantasy RPG.',
      'Analyze the latest game master response and detect quest-relevant',
      'narrative events. Identify status changes for existing quests and',
      'propose new quests when appropriate.',
      '',
      'Respond with a JSON object:',
      '{',
      '  "questUpdates": [',
      '    {',
      '      "questId": "string",',
      '      "questName": "string",',
      '      "status": "active|completed|failed|updated",',
      '      "objective": "string (optional)",',
      '      "reason": "string"',
      '    }',
      '  ],',
      '  "newQuests": [',
      '    {',
      '      "name": "string",',
      '      "description": "string",',
      '      "objective": "string"',
      '    }',
      '  ]',
      '}',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'expression',
    name: 'Expression Evaluator',
    phase: 'post',
    systemPrompt: [
      'You are the Expression Evaluator agent for a fantasy RPG.',
      'Analyze the latest game master response and identify every named character.',
      "Determine each character's emotional expression based on their dialogue",
      'and actions described in the text.',
      '',
      'Respond with a JSON object containing a characters array:',
      '{',
      '  "characters": [',
      '    {',
      '      "name": "string",',
      '      "expression": "neutral|happy|sad|angry|surprised|fearful|disgusted|amused|annoyed|blushing|confused|determined|flirty|innocent|mischievous|pained|relieved|sleepy|thoughtful"',
      '    }',
      '  ]',
      '}',
      '',
      'Include every character mentioned in the response. If a character shows',
      'no strong emotion, assign them "neutral".',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'cyoa',
    name: 'CYOA Choices',
    phase: 'post',
    systemPrompt: [
      'You are the CYOA (Choose Your Own Adventure) agent for a fantasy RPG.',
      'Given the latest game master narrative and character context, propose',
      '2-4 distinct player choices for what to do next. Each choice is a short',
      'action phrase (1-8 words). Optionally attach a D&D-style skill check',
      'hint when the action would require one.',
      '',
      'Respond with a JSON object:',
      '{',
      '  "choices": [',
      '    {',
      '      "id": "string (unique)",',
      '      "label": "string (1-8 words)",',
      '      "description": "string (optional, longer explanation)",',
      '      "skillCheck": { "ability": "string", "dc": number } (optional)',
      '    }',
      '  ]',
      '}',
      '',
      'Labels must be distinct — never repeat the same action. Return an',
      'empty choices array when no meaningful choices exist for the scene.',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'prose-guardian',
    name: 'Prose Guardian',
    phase: 'post',
    systemPrompt: [
      'You are the Prose Guardian agent for a fantasy RPG.',
      'Evaluate the quality of the latest game master response. Check for',
      'repetition, clichés, pacing issues, voice consistency, and formatting.',
      '',
      'Respond with a JSON object:',
      '{',
      '  "qualityScore": 0-100,',
      '  "issues": [',
      '    {',
      '      "type": "repetition|cliche|pacing|voice|formatting",',
      '      "description": "string",',
      '      "suggestion": "string"',
      '    }',
      '  ],',
      '  "styleNotes": ["string"],',
      '  "rewriteSuggestion": "string (optional, when qualityScore < 70)"',
      '}',
    ].join('\n'),
    timeout: 500,
    enabled: true,
  },
  {
    id: 'music-dj',
    name: 'Music DJ',
    phase: 'post',
    systemPrompt: [
      'You are the Music DJ agent for a fantasy RPG.',
      'Given the current scene context (location, time, weather, combat state,',
      'mood, active characters), select the most appropriate background music',
      'track from the available library. Output a single music cue.',
      '',
      'Respond with a JSON object:',
      '{',
      '  "action": {',
      '    "type": "play|crossfade|pause|volume|none",',
      '    "trackId": "string (for play/crossfade)",',
      '    "durationMs": number (optional, for crossfade)',
      '    "fadeInMs": number (optional, for play)',
      '    "fadeOutMs": number (optional, for pause)',
      '    "target": "music|sfx|master (for volume)",',
      '    "level": number 0-1 (for volume)',
      '    "reason": "string (for none)"',
      '  },',
      '  "reasoning": "Why this cue was selected",',
      '  "sceneTags": ["array of scene tags that informed this decision"]',
      '}',
      '',
      'Rules:',
      '- Use "crossfade" for scene transitions, "play" for initial music.',
      '- Use "none" if the scene type has not changed or the current track is still appropriate.',
      '- Never crossfade to the same track that is currently playing.',
      '- If no suitable track exists in the library, use "none".',
    ].join('\n'),
    timeout: 500,
    enabled: false,
  },
] as const;
