// packages/shared/types/src/lib/media/generation.ts
//
// Engine-agnostic generation contract (C-510). Derived from the TypeBox
// schemas in `@aikami/schemas` where a runtime validator exists; the client
// contract itself (functions, `Uint8Array`) is hand-written here because it
// crosses the Bun-CLI ↔ browser boundary and cannot be schema'd.
//
// `GenerationEngineId` deliberately reuses `ImageEngineId` minus `auto` — a
// second hand-written union would drift from the persisted preference type.
//
// Contract: C-510 Engine-Agnostic Asset Generation Pipeline

import type {
  AssetRecipeSchema,
  GeneratedAssetSchema,
  GenerationCapabilitiesSchema,
  GenerationEngineIdSchema,
  GenerationModalitySchema,
  GenerationRequestSchema,
} from '@aikami/schemas';
import type { Static } from 'typebox';
import type { ImageEngineId } from './image_engine.ts';

// ---------------------------------------------------------------------------
// Schema-derived
// ---------------------------------------------------------------------------

export type GenerationModality = Static<typeof GenerationModalitySchema>;
export type GenerationCapabilities = Static<typeof GenerationCapabilitiesSchema>;
export type GenerationRequest = Static<typeof GenerationRequestSchema>;
export type AssetRecipe = Static<typeof AssetRecipeSchema>;
export type GeneratedAsset = Static<typeof GeneratedAssetSchema>;

/**
 * Concrete engine id — the resolved result of `ImageEngineId` minus `auto`,
 * exactly as `ResolvedImageEngineId` is on the client. Never hand-write a
 * second union: it would silently drift from the persisted preference type.
 */
export type GenerationEngineId = Exclude<ImageEngineId, 'auto'>;

/** Compile-time guard that the schema and the derived union agree. */
export type _GenerationEngineIdSchemaMatches =
  Static<typeof GenerationEngineIdSchema> extends GenerationEngineId ? true : never;

// ---------------------------------------------------------------------------
// Engine contract
// ---------------------------------------------------------------------------

/** Model descriptor returned by an engine's model list. */
export type GenerationModelInfo = {
  readonly id: string;
  readonly description: string;
};

/** Progress pushed from an engine into a caller. */
export type GenerationProgress = {
  /** 0..1. Engines without fine-grained progress emit 0 then 1. */
  readonly fraction: number;
  /** Engine-agnostic human-readable label. */
  readonly label: string;
};

/** Result of an engine generation. */
export type GenerationResult = {
  /** Generated bytes. The Bun CLI has no `Blob` — the frontend adapter bridges. */
  readonly bytes: Uint8Array;
  readonly mimeType: string;
  readonly width?: number;
  readonly height?: number;
  readonly engine: GenerationEngineId;
  readonly seed?: number;
  readonly metadata: Record<string, string | number>;
};

/** Engine callbacks. */
export type GenerationCallbacks = {
  /** Abort signal — the engine's native cancel is issued on abort. */
  readonly signal?: AbortSignal;
  /** Progress callback (0..1 fraction, engine-agnostic label). */
  readonly onProgress?: (progress: GenerationProgress) => void;
};

/**
 * Narrow, framework-agnostic generation engine. One implementation per
 * engine, capability flags on the instance, and a factory that selects one.
 * Implementations must be free of Svelte runes and DOM-only globals.
 */
export type GenerationEngineClient = {
  /** Engine id. */
  readonly id: GenerationEngineId;
  /** What this engine produces. */
  readonly modality: GenerationModality;
  /** Capability flags — drives recipe validation and UI affordances. */
  readonly capabilities: GenerationCapabilities;
  /** Whether the engine is reachable right now. */
  healthCheck(options?: { signal?: AbortSignal }): Promise<boolean>;
  /** List available models/checkpoints. */
  listModels(options?: { signal?: AbortSignal }): Promise<readonly GenerationModelInfo[]>;
  /** Generate. Resolves with bytes; rejects with `AbortError` on abort. */
  generate(request: GenerationRequest, callbacks?: GenerationCallbacks): Promise<GenerationResult>;
};
