name: Pull Request Notifications

on:
    pull_request:
        types: [opened, reopened]

jobs:
    notify-on-pr:
        name: Notify Discord on Pull Request
        runs-on: ubuntu-latest
        steps:
            - name: Notify Discord about New PR
              uses: tsickert/discord-webhook@v6.0.0
              with:
                  webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
                  embed-title: '🔔 New Pull Request Created!'
                  embed-description: |
                      **Title:** ${{ github.event.pull_request.title }}
                      **Description:** ${{ github.event.pull_request.body }}
                      **Branch:** ${{ github.event.pull_request.head.ref }}
                      **Created by:** ${{ github.actor }}
                      [View Pull Request](${{ github.event.pull_request.html_url }})
                  embed-color: 3447003 # Dark blue
